import createNextIntlPlugin from "next-intl/plugin";
import withBundleAnalyzer from "@next/bundle-analyzer";
import path from "path";
import { fileURLToPath } from "url";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

if (process.env.NETLIFY === "true" && !process.env.NEXT_PUBLIC_SITE_URL) {
  process.env.NEXT_PUBLIC_SITE_URL = process.env.URL || process.env.DEPLOY_PRIME_URL;
}

// Bridge legacy Netlify var names → Next.js public vars (inlined at build time)
if (!process.env.NEXT_PUBLIC_SUPABASE_URL?.trim() && process.env.SUPABASE_URL?.trim()) {
  process.env.NEXT_PUBLIC_SUPABASE_URL = process.env.SUPABASE_URL.trim();
}
if (!process.env.NEXT_PUBLIC_SUPABASE_URL?.trim() && process.env.SUPABASE_DATABASE_URL?.trim()) {
  const dbUrl = process.env.SUPABASE_DATABASE_URL.trim();
  // Netlify Supabase integration provisions SUPABASE_DATABASE_URL as the
  // project REST endpoint (e.g. "https://[ref].supabase.co") — despite the
  // misleading name, it is NOT a postgres connection string. Use it directly.
  if (/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(dbUrl)) {
    process.env.NEXT_PUBLIC_SUPABASE_URL = dbUrl.replace(/\/$/, "");
  } else {
    // Fallback: older integrations may provision a postgres connection string.
    // Extract [ref] and derive the REST endpoint.
    const m = dbUrl.match(/postgres\.([a-z0-9]+):/);
    if (m) process.env.NEXT_PUBLIC_SUPABASE_URL = `https://${m[1]}.supabase.co`;
  }
}
if (!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() && process.env.SUPABASE_ANON_KEY?.trim()) {
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY.trim();
}

const isDev = process.env.NODE_ENV !== "production";

const securityHeaders = [
  { key: "X-DNS-Prefetch-Control", value: "on" },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  {
    key: "Strict-Transport-Security",
    value: "max-age=31536000; includeSubDomains; preload",
  },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  },
  {
    key: "Content-Security-Policy",
    // Why script-src keeps 'unsafe-inline': the App Router emits inline executable
    // bootstrap scripts in every HTML response (React streaming markers, $RB/$RV
    // runtime, and the `self.__next_f.push(...)` RSC flight payload). They are
    // generated by Next.js with no stable content hash, and noncing them requires
    // per-request rendering (nonce middleware + dynamic rendering), which would
    // break this site's static generation. Our own inline executable scripts
    // (preference bootstrap, gtag init) have been moved to /pref-bootstrap.js and
    // /ga-init.js so the only remaining inline code is framework-generated.
    // To go strict later: switch to dynamic rendering + a nonce middleware that
    // sets the CSP header per request, then remove 'unsafe-inline' here.
    value: [
      "default-src 'self'",
      `script-src 'self' 'unsafe-inline' https://www.googletagmanager.com${isDev ? " 'unsafe-eval'" : ""}`,
      // style-src keeps 'unsafe-inline' (unlike script-src's future goal): Tailwind
      // runtime-injected styles, Confetti <style> tags, and the motion library all
      // require it. There is no nonce/hash mechanism for these either.
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: blob:",
      "font-src 'self' data:",
      // Canonical connect tokens live in security-headers.json (CI: npm run check:security-headers).
      "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.ingest.sentry.io https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "object-src 'none'",
    ].join("; "),
  },
];

const isAnalyze = process.env.ANALYZE === "true";

const bundleAnalyzer = withBundleAnalyzer({
  enabled: isAnalyze,
  // Default off so `npm run analyze` does not hang/open a browser in CI or agents.
  // Set OPEN_ANALYZER=true to open the static HTML report locally.
  openAnalyzer: process.env.OPEN_ANALYZER === "true",
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Keep `next dev` on `.next` while an analyze build runs in parallel.
  ...(isAnalyze ? { distDir: ".next-analyze" } : {}),
  turbopack: {
    root: projectRoot,
  },
  allowedDevOrigins: ["127.0.0.1"],
  images: {
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 86400,
  },
  experimental: {
    optimizePackageImports: ["lucide-react"],
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: securityHeaders,
      },
    ];
  },
};

export default bundleAnalyzer(withNextIntl(nextConfig));
