import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./src/components/**/*.{js,ts,jsx,tsx,mdx}", "./src/app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-tint": "var(--color-surface-tint)",
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        tertiary: "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        error: "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        background: "var(--color-background)",
        "on-background": "var(--color-on-background)",
        "surface-variant": "var(--color-surface-variant)",
      },
      fontFamily: {
        hyperlegible: ["var(--font-atkinson)", "sans-serif"],
        sans: ["var(--font-atkinson)", "Atkinson Hyperlegible", "system-ui", "sans-serif"],
        display: ["var(--font-newsreader)", "Georgia", "serif"],
      },
      fontSize: {
        "headline-xl": ["42px", { lineHeight: "1.08", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg": ["34px", { lineHeight: "1.12", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["18px", { lineHeight: "1.65", fontWeight: "400" }],
        "label-lg": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-md": ["16px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.02em" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["30px", { lineHeight: "1.12", letterSpacing: "-0.025em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1.125rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        container: "1440px",
        readable: "72ch",
      },
      boxShadow: {
        card: "0 18px 36px -30px var(--shadow-color-heavy), 0 10px 22px -24px var(--shadow-color)",
        "card-hover": "0 28px 48px -32px var(--shadow-color-heavy), 0 16px 24px -26px var(--shadow-color)",
        "elevation-1": "0 12px 20px -18px var(--shadow-color), 0 6px 10px -10px var(--shadow-color)",
        "elevation-2": "0 22px 38px -28px var(--shadow-color-heavy), 0 10px 18px -18px var(--shadow-color)",
        "elevation-3": "0 36px 68px -34px var(--shadow-color-heavy), 0 14px 28px -26px var(--shadow-color)",
        floating: "0 42px 80px -40px var(--shadow-color-heavy), 0 16px 30px -22px var(--shadow-color)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        riseIn: {
          "0%": { opacity: "0", transform: "translateY(20px) scale(0.985)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        fadeIn: "fadeIn var(--motion-duration-slow) var(--motion-ease-entrance) both",
        riseIn: "riseIn var(--motion-duration-slow) var(--motion-ease-entrance) both",
        shimmer: "shimmer 1.8s linear infinite",
        slideDown: "slideDown var(--motion-duration-medium) var(--motion-ease-standard) both",
      },
      transitionTimingFunction: {
        premium: "var(--motion-ease-standard)",
        expressive: "var(--motion-ease-entrance)",
      },
    },
  },
  plugins: [typography],
};
export default config;
