import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f8f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3f484a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        outline: '#6f797a',
        'outline-variant': '#bfc8c9',
        'surface-tint': '#20686f',
        primary: '#004349',
        'on-primary': '#ffffff',
        'primary-container': '#0d5c63',
        'on-primary-container': '#90d2da',
        'inverse-primary': '#8fd1d9',
        secondary: '#3e6658',
        'on-secondary': '#ffffff',
        'secondary-container': '#c0ecda',
        'on-secondary-container': '#446c5e',
        tertiary: '#5c310d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#784722',
        'on-tertiary-container': '#fcb88a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#abeef6',
        'primary-fixed-dim': '#8fd1d9',
        'on-primary-fixed': '#002023',
        'on-primary-fixed-variant': '#004f55',
        'secondary-fixed': '#c0ecda',
        'secondary-fixed-dim': '#a5d0be',
        'on-secondary-fixed': '#002117',
        'on-secondary-fixed-variant': '#264e41',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#fcb889',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#693b17',
        background: '#f8f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
      },
      fontFamily: {
        'hyperlegible': ['"Atkinson Hyperlegible"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.25', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-lg': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['16px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.02em' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.25', fontWeight: '700' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '8px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container': '1100px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0, 67, 73, 0.04), 0 1px 2px rgba(0, 67, 73, 0.04)',
        'card-hover': '0 4px 6px rgba(0, 67, 73, 0.06), 0 2px 4px rgba(0, 67, 73, 0.04)',
        'elevation-2': '0 8px 16px rgba(0, 67, 73, 0.08), 0 4px 8px rgba(0, 67, 73, 0.04)',
      },
    },
  },
  plugins: [],
};
export default config;
