import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import { getAllLessonsFromMdx } from "../src/lib/lessons/mdxParser";

export interface SearchEntry {
  id: string;
  title: string;
  description: string;
  category: string;
  categoryId: string;
  content: string;
  url: string;
}

const locales = ["en", "es"] as const;

for (const locale of locales) {
  const lessons = getAllLessonsFromMdx(locale);
  const entries: SearchEntry[] = lessons.map((l) => ({
    id: l.id,
    title: l.title,
    description: l.description,
    category: l.category,
    categoryId: l.categoryId,
    content: l.content.sections.map((s) => `${s.title} ${s.content}`).join(" "),
    url: `/${locale}/learn/${l.id}`,
  }));

  const header = `// Auto-generated by scripts/build-search-index.ts — do not edit by hand.\n// Run: npm run content:bundle-search\n\n`;
  const outPath = path.join(process.cwd(), "src", "data", `searchIndex.${locale}.ts`);
  fs.writeFileSync(
    outPath,
    `${header}export interface SearchEntry {\n  id: string;\n  title: string;\n  description: string;\n  category: string;\n  categoryId: string;\n  content: string;\n  url: string;\n}\n\nexport const searchIndex: SearchEntry[] = ${JSON.stringify(entries, null, 2)} as const;\n`,
    "utf8"
  );
  execSync(`npx prettier --write ${outPath}`);
  console.log(`Wrote search index (${entries.length} entries) for ${locale}.`);
}
