import fs from "fs";
import path from "path";
import { getAllLessonsFromMdx } from "../src/lib/lessons/mdxParser";
import { getAllArticlesFromMdx } from "../src/lib/articles/mdxParser";
import { getAllGlossaryFromMdx } from "../src/lib/glossary/mdxParser";
import { getAllPathsFromMdx } from "../src/lib/paths/mdxParser";
import { formatWithPrettier } from "./lib/formatWithPrettier";

export type SearchEntryType = "lesson" | "article" | "glossary" | "path" | "tool";

export interface SearchEntry {
  id: string;
  type: SearchEntryType;
  title: string;
  description: string;
  category: string;
  categoryId: string;
  content: string;
  url: string;
}

const TOOL_ENTRIES: Omit<SearchEntry, "id">[] = [
  {
    type: "tool",
    title: "Visit Planner",
    description: "Build a list of questions to ask at your next appointment.",
    category: "Tools",
    categoryId: "tools",
    content: "visit planner questions doctor appointment checklist",
    url: "/tools/visit-planner",
  },
  {
    type: "tool",
    title: "Visit Checklist",
    description: "Track what to bring and do before, during, and after a visit.",
    category: "Tools",
    categoryId: "tools",
    content: "visit checklist before during after appointment",
    url: "/tools/visit-checklist",
  },
  {
    type: "tool",
    title: "Care Guide",
    description: "Find out where to go for care based on your symptoms.",
    category: "Tools",
    categoryId: "tools",
    content: "care guide urgent emergency primary care symptoms",
    url: "/tools/care-guide",
  },
];

const locales = ["en", "es"] as const;

for (const locale of locales) {
  const lessons = getAllLessonsFromMdx(locale);
  const articles = getAllArticlesFromMdx(locale);
  const glossary = getAllGlossaryFromMdx(locale);
  const paths = getAllPathsFromMdx(locale);

  const lessonEntries: SearchEntry[] = lessons.map((l) => ({
    id: l.id,
    type: "lesson",
    title: l.title,
    description: l.description,
    category: l.category,
    categoryId: l.categoryId,
    content: l.content.sections.map((s) => `${s.title} ${s.content}`).join(" "),
    url: `/learn/${l.id}`,
  }));

  const articleEntries: SearchEntry[] = articles.map((a) => ({
    id: a.id,
    type: "article",
    title: a.title,
    description: a.description,
    category: a.category,
    categoryId: "articles",
    content: a.content.sections.map((s) => `${s.title} ${s.content}`).join(" "),
    url: `/articles/${a.id}`,
  }));

  const glossaryEntries: SearchEntry[] = glossary.map((g) => ({
    id: g.id,
    type: "glossary",
    title: g.term,
    description: g.definition.slice(0, 160),
    category: g.category,
    categoryId: "glossary",
    content: g.definition,
    url: `/glossary/${g.id}`,
  }));

  const pathEntries: SearchEntry[] = paths.map((p) => ({
    id: p.id,
    type: "path",
    title: p.title,
    description: p.description,
    category: "Learning Paths",
    categoryId: "paths",
    content: `${p.title} ${p.description} ${p.lessons.join(" ")}`,
    url: `/learning-paths#${p.id}`,
  }));

  const toolEntries: SearchEntry[] = TOOL_ENTRIES.map((t, i) => ({
    id: `tool-${i}`,
    ...t,
  }));

  const entries = [...lessonEntries, ...articleEntries, ...glossaryEntries, ...pathEntries, ...toolEntries];

  const header = `// Auto-generated by scripts/build-search-index.ts — do not edit by hand.\n// Run: npm run content:bundle-search\n\n`;
  const outPath = path.join(process.cwd(), "src", "data", `searchIndex.${locale}.ts`);
  fs.writeFileSync(
    outPath,
    `${header}export type SearchEntryType = "lesson" | "article" | "glossary" | "path" | "tool";\n\nexport interface SearchEntry {\n  id: string;\n  type: SearchEntryType;\n  title: string;\n  description: string;\n  category: string;\n  categoryId: string;\n  content: string;\n  url: string;\n}\n\nexport const searchIndex: SearchEntry[] = ${JSON.stringify(entries, null, 2)} as const;\n`,
    "utf8"
  );
  formatWithPrettier(outPath);
  console.log(`Wrote search index (${entries.length} entries) for ${locale}.`);
}
