import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";
import { getAllArticlesFromMdx } from "../src/lib/articles/mdxParser";
import { assertLocaleIdParity } from "./lib/validateLocaleParity";

const en = getAllArticlesFromMdx("en");
const es = getAllArticlesFromMdx("es");

assertLocaleIdParity(en, es, "articles");

const dataDir = path.join(process.cwd(), "src", "data");
const header = `// Auto-generated by scripts/bundle-articles.ts — do not edit by hand.\n\nimport type { Article } from "@/types/article";\n\n`;

const writeLocaleBundle = (locale: "en" | "es", articles: typeof en) => {
  const outPath = path.join(dataDir, `articleBundles.${locale}.ts`);
  fs.writeFileSync(
    outPath,
    `${header}export const articles: Article[] = ${JSON.stringify(articles, null, 2)} as const;\n`,
    "utf8"
  );
  execFileSync("npx", ["prettier", "--write", outPath]);
};

writeLocaleBundle("en", en);
writeLocaleBundle("es", es);

fs.writeFileSync(
  path.join(dataDir, "articleBundles.ts"),
  `${header}import { articles as en } from "./articleBundles.en";\nimport { articles as es } from "./articleBundles.es";\n\nexport const articleBundles: Record<"en" | "es", Article[]> = { en, es } as const;\n`,
  "utf8"
);

console.log(`Wrote article bundles (${en.length} EN, ${es.length} ES articles).`);
