import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";
import { getAllGlossaryFromMdx } from "../src/lib/glossary/mdxParser";
import { assertLocaleIdParity } from "./lib/validateLocaleParity";

const en = getAllGlossaryFromMdx("en");
const es = getAllGlossaryFromMdx("es");

assertLocaleIdParity(en, es, "glossary");

const dataDir = path.join(process.cwd(), "src", "data");
const header = `// Auto-generated by scripts/bundle-glossary.ts — do not edit by hand.\n// Edit content/glossary/{en,es}/*.mdx then run: npm run content:bundle-glossary\n\nimport type { GlossaryTerm } from "@/types/glossary";\n\n`;

const writeLocaleBundle = (locale: "en" | "es", terms: typeof en) => {
  const outPath = path.join(dataDir, `glossaryBundles.${locale}.ts`);
  fs.writeFileSync(
    outPath,
    `${header}export const terms: GlossaryTerm[] = ${JSON.stringify(terms, null, 2)} as const;\n`,
    "utf8"
  );
  execFileSync("npx", ["prettier", "--write", outPath], { shell: process.platform === "win32" });
  return outPath;
};

writeLocaleBundle("en", en);
writeLocaleBundle("es", es);

fs.writeFileSync(
  path.join(dataDir, "glossaryBundles.ts"),
  `${header}import { terms as en } from "./glossaryBundles.en";\nimport { terms as es } from "./glossaryBundles.es";\n\nexport const glossaryBundles: Record<"en" | "es", GlossaryTerm[]> = { en, es } as const;\n`,
  "utf8"
);

console.log(`Wrote glossary bundles (${en.length} EN, ${es.length} ES terms).`);
