import fs from "fs";
import path from "path";
import { getAllGlossaryFromMdx } from "../src/lib/glossary/mdxParser";
import { assertLocaleIdParity } from "./lib/validateLocaleParity";

async function main() {
  const en = await getAllGlossaryFromMdx("en");
  const es = await getAllGlossaryFromMdx("es");

  assertLocaleIdParity(en, es, "glossary");

  const dataDir = path.join(process.cwd(), "src", "data");
  const header = `// Auto-generated by scripts/bundle-glossary.ts — do not edit by hand.\n// Edit content/glossary/{en,es}/*.mdx then run: npm run content:bundle-glossary\n\nimport type { GlossaryTerm } from "@/types/glossary";\n\n`;
  const combinedHeader = `// Auto-generated by scripts/bundle-glossary.ts — do not edit by hand.\n// Edit content/glossary/{en,es}/*.mdx then run: npm run content:bundle-glossary\n// Server/SSG only. Do not import this combined barrel from 'use client' modules.\n// Client code must dynamic-import ./glossaryBundles.en or ./glossaryBundles.es.\n\nimport type { GlossaryTerm } from "@/types/glossary";\n\n`;

  const writeLocaleBundle = (locale: "en" | "es", terms: typeof en) => {
    const outPath = path.join(dataDir, `glossaryBundles.${locale}.ts`);
    fs.writeFileSync(
      outPath,
      `${header}export const terms: GlossaryTerm[] = ${JSON.stringify(terms, null, 2)} as const;\n`,
      "utf8"
    );
    return outPath;
  };

  writeLocaleBundle("en", en);
  writeLocaleBundle("es", es);

  fs.writeFileSync(
    path.join(dataDir, "glossaryBundles.ts"),
    `${combinedHeader}import { terms as en } from "./glossaryBundles.en";\nimport { terms as es } from "./glossaryBundles.es";\n\nexport const glossaryBundles: Record<"en" | "es", GlossaryTerm[]> = { en, es } as const;\n`,
    "utf8"
  );

  console.log(`Wrote glossary bundles (${en.length} EN, ${es.length} ES terms).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
