import fs from "fs";
import path from "path";
import { getAllLessonsFromMdx } from "../src/lib/lessons/mdxParser";
import { assertLocaleIdParity } from "./lib/validateLocaleParity";

async function main() {
  const en = await getAllLessonsFromMdx("en");
  const es = await getAllLessonsFromMdx("es");

  assertLocaleIdParity(en, es, "lessons");

  const dataDir = path.join(process.cwd(), "src", "data");
  const header = `// Auto-generated by scripts/bundle-lessons.ts — do not edit by hand.\n// Edit content/lessons/{en,es}/*.mdx then run: npm run content:bundle-lessons\n\nimport type { Lesson } from "@/types/lesson";\n\n`;
  const combinedHeader = `// Auto-generated by scripts/bundle-lessons.ts — do not edit by hand.\n// Edit content/lessons/{en,es}/*.mdx then run: npm run content:bundle-lessons\n// Server/SSG only. Do not import this combined barrel from 'use client' modules.\n// Client code must dynamic-import ./lessonBundles.en or ./lessonBundles.es.\n\nimport type { Lesson } from "@/types/lesson";\n\n`;

  const writeLocaleBundle = (locale: "en" | "es", lessons: typeof en) => {
    const outPath = path.join(dataDir, `lessonBundles.${locale}.ts`);
    fs.writeFileSync(
      outPath,
      `${header}export const lessons: Lesson[] = ${JSON.stringify(lessons, null, 2)} as const;\n`,
      "utf8"
    );
    return outPath;
  };

  writeLocaleBundle("en", en);
  writeLocaleBundle("es", es);

  const indexPath = path.join(dataDir, "lessonBundles.ts");
  fs.writeFileSync(
    indexPath,
    `${combinedHeader}import { lessons as en } from "./lessonBundles.en";\nimport { lessons as es } from "./lessonBundles.es";\n\nexport const lessonBundles: Record<"en" | "es", Lesson[]> = { en, es } as const;\n`,
    "utf8"
  );

  const metaPath = path.join(dataDir, "lessonMeta.ts");
  const metaHeader = `// Auto-generated by scripts/bundle-lessons.ts — do not edit by hand.\n// Edit content/lessons/{en,es}/*.mdx then run: npm run content:bundle-lessons\n\n`;
  const lessonLevels: Record<string, string> = {};
  const beginnerLessonIds: string[] = [];

  for (const lesson of en) {
    lessonLevels[lesson.id] = lesson.level;
    if (lesson.level === "beginner") {
      beginnerLessonIds.push(lesson.id);
    }
  }

  fs.writeFileSync(
    metaPath,
    `${metaHeader}export const LESSON_LEVELS: Record<string, "beginner" | "intermediate" | "advanced"> = ${JSON.stringify(
      lessonLevels,
      null,
      2
    )} as const;\n\nexport const BEGINNER_LESSON_IDS: string[] = ${JSON.stringify(
      beginnerLessonIds,
      null,
      2
    )} as const;\n`,
    "utf8"
  );

  console.log(
    `Wrote lesson bundles (${en.length} EN, ${es.length} ES lessons) and lessonMeta.ts (${beginnerLessonIds.length} beginner lessons).`
  );
}
main().catch((e) => {
  console.error(e);
  process.exit(1);
});
