import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import { render } from "@testing-library/react";
import AppProviders from "@/components/AppProviders";

const messages = {
  nav: {
    home: "Home",
    learn: "Learn",
    paths: "Paths",
    tools: "Tools",
    dashboard: "Dashboard",
    glossary: "Glossary",
    about: "About",
    skipToContent: "Skip to content",
    taglineShort: "Health education for everyone",
    toggleNavigation: "Toggle navigation",
    mainNavigation: "Main navigation",
    mobileNavigation: "Mobile navigation",
    exploreByGoal: "Explore by goal",
    findRightResource: "Find the right resource",
    explore: "Explore",
    pathsTitle: "Learning Paths",
    pathsDescription: "Follow structured guides",
    learnTitle: "Learn",
    learnDescription: "Browse our library",
    glossaryTitle: "Glossary",
    glossaryDescription: "Find definitions",
    toolsTitle: "Tools",
    toolsDescription: "Use practical resources",
  },
  learn: {
    title: "What would you like to learn today?",
    description: "Clear, reliable guides",
    notFoundTitle: "Lesson not found",
    notFoundBody: "The lesson you are looking for is not available",
    backToLibrary: "Back to library",
    backToLessons: "Back to lessons",
    markComplete: "Mark as complete",
    markIncomplete: "Mark as not done",
    printLesson: "Print lesson",
    stillConfused: "Still confused?",
    sidebarBody: "Bring these questions to your next visit",
    tipCheckName: "Check the name",
    tipReadDose: "Read how many to take",
    tipWarnings: "Look for warnings",
    tipMissedDose: "Ask what happens if you miss a dose",
    pharmacistTip: "Pharmacists can explain labels",
    sidebarBodyDoctor: "Prepare for your next doctor's visit",
    tipDoctorAppointmentTime: "Write down the date and time",
    tipDoctorInsurance: "Bring your insurance card",
    tipDoctorQuestions: "Make a list of questions",
    tipDoctorMeds: "Bring all your current medications",
    doctorTip: "Your doctor is there to partner with you",
    sidebarBodyLabs: "Prepare for your lab tests",
    tipLabsFasting: "Check if you need to fast",
    tipLabsHydration: "Drink plenty of water",
    tipLabsComfort: "Wear comfortable clothing",
    tipLabsResults: "Ask when you will get results",
    labsTip: "Lab technicians can explain the process",
    keepLearning: "Keep learning",
    lastReviewed: "Last reviewed",
    sources: "Sources",
    takeQuiz: "Take quiz",
  },
  quiz: {
    description: "Test your knowledge of {title} with {count} questions.",
    passRequirement: "You need at least {score}% to pass.",
    startQuiz: "Start quiz",
    backToLesson: "Back to lesson",
    questionXofY: "Question {current} of {total}",
    answered: "{count} answered",
    previous: "Previous",
    next: "Next question",
    checkAnswer: "Check answer",
    seeResults: "See results",
    correct: "Correct!",
    incorrect: "Not quite.",
    explanation: "Explanation",
    scoreLabel: "You scored {score}% ({correct} of {total} correct)",
    passed: "You passed!",
    tryAgain: "Keep studying and try again.",
    retake: "Retake quiz",
  },
  search: {
    openSearch: "Open search",
    searchDialog: "Search lessons",
    placeholder: "Search lessons…",
    close: "Close search",
    noResults: "No lessons found. Try a different search term.",
  },
  onboarding: {
    welcome: "Welcome to Health Made Clear",
    subtitle: "Your guide to understanding health topics in plain language.",
    step1Title: "Learn at your own pace",
    step1Body: "Browse our library of clear lessons.",
    step2Title: "Follow learning paths",
    step2Body: "Structured guides help you build understanding.",
    step3Title: "Find what you need",
    step3Body: "Use search to quickly find the health topic.",
    getStarted: "Get started",
    close: "Close",
  },
  errors: {
    title: "Something went wrong",
    body: "We could not load this page.",
    retry: "Try again",
    home: "Go home",
    notFoundTitle: "Page not found",
    notFoundBody: "The page you are looking for does not exist.",
    goHome: "Go home",
  },
  disclaimer: {
    educational: "This content is for educational purposes only.",
    emergencyTitle: "Medical Emergency",
    emergencyBody: "If you are experiencing a medical emergency, call 911 immediately.",
    emergencyCall: "Call 911",
    emergencyCallAria: "Call emergency services",
  },
  glossary: {
    viewTerm: "View term",
  },
  about: {
    title: "About Health Made Clear",
    description: "We make health education accessible.",
    valueEducationTitle: "Evidence-based education",
    valueEducationBody: "All content is reviewed by medical professionals.",
    educationDetail: "Our content is based on current medical guidelines.",
    warningBody: "Always consult a healthcare provider.",
    whyMattersTitle: "Why it matters",
    whyMattersBody: "Health literacy saves lives.",
    valueEveryoneTitle: "Accessible to everyone",
    valueEveryoneBody: "Plain language, no jargon.",
    valueStructuredTitle: "Structured learning",
    valueStructuredBody: "Step-by-step learning paths.",
    joinBadge: "Join our community",
    joinTitle: "Ready to learn?",
    joinBody: "Start your health education journey today.",
    exploreLibrary: "Explore library",
    learnWithTools: "Learn with tools",
    contactTitle: "Contact us",
    contactBody: "Email us at ",
  },
  footer: {
    tagline: "Health Made Clear",
    rights: "All rights reserved.",
    privacy: "Privacy",
    accessibility: "Accessibility",
    about: "About",
  },
  hero: {
    badge: "New: Learning Paths & Quizzes",
    title: "Understand Your Health",
    subtitle: "Clear, reliable health education in plain language.",
    startLearning: "Start Learning",
    browseGlossary: "Browse Glossary",
    preparedVisits: "Prepared Visits",
    preparedVisitsBody: "Know what to ask and bring.",
    clearLessons: "Clear Lessons",
    clearLessonsBody: "Plain language, no jargon.",
  },
  sectionNav: {
    exploreByGoal: "Explore by goal",
    findRightResource: "Find the right resource for you",
    pathsTitle: "Learning Paths",
    pathsDescription: "Follow structured guides to master health topics step by step.",
    learnTitle: "Learn",
    learnDescription: "Browse our library of clear lessons on common health topics.",
    glossaryTitle: "Glossary",
    glossaryDescription: "Find plain-language definitions for medical terms.",
    toolsTitle: "Tools",
    toolsDescription: "Use practical resources for visits and care decisions.",
    explore: "Explore",
  },
} as const;

export function renderWithIntl(
  ui: ReactNode,
  options: { locale?: "en" | "es"; localePrefix?: "always" | "never" } = {}
) {
  const { locale = "en", localePrefix = "never" } = options;

  return render(
    <NextIntlClientProvider messages={messages} locale={locale}>
      <AppProviders locale={locale}>{ui}</AppProviders>
    </NextIntlClientProvider>
  );
}
