// Auto-generated by scripts/bundle-articles.ts — do not edit by hand.

import type { Article } from "@/types/article";

export const articles: Article[] = [
  {
    id: "choosing-primary-care-doctor",
    title: "How to Choose a Primary Care Doctor",
    description:
      "Practical steps to find a clinician who fits your needs, insurance, and communication style.",
    category: "Healthcare Navigation",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Why Primary Care Matters",
          content:
            "A primary care provider (PCP) is your main doctor for checkups, chronic conditions, referrals, and everyday concerns. A good match makes it easier to stay on top of preventive care and catch problems early.",
        },
        {
          title: "Start With Your Insurance",
          content:
            "Use your plan's provider directory to find in-network doctors. Out-of-network care usually costs much more. Confirm the office is accepting new patients before you book.",
        },
        {
          title: "Consider Logistics",
          content:
            "- **Location** — reasonable travel for sick visits and labs\r\n- **Hours** — evenings or weekends if you work standard hours\r\n- **Hospital affiliation** — matters if you may need inpatient care\r\n- **Telehealth** — useful for follow-ups and minor issues",
        },
        {
          title: "Evaluate Fit at the First Visit",
          content:
            "Ask yourself:\r\n\r\n- Did the doctor listen without rushing?\r\n- Were explanations clear?\r\n- Did you feel respected?\r\n- Was the staff helpful with scheduling and billing questions?\r\n\r\n:::info\r\nIt is okay to switch PCPs if the relationship is not working. Your comfort affects how honestly you share symptoms.\r\n:::",
        },
        {
          title: "Questions to Ask",
          content:
            "- Who covers for my doctor when they are away?\r\n- How do I reach someone after hours?\r\n- How are test results communicated?\r\n- Can I use the patient portal for refills and messages?",
        },
      ],
    },
  },
  {
    id: "annual-physical-what-to-expect",
    title: "What Happens at an Annual Physical",
    description: "What to expect during a routine wellness visit and how to prepare.",
    category: "Preventive Care",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Purpose of a Wellness Visit",
          content:
            "An annual physical (wellness visit) focuses on prevention — not just treating illness. Your clinician reviews history, checks vitals, discusses screenings, and updates vaccines.",
        },
        {
          title: "Typical Components",
          content:
            "- Height, weight, blood pressure, heart and lung exam\r\n- Review of medications and allergies\r\n- Age-appropriate cancer and chronic disease screening orders\r\n- Vaccine updates\r\n- Lifestyle counseling (sleep, activity, nutrition, tobacco)",
        },
        {
          title: "How to Prepare",
          content:
            "Bring your medication list, recent test results, and questions. Mention new symptoms even if they seem minor.\r\n\r\n:::warning\r\nA wellness visit is not the same as an urgent care visit for acute illness. Book separately if you are sick and need same-day treatment.\r\n:::",
        },
        {
          title: "After the Visit",
          content:
            "You may receive orders for blood work or referrals. Ask when results will be ready and how you will be notified.\r\n\r\n:::success\r\nUse preventive benefits your insurance covers — many screenings have no out-of-pocket cost when in-network.\r\n:::",
        },
      ],
    },
  },
  {
    id: "pharmacy-benefits-basics",
    title: "Understanding Your Pharmacy Benefits",
    description: "Formularies, tiers, prior authorization, and how to lower prescription costs.",
    category: "Insurance & Billing",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Key Terms",
          content:
            "- **Formulary** — list of drugs your plan covers\r\n- **Tier** — cost level (generic tier 1 is usually cheapest)\r\n- **Prior authorization** — insurer approval before they pay for certain drugs\r\n- **Step therapy** — try a preferred drug before a more expensive one",
        },
        {
          title: "Reading Your Drug Card",
          content:
            "Your insurance card may list a pharmacy help line and Rx BIN/PCN/group numbers pharmacists use to bill claims.",
        },
        {
          title: "Saving Money",
          content:
            "- Ask for generics when appropriate\r\n- Use in-network pharmacies\r\n- Compare 90-day mail-order prices\r\n- Ask about copay assistance for brand drugs\r\n\r\n:::info\r\nPharmacists can often suggest covered alternatives — bring your insurance card every visit.\r\n:::",
        },
        {
          title: "If a Claim Is Denied",
          content:
            "Ask why (formulary, prior auth, quantity limit). Your doctor can submit an appeal or request an exception with medical justification.",
        },
      ],
    },
  },
  {
    id: "health-literacy-better-questions",
    title: "Health Literacy: Asking Better Questions",
    description: "Simple phrases that help you understand diagnoses, tests, and treatment plans.",
    category: "Doctor Visits",
    readingTime: "5 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Why Questions Matter",
          content:
            "Clear communication reduces errors and helps you follow treatment. Clinicians expect questions — short visits make preparation essential.",
        },
        {
          title: "Phrases That Work",
          content:
            '- "Can you explain that in everyday language?"\r\n- "What is the most important thing I should do next?"\r\n- "What would you do if this were your family member?"\r\n- "Can I get written instructions?"\r\n- "What symptoms should prompt me to call you?"',
        },
        {
          title: "Teach-Back Technique",
          content:
            'Repeat what you heard: "So I will take this twice daily with food and call if I get a rash — is that right?" This catches misunderstandings early.\r\n\r\n:::info\r\nBring a friend or use your phone\'s recorder **only if** your clinic allows recording.\r\n:::',
        },
        {
          title: "When You Feel Rushed",
          content:
            'Say: "I have three questions I need answered before we finish." Prioritize safety and medicine instructions first.',
        },
      ],
    },
  },
  {
    id: "reliable-online-health-info",
    title: "When Online Health Information Is Reliable",
    description: "How to spot trustworthy sources and avoid dangerous misinformation.",
    category: "Healthcare Navigation",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Start With Trusted Organizations",
          content:
            "Look for content from government health agencies (.gov), major hospitals, and established nonprofits. Examples: CDC, NIH MedlinePlus, disease-specific foundations with medical advisory boards.",
        },
        {
          title: "Red Flags",
          content:
            "- Cure-all claims with no evidence\r\n- Pressure to buy supplements immediately\r\n- Anonymous authors with no credentials\r\n- Stories that contradict your care team's advice without discussion\r\n- Content designed to spread fear",
        },
        {
          title: "Check Dates and Sources",
          content:
            "Medical guidance changes. Prefer pages updated in the last few years with cited studies or expert review.\r\n\r\n:::warning\r\nSocial media anecdotes are not medical evidence. One person's experience may not apply to you.\r\n:::",
        },
        {
          title: "Bring What You Find to Your Visit",
          content:
            'Say: "I read about X online — is that relevant for my situation?" Your clinician can confirm, correct, or explain why it does not apply.',
        },
      ],
    },
  },
  {
    id: "understanding-your-eob",
    title: "Understanding Your Explanation of Benefits (EOB)",
    description: "How to read an EOB and match it to provider bills.",
    category: "Insurance & Billing",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "What an EOB Is",
          content:
            "An Explanation of Benefits (EOB) is **not a bill**. It is a statement from your insurer showing what was billed, what they paid, and what you may owe. You usually receive it before or with a provider statement.",
        },
        {
          title: "Key Lines on an EOB",
          content:
            "- **Billed amount** — what the provider charged\r\n- **Allowed amount** — negotiated rate your plan accepts\r\n- **Plan paid** — what insurance covered\r\n- **Patient responsibility** — deductible, copay, coinsurance, or non-covered charges",
        },
        {
          title: "Matching EOB to Bills",
          content:
            "Compare date of service, provider name, and procedure codes. If the bill total does not match the EOB patient responsibility, call billing before paying.\r\n\r\n:::info\r\nKeep EOBs for at least one plan year — you may need them for taxes (HSA/FSA) or appeals.\r\n:::",
        },
        {
          title: "Common Confusion",
          content:
            '- **Duplicate EOBs** for one visit — one per service line is normal\r\n- **"You may owe"** — verify against the actual bill\r\n- **Out-of-network** — allowed amount and balance billing rules differ',
        },
        {
          title: "When to Call Your Insurer",
          content:
            "Ask if a claim was denied, applied to the wrong deductible, or coded incorrectly. Your doctor's office can resubmit with corrected codes.",
        },
      ],
    },
  },
  {
    id: "finding-in-network-providers",
    title: "Finding In-Network Providers",
    description: "Use your plan directory and avoid surprise bills.",
    category: "Healthcare Navigation",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Why Network Matters",
          content:
            "In-network providers contract with your insurer for lower rates. Out-of-network care can cost much more or may not be covered except in emergencies.",
        },
        {
          title: "Steps to Find Care",
          content:
            "1. Log into your insurer's website or app\r\n2. Search by specialty, location, and language\r\n3. Confirm the **specific doctor** is in network — not just the clinic name\r\n4. Call the office to verify they still accept your plan",
        },
        {
          title: "Hospital vs Doctor Network",
          content:
            "Hospitals and individual doctors negotiate separately. A surgeon may be out of network even at an in-network hospital — ask before scheduled procedures.\r\n\r\n:::warning\r\nEmergency room care is often covered as in-network by law, but follow-up and ambulance rides may not be — verify after stabilization.\r\n:::",
        },
        {
          title: "Telehealth and Urgent Care",
          content:
            "Check whether virtual visits and retail clinics (minute clinics, urgent care chains) are in network before you go.",
        },
        {
          title: "If You Must Go Out of Network",
          content:
            "Ask about cash prices, payment plans, and whether your doctor can refer you to an in-network alternative.",
        },
      ],
    },
  },
  {
    id: "preparing-for-blood-draw",
    title: "Preparing for a Blood Draw",
    description: "Fasting rules, hydration, and what to expect at the lab.",
    category: "Lab Results",
    readingTime: "5 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Before You Go",
          content:
            "- Confirm **fasting** requirements (often 8–12 hours for glucose and lipids; water is usually OK)\r\n- Take prescribed morning medicines unless told otherwise\r\n- Wear sleeves that roll up easily\r\n- Bring your order form or show the lab your electronic order",
        },
        {
          title: "At the Lab",
          content:
            "The phlebotomist cleans your arm, applies a tourniquet, and inserts a small needle. Most draws take a few minutes. Multiple tubes may be filled from one stick.",
        },
        {
          title: "After the Draw",
          content:
            "Press gauze firmly for several minutes to reduce bruising. Avoid heavy lifting with that arm for the rest of the day.\r\n\r\n:::info\r\nMild bruising is common and not dangerous. Apply a cold pack if sore.\r\n:::",
        },
        {
          title: "Results Timeline",
          content:
            "Many routine tests return in 1–3 business days on your patient portal. Critical values may trigger a phone call sooner.",
        },
        {
          title: "Special Situations",
          content:
            "Tell staff if you faint with needles, take blood thinners, or have a mastectomy — they may use a different arm or position.",
        },
      ],
    },
  },
  {
    id: "second-opinion-basics",
    title: "When and How to Get a Second Opinion",
    description: "A practical guide to consulting another specialist.",
    category: "Healthcare Navigation",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Why Second Opinions Help",
          content:
            "They confirm diagnoses, compare treatment options, or offer peace of mind before major surgery or long-term therapy. Good doctors support them.",
        },
        {
          title: "When to Consider One",
          content:
            "- Serious or unclear diagnosis (cancer, rare disease)\r\n- Recommended surgery with significant risk\r\n- Symptoms not improving on treatment\r\n- You feel rushed or unheard",
        },
        {
          title: "How to Request Records",
          content:
            'Ask your clinic for copies of imaging, pathology, and visit notes — or authorize transfer to the second physician. Many systems share via electronic health records.\r\n\r\n:::info\r\nYou do not need to tell your current doctor a negative reason — "I want to confirm the plan" is enough.\r\n:::',
        },
        {
          title: "Insurance Coverage",
          content:
            "Some plans require or pay for second opinions on certain procedures. Call member services before booking.",
        },
        {
          title: "After the Second Visit",
          content:
            "Compare recommendations in writing. If plans differ, ask both doctors to discuss or schedule a three-way call.",
        },
      ],
    },
  },
  {
    id: "telehealth-visit-tips",
    title: "Telehealth Visit Tips",
    description: "Prepare for a productive video or phone appointment.",
    category: "Doctor Visits",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Before the Visit",
          content:
            "- Test camera, microphone, and app login 15 minutes early\r\n- Sit in a quiet, well-lit space\r\n- Have medication list, thermometer readings, and photos of rashes ready\r\n- Know your pharmacy name and address for e-prescriptions",
        },
        {
          title: "During the Call",
          content:
            "Speak clearly and show affected areas to the camera when asked. Telehealth works well for follow-ups, medication checks, and many mental health visits.",
        },
        {
          title: "Limitations",
          content:
            "Emergencies, hands-on exams, and some diagnostic tests still need in-person care. Ask what cannot be done virtually.\r\n\r\n:::warning\r\nIf symptoms worsen during a video visit, the clinician may direct you to urgent care or ER — have transport plans ready.\r\n:::",
        },
        {
          title: "Privacy",
          content:
            "Use a private room. Headphones reduce echo and protect others from hearing your health information.",
        },
        {
          title: "Afterward",
          content: "Confirm next steps in the portal message center and schedule in-person labs if ordered.",
        },
      ],
    },
  },
  {
    id: "medication-adherence-strategies",
    title: "Medication Adherence Strategies",
    description: "Tools and habits to take medicines as prescribed.",
    category: "Medication Safety",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Why Adherence Matters",
          content:
            "Skipping doses or stopping early can cause relapse, resistance, or hospitalization — especially for blood pressure, diabetes, and infection treatments.",
        },
        {
          title: "Practical Tools",
          content:
            "- **Pill organizer** — weekly boxes with AM/PM slots\r\n- **Phone alarms** — label each with drug name\r\n- **Pharmacy auto-refill** — reduces gaps\r\n- **Blister packs** — some pharmacies pre-sort by dose time",
        },
        {
          title: "Tie to Daily Routines",
          content:
            "Link medicines to brushing teeth, meals, or bedtime so the habit stacks on something you already do.\r\n\r\n:::info\r\nIf cost or side effects block adherence, tell your clinician — alternatives exist.\r\n:::",
        },
        {
          title: "Travel and Sick Days",
          content:
            "Pack extra doses in carry-on luggage. Ask your doctor for sick-day rules for insulin, blood pressure, or diuretics.",
        },
        {
          title: "Tracking",
          content: 'Use a simple log or app for "as needed" medicines so you do not exceed daily limits.',
        },
      ],
    },
  },
  {
    id: "when-to-call-your-doctor",
    title: "When to Call Your Doctor vs Urgent Care vs 911",
    description: "A simple decision guide for non-emergency symptoms.",
    category: "Emergency",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Call 911 or Go to ER",
          content:
            "- Chest pain or pressure\r\n- Trouble breathing\r\n- Stroke signs (FAST: face, arm, speech, time)\r\n- Severe bleeding or unconsciousness\r\n- Suicidal thoughts with a plan",
        },
        {
          title: "Urgent Care (Same Day)",
          content:
            "- Sprains, minor cuts needing stitches\r\n- Fever without severe distress in otherwise healthy adults\r\n- Urinary burning if you cannot reach your doctor\r\n- Mild asthma flare with inhaler not helping after one hour",
        },
        {
          title: "Call Your Doctor's Office",
          content:
            "- Medication side effects\r\n- Worsening chronic condition\r\n- Test result questions\r\n- Referrals and preventive scheduling\r\n\r\n:::info\r\nMany clinics offer nurse triage lines — describe symptoms and they advise timing.\r\n:::",
        },
        {
          title: "When Unsure",
          content: "Err toward safer care. It is OK to go to ER; it is also OK to call 911 for guidance.",
        },
      ],
    },
  },
  {
    id: "patient-portal-basics",
    title: "Patient Portal Basics",
    description: "Access results, messages, and refills online.",
    category: "Healthcare Navigation",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "What Portals Do",
          content:
            "Most clinics offer secure websites or apps to:\r\n\r\n- View lab and imaging results\r\n- Message your care team\r\n- Request prescription refills\r\n- Schedule appointments\r\n- Download visit summaries",
        },
        {
          title: "Getting Started",
          content:
            "Ask front desk for signup instructions. You may need email verification and a one-time activation code from your visit paperwork.",
        },
        {
          title: "Reading Results Early",
          content:
            "Results may appear before your doctor reviews them. Abnormal flags are not always urgent — but note questions for your follow-up.\r\n\r\n:::warning\r\nPortals are not for emergencies. Call 911 or go to ER for immediate danger.\r\n:::",
        },
        {
          title: "Messaging Etiquette",
          content:
            "Include one clear question per message, your pharmacy if requesting refills, and allow 1–3 business days for replies.",
        },
        {
          title: "Privacy and Access",
          content:
            "Use strong passwords. Proxy access for caregivers may require separate authorization forms.",
        },
      ],
    },
  },
  {
    id: "health-literacy-for-caregivers",
    title: "Health Literacy for Caregivers",
    description: "Support a loved one's care while respecting their autonomy.",
    category: "Healthcare Navigation",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Your Role",
          content:
            "Caregivers translate instructions, track appointments, and advocate — but the patient (or legal proxy) makes final decisions unless incapacitated.",
        },
        {
          title: "Prepare for Appointments Together",
          content:
            "- List current medicines and allergies\r\n- Write top three concerns in the patient's words\r\n- Take notes or ask permission to record",
        },
        {
          title: "Proxy Access",
          content:
            "Hospitals require HIPAA authorization for you to receive medical information. Complete forms before emergencies when possible.\r\n\r\n:::info\r\nBring durable power of attorney for healthcare documents to major visits if you are the decision-maker.\r\n:::",
        },
        {
          title: "Avoid Burnout",
          content: "Share duties with family, use respite programs, and keep your own medical appointments.",
        },
        {
          title: "When Values Conflict",
          content:
            "Focus on what matters to the patient — mobility, pain control, independence — not only what seems medically aggressive.",
        },
      ],
    },
  },
  {
    id: "understanding-prior-authorization",
    title: "Understanding Prior Authorization",
    description: "Why insurers require approval and how to speed the process.",
    category: "Insurance & Billing",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "What Prior Auth Is",
          content:
            "Your insurer may require approval before paying for certain drugs, imaging, or procedures. The provider submits clinical reasons; the plan decides if criteria are met.",
        },
        {
          title: "Common Triggers",
          content:
            "- Expensive brand drugs with generic alternatives\r\n- Advanced imaging (MRI, PET)\r\n- Elective surgeries\r\n- Durable medical equipment",
        },
        {
          title: "Timeline",
          content:
            "Decisions can take days to two weeks. Start early — ask your doctor's office to submit the same day they order the service.\r\n\r\n:::warning\r\nStarting treatment before approval may leave you with full cost if denied.\r\n:::",
        },
        {
          title: "If Denied",
          content:
            "You can appeal with additional documentation. Ask for the denial letter in writing and the reason code.",
        },
        {
          title: "Your Role",
          content:
            "Sign release forms promptly, provide insurance cards at every visit, and follow up if you have not heard back within the stated window.",
        },
      ],
    },
  },
] as const;
