// Auto-generated by scripts/bundle-articles.ts — do not edit by hand.

import type { Article } from "@/types/article";

export const articles: Article[] = [
  {
    id: "choosing-primary-care-doctor",
    title: "Cómo elegir un médico de atención primaria",
    description:
      "Pasos prácticos para encontrar un profesional que se ajuste a sus necesidades, seguro y estilo de comunicación.",
    category: "Healthcare Navigation",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Por qué importa la atención primaria",
          content:
            "Un proveedor de atención primaria (PCP) es su médico principal para chequeos, condiciones crónicas, referencias y problemas cotidianos. Un buen match facilita la atención preventiva y detectar problemas temprano.",
        },
        {
          title: "Empiece con su seguro",
          content:
            "Use el directorio de su plan para médicos en red. La atención fuera de red suele costar mucho más. Confirme que la oficina acepta pacientes nuevos.",
        },
        {
          title: "Considere logística",
          content:
            "- **Ubicación** — viaje razonable para visitas y laboratorios\r\n- **Horarios** — tardes o fines de semana si trabaja horario estándar\r\n- **Afiliación hospitalaria** — importa si puede necesitar hospitalización\r\n- **Telemedicina** — útil para seguimientos y problemas menores",
        },
        {
          title: "Evalúe en la primera visita",
          content:
            "- ¿El médico escuchó sin apresurarse?\r\n- ¿Las explicaciones fueron claras?\r\n- ¿Se sintió respetado?\r\n- ¿El personal ayudó con citas y facturación?\r\n\r\n:::info\r\nEstá bien cambiar de PCP si la relación no funciona. Su comodidad afecta qué tan honesto es al compartir síntomas.\r\n:::",
        },
        {
          title: "Preguntas útiles",
          content:
            "- ¿Quién cubre cuando mi médico no está?\r\n- ¿Cómo contacto a alguien fuera de horario?\r\n- ¿Cómo comunican resultados?\r\n- ¿Puedo usar el portal para resurtidos y mensajes?",
        },
      ],
    },
  },
  {
    id: "annual-physical-what-to-expect",
    title: "Qué esperar en un examen físico anual",
    description: "Qué ocurre en una visita de bienestar de rutina y cómo prepararse.",
    category: "Preventive Care",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Propósito de la visita de bienestar",
          content:
            "Un examen anual se enfoca en prevención. El profesional revisa historial, signos vitales, pruebas de detección y vacunas.",
        },
        {
          title: "Componentes típicos",
          content:
            "- Talla, peso, presión, examen cardíaco y pulmonar\r\n- Revisión de medicamentos y alergias\r\n- Órdenes de detección según edad\r\n- Actualización de vacunas\r\n- Consejería de estilo de vida",
        },
        {
          title: "Cómo prepararse",
          content:
            "Lleve lista de medicamentos, resultados recientes y preguntas. Mencione síntomas nuevos aunque parezcan menores.\r\n\r\n:::warning\r\nUna visita de bienestar no es lo mismo que atención urgente por enfermedad aguda. Reserve por separado si está enfermo.\r\n:::",
        },
        {
          title: "Después de la visita",
          content:
            "Puede recibir órdenes de laboratorio o referencias. Pregunte cuándo estarán los resultados y cómo le avisarán.\r\n\r\n:::success\r\nUse beneficios preventivos de su seguro — muchas pruebas no tienen copago en red.\r\n:::",
        },
      ],
    },
  },
  {
    id: "pharmacy-benefits-basics",
    title: "Cómo entender sus beneficios de farmacia",
    description: "Formularios, niveles, autorización previa y cómo reducir costos de recetas.",
    category: "Insurance & Billing",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Términos clave",
          content:
            "- **Formulario** — lista de medicamentos que cubre su plan\r\n- **Nivel (tier)** — nivel de costo (genéricos nivel 1 suelen ser más baratos)\r\n- **Autorización previa** — aprobación del asegurador antes de pagar ciertos medicamentos\r\n- **Terapia escalonada** — probar un medicamento preferido antes de uno más caro",
        },
        {
          title: "Leer su tarjeta de medicamentos",
          content:
            "Su tarjeta puede tener línea de ayuda de farmacia y números BIN/PCN/grupo que usa la farmacia.",
        },
        {
          title: "Ahorrar dinero",
          content:
            "- Pida genéricos cuando sea apropiado\r\n- Use farmacias en red\r\n- Compare precios de pedido por correo a 90 días\r\n- Pregunte por ayuda con copago para marcas\r\n\r\n:::info\r\nLos farmacéuticos pueden sugerir alternativas cubiertas — lleve su tarjeta de seguro siempre.\r\n:::",
        },
        {
          title: "Si rechazan un reclamo",
          content:
            "Pregunte por qué (formulario, autorización, límite de cantidad). Su médico puede apelar o pedir excepción.",
        },
      ],
    },
  },
  {
    id: "health-literacy-better-questions",
    title: "Alfabetización en salud: mejores preguntas",
    description: "Frases simples para entender diagnósticos, pruebas y planes de tratamiento.",
    category: "Doctor Visits",
    readingTime: "5 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Por qué importan las preguntas",
          content:
            "La comunicación clara reduce errores y ayuda a seguir el tratamiento. Los profesionales esperan preguntas — las visitas cortas hacen esencial la preparación.",
        },
        {
          title: "Frases que funcionan",
          content:
            '- "¿Puede explicarlo en lenguaje cotidiano?"\r\n- "¿Qué es lo más importante que debo hacer ahora?"\r\n- "¿Qué haría si fuera su familiar?"\r\n- "¿Puedo tener instrucciones por escrito?"\r\n- "¿Qué síntomas deberían hacer que le llame?"',
        },
        {
          title: "Técnica de enseñanza de vuelta",
          content:
            'Repita lo que oyó: "Entonces tomaré esto dos veces al día con comida y llamaré si tengo erupción — ¿correcto?"\r\n\r\n:::info\r\nTraiga a un amigo o use grabadora **solo si** la clínica lo permite.\r\n:::',
        },
        {
          title: "Si se siente apurado",
          content:
            'Diga: "Tengo tres preguntas que necesito resolver antes de terminar." Priorice seguridad e instrucciones de medicamentos.',
        },
      ],
    },
  },
  {
    id: "reliable-online-health-info",
    title: "Cuándo la información de salud en línea es confiable",
    description: "Cómo identificar fuentes confiables y evitar desinformación peligrosa.",
    category: "Healthcare Navigation",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Empiece con organizaciones confiables",
          content:
            "Busque contenido de agencias gubernamentales (.gov), hospitales importantes y fundaciones establecidas. Ejemplos: CDC, NIH MedlinePlus, fundaciones con consejos médicos.",
        },
        {
          title: "Señales de alerta",
          content:
            "- Promesas de cura total sin evidencia\r\n- Presión para comprar suplementos de inmediato\r\n- Autores anónimos sin credenciales\r\n- Historias que contradicen a su equipo sin discusión\r\n- Contenido diseñado para generar miedo",
        },
        {
          title: "Revise fechas y fuentes",
          content:
            "La orientación médica cambia. Prefiera páginas actualizadas en los últimos años con estudios citados.\r\n\r\n:::warning\r\nLas anécdotas en redes no son evidencia médica. La experiencia de una persona puede no aplicarle.\r\n:::",
        },
        {
          title: "Lleve lo que encuentre a su visita",
          content:
            'Diga: "Leí sobre X en línea — ¿es relevante para mi situación?" Su profesional puede confirmar, corregir o explicar por qué no aplica.',
        },
      ],
    },
  },
  {
    id: "understanding-your-eob",
    title: "Entender su Explicación de Beneficios (EOB)",
    description: "Cómo leer un EOB y compararlo con facturas del proveedor.",
    category: "Insurance & Billing",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Qué es un EOB",
          content:
            "Una Explicación de Beneficios (EOB) **no es una factura**. Es un estado de su aseguradora que muestra lo facturado, lo pagado y lo que puede deber. Suele llegar antes o con la factura del proveedor.",
        },
        {
          title: "Líneas clave",
          content:
            "- **Monto facturado** — lo que cobró el proveedor\r\n- **Monto permitido** — tarifa negociada que acepta su plan\r\n- **Pagó el plan** — lo que cubrió el seguro\r\n- **Responsabilidad del paciente** — deducible, copago, coseguro o cargos no cubiertos",
        },
        {
          title: "Comparar EOB con facturas",
          content:
            "Compare fecha de servicio, proveedor y códigos. Si el total no coincide con la responsabilidad del paciente en el EOB, llame a facturación antes de pagar.\r\n\r\n:::info\r\nGuarde EOBs al menos un año — puede necesitarlos para impuestos (HSA/FSA) o apelaciones.\r\n:::",
        },
        {
          title: "Confusiones comunes",
          content:
            '- **EOB duplicados** por una visita — una por línea de servicio es normal\r\n- **"Puede deber"** — verifique contra la factura real\r\n- **Fuera de red** — reglas de monto permitido y facturación balanceada difieren',
        },
        {
          title: "Cuándo llamar al asegurador",
          content:
            "Pregunte si un reclamo fue rechazado, aplicado al deducible incorrecto o codificado mal. La oficina del médico puede reenviar con códigos corregidos.",
        },
      ],
    },
  },
  {
    id: "finding-in-network-providers",
    title: "Encontrar proveedores en red",
    description: "Use el directorio de su plan y evite facturas sorpresa.",
    category: "Healthcare Navigation",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Por qué importa la red",
          content:
            "Los proveedores en red tienen contrato con su aseguradora a tarifas más bajas. Atención fuera de red puede costar mucho más o no cubrirse excepto en emergencias.",
        },
        {
          title: "Pasos para encontrar atención",
          content:
            "1. Entre al sitio o app de su aseguradora\r\n2. Busque por especialidad, ubicación e idioma\r\n3. Confirme que el **médico específico** está en red — no solo la clínica\r\n4. Llame para verificar que aún aceptan su plan",
        },
        {
          title: "Red del hospital vs del médico",
          content:
            "Hospitales y médicos negocian por separado. Un cirujano puede estar fuera de red aunque el hospital esté en red — pregunte antes de procedimientos programados.\r\n\r\n:::warning\r\nEmergencias suelen cubrirse como en red por ley, pero seguimiento y ambulancia pueden no — verifique tras estabilización.\r\n:::",
        },
        {
          title: "Telesalud y urgencias",
          content: "Verifique si visitas virtuales y clínicas minoristas están en red antes de ir.",
        },
        {
          title: "Si debe ir fuera de red",
          content:
            "Pregunte precios en efectivo, planes de pago y si su médico puede referirlo a alternativa en red.",
        },
      ],
    },
  },
  {
    id: "preparing-for-blood-draw",
    title: "Prepararse para una extracción de sangre",
    description: "Reglas de ayuno, hidratación y qué esperar en el laboratorio.",
    category: "Lab Results",
    readingTime: "5 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Antes de ir",
          content:
            "- Confirme requisitos de **ayuno** (a menudo 8–12 horas para glucosa y lípidos; agua suele estar bien)\r\n- Tome medicamentos matutinos recetados salvo indicación contraria\r\n- Use mangas que suban fácilmente\r\n- Lleve la orden o muestre la orden electrónica",
        },
        {
          title: "En el laboratorio",
          content:
            "El flebotomista limpia el brazo, aplica torniquete e inserta aguja pequeña. La mayoría tarda minutos. Pueden llenarse varios tubos con una sola punción.",
        },
        {
          title: "Después",
          content:
            "Presione gasa firmemente varios minutos para reducir moretones. Evite levantar peso con ese brazo el resto del día.\r\n\r\n:::info\r\nMoretones leves son comunes y no peligrosos. Aplique hielo si hay dolor.\r\n:::",
        },
        {
          title: "Plazo de resultados",
          content:
            "Muchas pruebas de rutina regresan en 1–3 días hábiles en el portal. Valores críticos pueden generar llamada antes.",
        },
        {
          title: "Situaciones especiales",
          content:
            "Informe si se desmaya con agujas, toma anticoagulantes o tuvo mastectomía — pueden usar otro brazo o posición.",
        },
      ],
    },
  },
  {
    id: "second-opinion-basics",
    title: "Cuándo y cómo pedir segunda opinión",
    description: "Guía práctica para consultar a otro especialista.",
    category: "Healthcare Navigation",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Por qué ayudan las segundas opiniones",
          content:
            "Confirman diagnósticos, comparan tratamientos u ofrecen tranquilidad antes de cirugía mayor o terapia prolongada. Buenos médicos las apoyan.",
        },
        {
          title: "Cuándo considerarla",
          content:
            "- Diagnóstico grave o poco claro (cáncer, enfermedad rara)\r\n- Cirugía recomendada con riesgo significativo\r\n- Síntomas que no mejoran con tratamiento\r\n- Se siente apurado o no escuchado",
        },
        {
          title: "Cómo solicitar registros",
          content:
            'Pida copias de imágenes, patología y notas — o autorice transferencia al segundo médico. Muchos sistemas comparten electrónicamente.\r\n\r\n:::info\r\nNo necesita dar razón negativa a su médico actual — "quiero confirmar el plan" basta.\r\n:::',
        },
        {
          title: "Cobertura del seguro",
          content:
            "Algunos planes exigen o pagan segundas opiniones en ciertos procedimientos. Llame a servicios al miembro antes de reservar.",
        },
        {
          title: "Tras la segunda visita",
          content:
            "Compare recomendaciones por escrito. Si difieren, pida a ambos médicos discutir o programar llamada conjunta.",
        },
      ],
    },
  },
  {
    id: "telehealth-visit-tips",
    title: "Consejos para visitas de telesalud",
    description: "Prepárese para una cita por video o teléfono productiva.",
    category: "Doctor Visits",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Antes de la visita",
          content:
            "- Pruebe cámara, micrófono e inicio de sesión 15 minutos antes\r\n- Siéntese en lugar tranquilo y bien iluminado\r\n- Tenga lista de medicamentos, temperaturas y fotos de erupciones listas\r\n- Sepa nombre y dirección de farmacia para recetas electrónicas",
        },
        {
          title: "Durante la llamada",
          content:
            "Hable claro y muestre áreas afectadas a la cámara cuando pidan. Telesalud funciona bien para seguimientos, revisiones de medicamentos y muchas visitas de salud mental.",
        },
        {
          title: "Limitaciones",
          content:
            "Emergencias, exámenes físicos y algunas pruebas aún requieren presencial. Pregunte qué no se puede hacer virtualmente.\r\n\r\n:::warning\r\nSi empeoran síntomas durante video visita, pueden dirigirlo a urgencias — tenga plan de transporte.\r\n:::",
        },
        {
          title: "Privacidad",
          content:
            "Use habitación privada. Audífonos reducen eco y protegen a otros de escuchar su información.",
        },
        {
          title: "Después",
          content:
            "Confirme siguientes pasos en el portal y programe laboratorios presenciales si los ordenaron.",
        },
      ],
    },
  },
  {
    id: "medication-adherence-strategies",
    title: "Estrategias para adherencia a medicamentos",
    description: "Herramientas y hábitos para tomar medicamentos según receta.",
    category: "Medication Safety",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Por qué importa la adherencia",
          content:
            "Omitir dosis o suspender antes puede causar recaída, resistencia u hospitalización — especialmente en presión, diabetes e infecciones.",
        },
        {
          title: "Herramientas prácticas",
          content:
            "- **Organizador de pastillas** — cajas semanales AM/PM\r\n- **Alarmas del teléfono** — etiquete con nombre del medicamento\r\n- **Resurtido automático** — reduce huecos\r\n- **Blísteres** — algunas farmacias preordenan por horario",
        },
        {
          title: "Enlace a rutinas diarias",
          content:
            "Asocie medicamentos con cepillado, comidas o dormir para anclar el hábito.\r\n\r\n:::info\r\nSi costo o efectos secundarios bloquean adherencia, dígalo al clínico — hay alternativas.\r\n:::",
        },
        {
          title: "Viajes y días de enfermedad",
          content:
            "Lleve dosis extra en equipaje de mano. Pregunte reglas para insulina, presión o diuréticos en días de enfermedad.",
        },
        {
          title: "Seguimiento",
          content:
            'Use registro simple o app para medicamentos "según necesidad" y no exceder límites diarios.',
        },
      ],
    },
  },
  {
    id: "when-to-call-your-doctor",
    title: "Cuándo llamar al médico vs urgencias vs 911",
    description: "Guía simple para síntomas no emergentes.",
    category: "Emergency",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Llame 911 o vaya a emergencias",
          content:
            "- Dolor u opresión de pecho\r\n- Dificultad para respirar\r\n- Signos de ACV (FAST: cara, brazo, habla, tiempo)\r\n- Sangrado severo o inconsciencia\r\n- Pensamientos suicidas con plan",
        },
        {
          title: "Atención urgente (mismo día)",
          content:
            "- Esguinces, cortes menores que necesitan puntos\r\n- Fiebre sin angustia severa en adultos sanos\r\n- Ardor al orinar si no puede contactar al médico\r\n- Brote leve de asma si inhalador no ayuda tras una hora",
        },
        {
          title: "Llame al consultorio",
          content:
            "- Efectos secundarios de medicamentos\r\n- Empeoramiento de condición crónica\r\n- Preguntas sobre resultados\r\n- Referencias y citas preventivas\r\n\r\n:::info\r\nMuchas clínicas tienen línea de enfermería — describa síntomas y orientan timing.\r\n:::",
        },
        {
          title: "Si no está seguro",
          content:
            "Prefiera atención más segura. Está bien ir a emergencias; también llamar al 911 para orientación.",
        },
      ],
    },
  },
  {
    id: "patient-portal-basics",
    title: "Conceptos básicos del portal del paciente",
    description: "Acceda a resultados, mensajes y resurtidos en línea.",
    category: "Healthcare Navigation",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Qué hacen los portales",
          content:
            "La mayoría de clínicas ofrecen sitios o apps seguros para:\r\n\r\n- Ver resultados de laboratorio e imágenes\r\n- Enviar mensajes al equipo\r\n- Solicitar resurtidos\r\n- Programar citas\r\n- Descargar resúmenes de visita",
        },
        {
          title: "Primeros pasos",
          content:
            "Pida instrucciones en recepción. Puede necesitar verificación de correo y código de activación del paperwork de la visita.",
        },
        {
          title: "Leer resultados temprano",
          content:
            "Los resultados pueden aparecer antes de que el médico los revise. Banderas anormales no siempre son urgentes — anote preguntas para seguimiento.\r\n\r\n:::warning\r\nLos portales no son para emergencias. Llame 911 o vaya a emergencias ante peligro inmediato.\r\n:::",
        },
        {
          title: "Etiqueta de mensajes",
          content:
            "Incluya una pregunta clara, farmacia si pide resurtidos y espere 1–3 días hábiles de respuesta.",
        },
        {
          title: "Privacidad y acceso",
          content:
            "Use contraseñas fuertes. Acceso de cuidadores puede requerir formularios de autorización separados.",
        },
      ],
    },
  },
  {
    id: "health-literacy-for-caregivers",
    title: "Alfabetización en salud para cuidadores",
    description: "Apoye el cuidado de un ser querido respetando su autonomía.",
    category: "Healthcare Navigation",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Su rol",
          content:
            "Los cuidadores traducen instrucciones, rastrean citas y abogan — pero el paciente (o apoderado legal) decide salvo incapacidad.",
        },
        {
          title: "Preparen citas juntos",
          content:
            "- Liste medicamentos y alergias actuales\r\n- Escriban tres preocupaciones principales con palabras del paciente\r\n- Tomen notas o pidan permiso para grabar",
        },
        {
          title: "Acceso proxy",
          content:
            "Hospitales requieren autorización HIPAA para darle información médica. Complete formularios antes de emergencias cuando sea posible.\r\n\r\n:::info\r\nLleve documentos de poder notarial para salud en visitas importantes si es quien decide.\r\n:::",
        },
        {
          title: "Evite agotamiento",
          content: "Comparta tareas, use programas de respiro y mantenga sus propias citas médicas.",
        },
        {
          title: "Cuando hay conflicto de valores",
          content:
            "Enfóquese en lo que importa al paciente — movilidad, control del dolor, independencia — no solo lo médicamente agresivo.",
        },
      ],
    },
  },
  {
    id: "understanding-prior-authorization",
    title: "Entender la autorización previa",
    description: "Por qué los aseguradores exigen aprobación y cómo acelerar el proceso.",
    category: "Insurance & Billing",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Qué es autorización previa",
          content:
            "Su asegurador puede exigir aprobación antes de pagar ciertos medicamentos, imágenes o procedimientos. El proveedor envía razones clínicas; el plan decide si cumple criterios.",
        },
        {
          title: "Disparadores comunes",
          content:
            "- Medicamentos de marca costosos con genéricos\r\n- Imágenes avanzadas (RM, PET)\r\n- Cirugías electivas\r\n- Equipo médico durable",
        },
        {
          title: "Plazos",
          content:
            "Decisiones pueden tardar días a dos semanas. Empiece pronto — pida que la oficina envíe el mismo día que ordenan el servicio.\r\n\r\n:::warning\r\nIniciar tratamiento antes de aprobación puede dejarlo con costo total si rechazan.\r\n:::",
        },
        {
          title: "Si rechazan",
          content:
            "Puede apelar con documentación adicional. Pida carta de rechazo por escrito y código de razón.",
        },
        {
          title: "Su rol",
          content:
            "Firme liberaciones pronto, entregue tarjeta de seguro en cada visita y haga seguimiento si no hay respuesta en el plazo indicado.",
        },
      ],
    },
  },
] as const;
