// Auto-generated by scripts/bundle-articles.ts — do not edit by hand.

import type { Article } from "@/types/article";

export const articles: Article[] = [
  {
    id: "choosing-primary-care-doctor",
    title: "Cómo elegir un médico de atención primaria",
    description:
      "Pasos prácticos para encontrar un profesional que se ajuste a sus necesidades, seguro y estilo de comunicación.",
    category: "Healthcare Navigation",
    readingTime: "7 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Por qué importa la atención primaria",
          content:
            "Un proveedor de atención primaria (PCP) es su médico principal para chequeos, condiciones crónicas, referencias y problemas cotidianos. Un buen match facilita la atención preventiva y detectar problemas temprano.",
        },
        {
          title: "Empiece con su seguro",
          content:
            "Use el directorio de su plan para médicos en red. La atención fuera de red suele costar mucho más. Confirme que la oficina acepta pacientes nuevos.",
        },
        {
          title: "Considere logística",
          content:
            "- **Ubicación** — viaje razonable para visitas y laboratorios\n- **Horarios** — tardes o fines de semana si trabaja horario estándar\n- **Afiliación hospitalaria** — importa si puede necesitar hospitalización\n- **Telemedicina** — útil para seguimientos y problemas menores",
        },
        {
          title: "Evalúe en la primera visita",
          content:
            "- ¿El médico escuchó sin apresurarse?\n- ¿Las explicaciones fueron claras?\n- ¿Se sintió respetado?\n- ¿El personal ayudó con citas y facturación?",
          callouts: [
            {
              type: "info",
              content:
                "Está bien cambiar de PCP si la relación no funciona. Su comodidad afecta qué tan honesto es al compartir síntomas.",
            },
          ],
        },
        {
          title: "Preguntas útiles",
          content:
            "- ¿Quién cubre cuando mi médico no está?\n- ¿Cómo contacto a alguien fuera de horario?\n- ¿Cómo comunican resultados?\n- ¿Puedo usar el portal para resurtidos y mensajes?",
        },
      ],
    },
  },
  {
    id: "annual-physical-what-to-expect",
    title: "Qué esperar en un examen físico anual",
    description: "Qué ocurre en una visita de bienestar de rutina y cómo prepararse.",
    category: "Preventive Care",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Propósito de la visita de bienestar",
          content:
            "Un examen anual se enfoca en prevención. El profesional revisa historial, signos vitales, pruebas de detección y vacunas.",
        },
        {
          title: "Componentes típicos",
          content:
            "- Talla, peso, presión, examen cardíaco y pulmonar\n- Revisión de medicamentos y alergias\n- Órdenes de detección según edad\n- Actualización de vacunas\n- Consejería de estilo de vida",
        },
        {
          title: "Cómo prepararse",
          content:
            "Lleve lista de medicamentos, resultados recientes y preguntas. Mencione síntomas nuevos aunque parezcan menores.",
          callouts: [
            {
              type: "warning",
              content:
                "Una visita de bienestar no es lo mismo que atención urgente por enfermedad aguda. Reserve por separado si está enfermo.",
            },
          ],
        },
        {
          title: "Después de la visita",
          content:
            "Puede recibir órdenes de laboratorio o referencias. Pregunte cuándo estarán los resultados y cómo le avisarán.",
          callouts: [
            {
              type: "success",
              content: "Use beneficios preventivos de su seguro — muchas pruebas no tienen copago en red.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "pharmacy-benefits-basics",
    title: "Cómo entender sus beneficios de farmacia",
    description: "Formularios, niveles, autorización previa y cómo reducir costos de recetas.",
    category: "Insurance & Billing",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Términos clave",
          content:
            "- **Formulario** — lista de medicamentos que cubre su plan\n- **Nivel (tier)** — nivel de costo (genéricos nivel 1 suelen ser más baratos)\n- **Autorización previa** — aprobación del asegurador antes de pagar ciertos medicamentos\n- **Terapia escalonada** — probar un medicamento preferido antes de uno más caro",
        },
        {
          title: "Leer su tarjeta de medicamentos",
          content:
            "Su tarjeta puede tener línea de ayuda de farmacia y números BIN/PCN/grupo que usa la farmacia.",
        },
        {
          title: "Ahorrar dinero",
          content:
            "- Pida genéricos cuando sea apropiado\n- Use farmacias en red\n- Compare precios de pedido por correo a 90 días\n- Pregunte por ayuda con copago para marcas",
          callouts: [
            {
              type: "info",
              content:
                "Los farmacéuticos pueden sugerir alternativas cubiertas — lleve su tarjeta de seguro siempre.",
            },
          ],
        },
        {
          title: "Si rechazan un reclamo",
          content:
            "Pregunte por qué (formulario, autorización, límite de cantidad). Su médico puede apelar o pedir excepción.",
        },
      ],
    },
  },
  {
    id: "health-literacy-better-questions",
    title: "Alfabetización en salud: mejores preguntas",
    description: "Frases simples para entender diagnósticos, pruebas y planes de tratamiento.",
    category: "Doctor Visits",
    readingTime: "5 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Por qué importan las preguntas",
          content:
            "La comunicación clara reduce errores y ayuda a seguir el tratamiento. Los profesionales esperan preguntas — las visitas cortas hacen esencial la preparación.",
        },
        {
          title: "Frases que funcionan",
          content:
            '- "¿Puede explicarlo en lenguaje cotidiano?"\n- "¿Qué es lo más importante que debo hacer ahora?"\n- "¿Qué haría si fuera su familiar?"\n- "¿Puedo tener instrucciones por escrito?"\n- "¿Qué síntomas deberían hacer que le llame?"',
        },
        {
          title: "Técnica de enseñanza de vuelta",
          content:
            'Repita lo que oyó: "Entonces tomaré esto dos veces al día con comida y llamaré si tengo erupción — ¿correcto?"',
          callouts: [
            {
              type: "info",
              content: "Traiga a un amigo o use grabadora **solo si** la clínica lo permite.",
            },
          ],
        },
        {
          title: "Si se siente apurado",
          content:
            'Diga: "Tengo tres preguntas que necesito resolver antes de terminar." Priorice seguridad e instrucciones de medicamentos.',
        },
      ],
    },
  },
  {
    id: "reliable-online-health-info",
    title: "Cuándo la información de salud en línea es confiable",
    description: "Cómo identificar fuentes confiables y evitar desinformación peligrosa.",
    category: "Healthcare Navigation",
    readingTime: "6 min",
    lastReviewed: "2026-06-11",
    reviewedBy: "Health Education Review Team",
    sources: ["CDC", "NIH MedlinePlus"],
    content: {
      sections: [
        {
          title: "Empiece con organizaciones confiables",
          content:
            "Busque contenido de agencias gubernamentales (.gov), hospitales importantes y fundaciones establecidas. Ejemplos: CDC, NIH MedlinePlus, fundaciones con consejos médicos.",
        },
        {
          title: "Señales de alerta",
          content:
            "- Promesas de cura total sin evidencia\n- Presión para comprar suplementos de inmediato\n- Autores anónimos sin credenciales\n- Historias que contradicen a su equipo sin discusión\n- Contenido diseñado para generar miedo",
        },
        {
          title: "Revise fechas y fuentes",
          content:
            "La orientación médica cambia. Prefiera páginas actualizadas en los últimos años con estudios citados.",
          callouts: [
            {
              type: "warning",
              content:
                "Las anécdotas en redes no son evidencia médica. La experiencia de una persona puede no aplicarle.",
            },
          ],
        },
        {
          title: "Lleve lo que encuentre a su visita",
          content:
            'Diga: "Leí sobre X en línea — ¿es relevante para mi situación?" Su profesional puede confirmar, corregir o explicar por qué no aplica.',
        },
      ],
    },
  },
] as const;
