// Auto-generated by scripts/bundle-glossary.ts — do not edit by hand.
// Edit content/glossary/{en,es}/*.mdx then run: npm run content:bundle-glossary

import type { GlossaryTerm } from "@/types/glossary";

import { terms as en } from "./glossaryBundles.en";
import { terms as es } from "./glossaryBundles.es";

export const glossaryBundles: Record<"en" | "es", GlossaryTerm[]> = { en, es } as const;
