// Auto-generated by scripts/bundle-glossary.ts — do not edit by hand.
// Edit content/glossary/{en,es}/*.mdx then run: npm run content:bundle-glossary

import type { GlossaryTerm } from "@/types/glossary";

export const terms: GlossaryTerm[] = [
  {
    id: "blood-pressure",
    term: "Presión arterial",
    category: "General",
    definition:
      "La fuerza con la que la sangre empuja las paredes de tus arterias. Se mide con dos números: sistólica sobre diastólica.",
    relatedTerms: ["hypertension", "hypotension"],
  },
  {
    id: "hypertension",
    term: "Hipertensión",
    category: "Condiciones",
    definition:
      "Presión arterial alta. Puede dañar los vasos sanguíneos y aumentar el riesgo de enfermedad cardíaca y derrame cerebral.",
    relatedTerms: ["blood-pressure"],
  },
  {
    id: "hypotension",
    term: "Hipotensión",
    category: "Condiciones",
    definition:
      "Presión arterial baja. Puede causar mareo, desmayo o cansancio y debe evaluarse si produce síntomas.",
    relatedTerms: ["blood-pressure"],
  },
  {
    id: "cholesterol",
    term: "Colesterol",
    category: "General",
    definition:
      "Sustancia cerosa similar a la grasa que existe en las células del cuerpo. Demasiado colesterol puede acumularse en las arterias.",
    relatedTerms: ["ldl", "hdl", "triglycerides"],
  },
  {
    id: "ldl",
    term: "Colesterol LDL",
    category: "Resultados de laboratorio",
    definition:
      "Lipoproteína de baja densidad, conocida como colesterol malo. Puede acumularse en las arterias.",
    relatedTerms: ["cholesterol", "hdl"],
  },
  {
    id: "hdl",
    term: "Colesterol HDL",
    category: "Resultados de laboratorio",
    definition:
      "Lipoproteína de alta densidad, conocida como colesterol bueno. Ayuda a eliminar LDL de las arterias.",
    relatedTerms: ["cholesterol", "ldl"],
  },
  {
    id: "triglycerides",
    term: "Triglicéridos",
    category: "Resultados de laboratorio",
    definition:
      "Tipo de grasa en la sangre que el cuerpo usa para obtener energía. Niveles altos aumentan el riesgo cardiovascular.",
    relatedTerms: ["cholesterol"],
  },
  {
    id: "diabetes",
    term: "Diabetes",
    category: "Condiciones",
    definition:
      "Enfermedad crónica que afecta cómo el cuerpo convierte los alimentos en energía. Puede causar niveles altos de azúcar en sangre.",
    relatedTerms: ["blood-sugar", "insulin", "glucose"],
  },
  {
    id: "blood-sugar",
    term: "Azúcar en sangre",
    category: "General",
    definition:
      "También llamada glucosa en sangre. Es la principal fuente de energía del cuerpo y está controlada por la insulina.",
    relatedTerms: ["diabetes", "glucose", "insulin"],
  },
  {
    id: "glucose",
    term: "Glucosa",
    category: "General",
    definition: "Azúcar simple que sirve como fuente principal de energía para el cuerpo.",
    relatedTerms: ["blood-sugar", "diabetes"],
  },
  {
    id: "insulin",
    term: "Insulina",
    category: "General",
    definition:
      "Hormona producida por el páncreas que ayuda a que la glucosa entre a las células para usarse como energía.",
    relatedTerms: ["diabetes", "blood-sugar"],
  },
  {
    id: "chronic",
    term: "Crónico",
    category: "General",
    definition: "Condición de salud que dura mucho tiempo y a menudo requiere manejo continuo.",
  },
  {
    id: "acute",
    term: "Agudo",
    category: "General",
    definition: "Condición de salud que aparece de repente y suele durar poco tiempo.",
  },
  {
    id: "symptom",
    term: "Síntoma",
    category: "General",
    definition:
      "Problema físico o mental que siente una persona y que puede indicar una enfermedad o condición.",
    relatedTerms: ["sign"],
  },
  {
    id: "sign",
    term: "Signo",
    category: "General",
    definition:
      "Algo que un profesional de salud puede observar o medir durante un examen, como fiebre o presión alta.",
    relatedTerms: ["symptom"],
  },
  {
    id: "diagnosis",
    term: "Diagnóstico",
    category: "General",
    definition:
      "Proceso de identificar una enfermedad o condición a partir de síntomas, historia clínica y resultados de pruebas.",
  },
  {
    id: "prognosis",
    term: "Pronóstico",
    category: "General",
    definition: "La evolución o resultado probable de una enfermedad o condición con el tiempo.",
  },
  {
    id: "side-effect",
    term: "Efecto secundario",
    category: "Medicamentos",
    definition: "Efecto no deseado que puede aparecer al tomar un medicamento.",
  },
  {
    id: "dosage",
    term: "Dosis",
    category: "Medicamentos",
    definition: "Cantidad de medicamento que debes tomar y con qué frecuencia.",
  },
  {
    id: "generic-drug",
    term: "Medicamento genérico",
    category: "Medicamentos",
    definition: "Medicamento con los mismos ingredientes activos que uno de marca, usualmente a menor costo.",
  },
  {
    id: "prescription",
    term: "Receta médica",
    category: "Medicamentos",
    definition: "Orden escrita de un médico para recibir un medicamento o tratamiento.",
  },
  {
    id: "over-the-counter",
    term: "De venta libre (OTC)",
    category: "Medicamentos",
    definition:
      "Medicamentos que puedes comprar sin receta, aunque aún pueden tener riesgos e interacciones.",
  },
  {
    id: "biopsy",
    term: "Biopsia",
    category: "Procedimientos",
    definition: "Procedimiento en el que se extrae una pequeña muestra de tejido para examinarla.",
  },
  {
    id: "ct-scan",
    term: "Tomografía computarizada",
    category: "Procedimientos",
    definition:
      "Prueba de imagen que usa rayos X y una computadora para crear imágenes detalladas del cuerpo.",
  },
  {
    id: "mri",
    term: "Resonancia magnética",
    category: "Procedimientos",
    definition: "Prueba que usa imanes y ondas de radio para crear imágenes detalladas del cuerpo.",
  },
  {
    id: "ultrasound",
    term: "Ultrasonido",
    category: "Procedimientos",
    definition: "Prueba que usa ondas sonoras para crear imágenes del interior del cuerpo.",
  },
  {
    id: "inflammation",
    term: "Inflamación",
    category: "General",
    definition:
      "Respuesta del cuerpo a una lesión o infección que puede causar enrojecimiento, hinchazón, calor o dolor.",
  },
  {
    id: "immune-system",
    term: "Sistema inmunitario",
    category: "General",
    definition: "Sistema de defensa del cuerpo contra infecciones y enfermedades.",
  },
  {
    id: "metabolism",
    term: "Metabolismo",
    category: "General",
    definition: "Procesos químicos del cuerpo que convierten alimentos y bebidas en energía.",
  },
  {
    id: "placebo",
    term: "Placebo",
    category: "Investigación",
    definition: "Sustancia sin ingredientes activos que se usa como comparación en estudios médicos.",
  },
  {
    id: "clinical-trial",
    term: "Ensayo clínico",
    category: "Investigación",
    definition:
      "Estudio de investigación que prueba tratamientos, medicamentos o dispositivos médicos en personas.",
  },
] as const;
