// Auto-generated by scripts/bundle-lessons.ts — do not edit by hand.
// Edit content/lessons/{en,es}/*.mdx then run: npm run content:bundle-lessons

import type { Lesson } from "@/types/lesson";

export const lessons: Lesson[] = [
  {
    id: "understanding-prescription-labels",
    title: "Understanding Prescription Labels",
    description: "Learn how to read and understand your medicine labels to take medications safely.",
    category: "Medication Safety",
    categoryId: "medication-safety",
    duration: "15 minutes",
    level: "beginner",
    image: "/stitch/lesson_understanding_prescription_labels.png",
    sidebarTips: [
      "Check the name.",
      "Read how many to take.",
      "Look for warnings.",
      "Ask what happens if you miss a dose.",
    ],
    sidebarTitle: "Still confused?",
    content: {
      sections: [
        {
          title: "What is a Prescription Label?",
          content:
            "A prescription label is the sticker on your medicine bottle that tells you how to take your medicine safely. It contains important information about your medication, including the dosage, when to take it, and any special instructions.",
        },
        {
          title: "Key Parts of a Label",
          content:
            "Every prescription label has several important sections:\n\n1. Your name - to make sure the medicine is for you\n2. Drug name and strength - what the medicine is and how strong it is\n3. Dosage - how much to take\n4. Frequency - how often to take it\n5. Special instructions - any warnings or special directions\n6. Expiration date - when the medicine should no longer be used",
          callouts: [
            {
              type: "info",
              content: "Always check that your name is on the label before taking any medication.",
            },
          ],
        },
        {
          title: "Understanding Dosage Instructions",
          content:
            'Dosage instructions tell you exactly how much medicine to take and when. Common instructions include:\n\n- "Take one tablet daily" means take one pill every day at the same time\n- "Take with food" means eat something before taking the medicine\n- "Take on an empty stomach" means wait 2 hours after eating or 1 hour before eating\n- "Twice daily" means take it two times per day, usually morning and evening',
          callouts: [
            {
              type: "warning",
              content:
                "Never take more than the prescribed amount. If you miss a dose, ask your pharmacist what to do.",
            },
          ],
        },
        {
          title: "Special Warnings",
          content:
            'Prescription labels may include special warnings such as:\n\n- "May cause drowsiness" - the medicine might make you sleepy, so don\'t drive\n- "Avoid alcohol" - drinking alcohol while taking this medicine can be dangerous\n- "Store in a cool, dry place" - keep the medicine away from heat and moisture\n- "Shake well before use" - for liquid medicines, mix it before pouring',
        },
        {
          title: "Questions to Ask Your Pharmacist",
          content:
            "If anything on your label is unclear, ask your pharmacist:\n\n1. What is this medicine for?\n2. How and when should I take it?\n3. What should I do if I miss a dose?\n4. Are there any side effects I should know about?\n5. Can I take this with my other medicines?",
          callouts: [
            {
              type: "success",
              content:
                "Your pharmacist is there to help. Never hesitate to ask questions about your medications.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "asking-about-medications",
    title: "Asking About Your Medications",
    description: "Learn the right questions to ask your doctor or pharmacist about any new medication.",
    category: "Medication Safety",
    categoryId: "medication-safety",
    duration: "10 minutes",
    level: "beginner",
    content: {
      sections: [
        {
          title: "Why Ask Questions?",
          content:
            "Asking questions about your medications helps you understand what you're taking and why. It can prevent mistakes, side effects, and dangerous drug interactions. You have the right to know everything about your medicines.",
        },
        {
          title: "Essential Questions to Ask",
          content:
            "When your doctor prescribes a new medication, ask these questions:\n\n1. What is the name of the medicine?\n2. What is it supposed to do?\n3. How and when should I take it?\n4. How long will I need to take it?\n5. What side effects should I watch for?\n6. Are there any foods or drinks I should avoid?\n7. What should I do if I miss a dose?",
        },
        {
          title: "About Drug Interactions",
          content:
            "Drug interactions happen when two or more medicines react with each other. Always tell your doctor and pharmacist about:\n\n- All prescription medicines you take\n- Over-the-counter medicines (like aspirin or cold medicine)\n- Vitamins and supplements\n- Herbal remedies\n- Any allergies you have",
          callouts: [
            {
              type: "warning",
              content: "Keep a list of all your medicines and show it to every doctor you visit.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "managing-side-effects",
    title: "Managing Side Effects",
    description: "Learn what side effects are, which ones are normal, and when to call your doctor.",
    category: "Medication Safety",
    categoryId: "medication-safety",
    duration: "12 minutes",
    level: "beginner",
    content: {
      sections: [
        {
          title: "What Are Side Effects?",
          content:
            "Side effects are unwanted reactions to a medication. They can range from mild (like a dry mouth) to severe (like an allergic reaction). Not everyone will experience side effects, and they may go away as your body gets used to the medicine.",
        },
        {
          title: "Common Mild Side Effects",
          content:
            "These side effects are usually not serious and may go away on their own:\n\n- Nausea or upset stomach\n- Drowsiness or dizziness\n- Dry mouth\n- Headache\n- Mild rash or itching\n\nIf these bother you, talk to your doctor or pharmacist. They may have suggestions to help.",
        },
        {
          title: "When to Call Your Doctor",
          content:
            "Call your doctor right away if you experience:\n\n- Trouble breathing or swallowing\n- Severe rash or hives\n- Swelling of the face, lips, or tongue\n- Severe dizziness or fainting\n- Chest pain or rapid heartbeat\n- Severe stomach pain or vomiting\n- Yellowing of the skin or eyes\n- Unusual bleeding or bruising",
          callouts: [
            {
              type: "warning",
              content: "If you think you're having a serious reaction, call 911 or go to the emergency room.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "before-your-visit",
    title: "Before Your Doctor Visit",
    description: "Prepare for your appointment to get the most out of your time with your doctor.",
    category: "Doctor Visits",
    categoryId: "doctor-visits",
    duration: "10 minutes",
    level: "beginner",
    content: {
      sections: [
        {
          title: "Gather Your Information",
          content:
            "Before your appointment, collect these important items:\n\n- Your insurance card and ID\n- A list of all your current medications\n- Your medical history, if you're seeing a new doctor\n- Previous test results or medical records\n- A list of your symptoms and when they started\n- Any questions you want to ask",
        },
        {
          title: "Write Down Your Symptoms",
          content:
            "Be specific about your symptoms. For each symptom, note:\n\n- When it started\n- How often it happens\n- What makes it better or worse\n- How severe it is (on a scale of 1-10)\n- Any other symptoms that happen at the same time",
        },
        {
          title: "Prepare Your Questions",
          content:
            "Write down your questions before your visit. Put the most important ones first. Good questions include:\n\n- What could be causing my symptoms?\n- What tests do I need?\n- What are my treatment options?\n- What should I do if I get worse?\n- When should I follow up with you?",
          callouts: [
            {
              type: "info",
              content: "Bring a notepad and pen to write down what your doctor says.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "during-your-visit",
    title: "During Your Doctor Visit",
    description: "Learn how to communicate effectively with your doctor during your appointment.",
    category: "Doctor Visits",
    categoryId: "doctor-visits",
    duration: "10 minutes",
    level: "beginner",
    content: {
      sections: [
        {
          title: "Be Honest and Complete",
          content:
            "Tell your doctor everything about your health, even if it feels embarrassing. Your doctor needs the full picture to help you. Don't leave anything out, including:\n\n- All medications you take (including supplements)\n- Your lifestyle habits (smoking, alcohol, exercise)\n- Any changes in your health\n- Your concerns and fears",
        },
        {
          title: "Ask for Clarification",
          content:
            'If your doctor uses medical terms you don\'t understand, ask them to explain in plain language. You can say:\n\n- "Can you explain that in simpler terms?"\n- "What does that word mean?"\n- "Can you write that down for me?"\n- "Can you give me an example?"',
        },
        {
          title: "Take Notes",
          content:
            "Write down important information during your visit, including:\n\n- Your diagnosis (what's wrong)\n- Your treatment plan\n- Medication instructions\n- When to follow up\n- Any warning signs to watch for",
          callouts: [
            {
              type: "success",
              content: "It's okay to ask your doctor to slow down or repeat something you missed.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "after-your-visit",
    title: "After Your Doctor Visit",
    description: "Follow up on your care plan and keep track of your health.",
    category: "Doctor Visits",
    categoryId: "doctor-visits",
    duration: "8 minutes",
    level: "beginner",
    content: {
      sections: [
        {
          title: "Review Your Instructions",
          content:
            "As soon as you get home, review what your doctor told you. Make sure you understand:\n\n- What medicines to take and when\n- Any lifestyle changes you need to make\n- When to schedule follow-up appointments\n- What to do if your symptoms get worse",
        },
        {
          title: "Fill Your Prescriptions",
          content:
            "If your doctor prescribed medication:\n\n- Go to your pharmacy right away\n- Show the pharmacist your insurance card\n- Ask the pharmacist any questions about your medicine\n- Read the label carefully before taking any medication",
        },
        {
          title: "Track Your Progress",
          content:
            "Keep a health journal to track:\n\n- Your symptoms and how they change\n- Side effects from medications\n- Questions that come up between visits\n- Any improvements or worsening of your condition",
          callouts: [
            {
              type: "info",
              content:
                "Bring your health journal to your next appointment to help your doctor understand your progress.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "blood-basics",
    title: "Blood Test Basics",
    description: "Understand what blood tests measure and why they're important.",
    category: "Lab Results",
    categoryId: "lab-results",
    duration: "15 minutes",
    level: "intermediate",
    sidebarTips: [
      "Ask if you need to fast (no eating or drinking).",
      "Drink plenty of water unless told not to.",
      "Wear sleeves that are easy to roll up.",
    ],
    sidebarTitle: "Prep tips",
    content: {
      sections: [
        {
          title: "Why Blood Tests?",
          content:
            "Blood tests help doctors understand what's happening inside your body. They can show:\n\n- How well your organs are working\n- If you have certain diseases or conditions\n- How well medications are working\n- If your immune system is fighting an infection",
        },
        {
          title: "Common Blood Tests",
          content:
            "Some of the most common blood tests include:\n\n- Complete Blood Count (CBC) - measures different parts of your blood\n- Basic Metabolic Panel - checks kidney function, electrolytes, and blood sugar\n- Lipid Panel - measures cholesterol and triglycerides\n- Glucose Test - checks blood sugar levels for diabetes\n- Thyroid Panel - checks how well your thyroid is working",
        },
        {
          title: "Understanding Reference Ranges",
          content:
            "Blood test results show your numbers compared to a \"reference range\" - the range that's considered normal for most people. Your result might be:\n\n- Within the normal range\n- Above the normal range (high)\n- Below the normal range (low)\n\nBeing slightly outside the range isn't always a problem. Your doctor will look at the whole picture.",
          callouts: [
            {
              type: "info",
              content:
                "Reference ranges can vary by lab, age, and sex. Always ask your doctor to explain your results.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "common-tests",
    title: "Understanding Common Lab Tests",
    description: "Learn what specific lab tests measure and what abnormal results might mean.",
    category: "Lab Results",
    categoryId: "lab-results",
    duration: "20 minutes",
    level: "intermediate",
    content: {
      sections: [
        {
          title: "Complete Blood Count (CBC)",
          content:
            "A CBC measures several parts of your blood:\n\n- Red blood cells - carry oxygen throughout your body\n- White blood cells - fight infection\n- Platelets - help your blood clot\n- Hemoglobin - the protein that carries oxygen in red blood cells\n- Hematocrit - the percentage of blood that's red blood cells",
        },
        {
          title: "Cholesterol Test",
          content:
            "Cholesterol tests measure different types of fats in your blood:\n\n- Total cholesterol - all cholesterol in your blood\n- LDL (bad) cholesterol - can build up in arteries\n- HDL (good) cholesterol - helps remove LDL from arteries\n- Triglycerides - a type of fat that stores energy",
          callouts: [
            {
              type: "warning",
              content: "High LDL and low HDL can increase your risk of heart disease.",
            },
          ],
        },
        {
          title: "Blood Sugar Tests",
          content:
            "Blood sugar tests check for diabetes or prediabetes:\n\n- Fasting glucose - blood sugar after not eating\n- A1C - average blood sugar over the past 2-3 months\n- Glucose tolerance - how your body handles sugar after eating",
        },
      ],
    },
  },
  {
    id: "when-to-worry",
    title: "When to Worry About Lab Results",
    description: "Learn which abnormal results need immediate attention and which can wait.",
    category: "Lab Results",
    categoryId: "lab-results",
    duration: "10 minutes",
    level: "intermediate",
    content: {
      sections: [
        {
          title: "Results That Need Quick Action",
          content:
            "Call your doctor right away if your results show:\n\n- Very low or very high blood sugar\n- Signs of infection (very high white blood cell count)\n- Kidney problems (very high creatinine)\n- Liver problems (very high liver enzymes)\n- Severe anemia (very low hemoglobin)",
          callouts: [
            {
              type: "warning",
              content:
                "If you can't reach your doctor and feel very sick, go to urgent care or the emergency room.",
            },
          ],
        },
        {
          title: "Results to Monitor",
          content:
            "Some abnormal results need attention but aren't emergencies:\n\n- Slightly high cholesterol\n- Mildly elevated blood sugar\n- Slightly low or high thyroid levels\n- Mild anemia\n\nYour doctor may want to retest in a few weeks or make lifestyle changes.",
        },
        {
          title: "Questions to Ask Your Doctor",
          content:
            "When discussing abnormal results, ask:\n\n- How serious is this result?\n- What could be causing it?\n- Do I need more tests?\n- What treatment do I need?\n- How will we monitor this?\n- What changes should I make?",
        },
      ],
    },
  },
] as const;
