// Auto-generated by scripts/bundle-lessons.ts — do not edit by hand.
// Edit content/lessons/{en,es}/*.mdx then run: npm run content:bundle-lessons

import type { Lesson } from "@/types/lesson";

export const lessonBundles: Record<"en" | "es", Lesson[]> = {
  "en": [
    {
      "id": "understanding-prescription-labels",
      "title": "Understanding Prescription Labels",
      "description": "Learn how to read and understand your medicine labels to take medications safely.",
      "category": "Medication Safety",
      "categoryId": "medication-safety",
      "duration": "15 minutes",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "What is a Prescription Label?",
            "content": "A prescription label is the sticker on your medicine bottle that tells you how to take your medicine safely. It contains important information about your medication, including the dosage, when to take it, and any special instructions."
          },
          {
            "title": "Key Parts of a Label",
            "content": "Every prescription label has several important sections:\n\n1. Your name - to make sure the medicine is for you\n2. Drug name and strength - what the medicine is and how strong it is\n3. Dosage - how much to take\n4. Frequency - how often to take it\n5. Special instructions - any warnings or special directions\n6. Expiration date - when the medicine should no longer be used",
            "callouts": [
              {
                "type": "info",
                "content": "Always check that your name is on the label before taking any medication."
              }
            ]
          },
          {
            "title": "Understanding Dosage Instructions",
            "content": "Dosage instructions tell you exactly how much medicine to take and when. Common instructions include:\n\n- \"Take one tablet daily\" means take one pill every day at the same time\n- \"Take with food\" means eat something before taking the medicine\n- \"Take on an empty stomach\" means wait 2 hours after eating or 1 hour before eating\n- \"Twice daily\" means take it two times per day, usually morning and evening",
            "callouts": [
              {
                "type": "warning",
                "content": "Never take more than the prescribed amount. If you miss a dose, ask your pharmacist what to do."
              }
            ]
          },
          {
            "title": "Special Warnings",
            "content": "Prescription labels may include special warnings such as:\n\n- \"May cause drowsiness\" - the medicine might make you sleepy, so don't drive\n- \"Avoid alcohol\" - drinking alcohol while taking this medicine can be dangerous\n- \"Store in a cool, dry place\" - keep the medicine away from heat and moisture\n- \"Shake well before use\" - for liquid medicines, mix it before pouring"
          },
          {
            "title": "Questions to Ask Your Pharmacist",
            "content": "If anything on your label is unclear, ask your pharmacist:\n\n1. What is this medicine for?\n2. How and when should I take it?\n3. What should I do if I miss a dose?\n4. Are there any side effects I should know about?\n5. Can I take this with my other medicines?",
            "callouts": [
              {
                "type": "success",
                "content": "Your pharmacist is there to help. Never hesitate to ask questions about your medications."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "asking-about-medications",
      "title": "Asking About Your Medications",
      "description": "Learn the right questions to ask your doctor or pharmacist about any new medication.",
      "category": "Medication Safety",
      "categoryId": "medication-safety",
      "duration": "10 minutes",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "Why Ask Questions?",
            "content": "Asking questions about your medications helps you understand what you're taking and why. It can prevent mistakes, side effects, and dangerous drug interactions. You have the right to know everything about your medicines."
          },
          {
            "title": "Essential Questions to Ask",
            "content": "When your doctor prescribes a new medication, ask these questions:\n\n1. What is the name of the medicine?\n2. What is it supposed to do?\n3. How and when should I take it?\n4. How long will I need to take it?\n5. What side effects should I watch for?\n6. Are there any foods or drinks I should avoid?\n7. What should I do if I miss a dose?"
          },
          {
            "title": "About Drug Interactions",
            "content": "Drug interactions happen when two or more medicines react with each other. Always tell your doctor and pharmacist about:\n\n- All prescription medicines you take\n- Over-the-counter medicines (like aspirin or cold medicine)\n- Vitamins and supplements\n- Herbal remedies\n- Any allergies you have",
            "callouts": [
              {
                "type": "warning",
                "content": "Keep a list of all your medicines and show it to every doctor you visit."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "managing-side-effects",
      "title": "Managing Side Effects",
      "description": "Learn what side effects are, which ones are normal, and when to call your doctor.",
      "category": "Medication Safety",
      "categoryId": "medication-safety",
      "duration": "12 minutes",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "What Are Side Effects?",
            "content": "Side effects are unwanted reactions to a medication. They can range from mild (like a dry mouth) to severe (like an allergic reaction). Not everyone will experience side effects, and they may go away as your body gets used to the medicine."
          },
          {
            "title": "Common Mild Side Effects",
            "content": "These side effects are usually not serious and may go away on their own:\n\n- Nausea or upset stomach\n- Drowsiness or dizziness\n- Dry mouth\n- Headache\n- Mild rash or itching\n\nIf these bother you, talk to your doctor or pharmacist. They may have suggestions to help."
          },
          {
            "title": "When to Call Your Doctor",
            "content": "Call your doctor right away if you experience:\n\n- Trouble breathing or swallowing\n- Severe rash or hives\n- Swelling of the face, lips, or tongue\n- Severe dizziness or fainting\n- Chest pain or rapid heartbeat\n- Severe stomach pain or vomiting\n- Yellowing of the skin or eyes\n- Unusual bleeding or bruising",
            "callouts": [
              {
                "type": "warning",
                "content": "If you think you're having a serious reaction, call 911 or go to the emergency room."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "before-your-visit",
      "title": "Before Your Doctor Visit",
      "description": "Prepare for your appointment to get the most out of your time with your doctor.",
      "category": "Doctor Visits",
      "categoryId": "doctor-visits",
      "duration": "10 minutes",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "Gather Your Information",
            "content": "Before your appointment, collect these important items:\n\n- Your insurance card and ID\n- A list of all your current medications\n- Your medical history, if you're seeing a new doctor\n- Previous test results or medical records\n- A list of your symptoms and when they started\n- Any questions you want to ask"
          },
          {
            "title": "Write Down Your Symptoms",
            "content": "Be specific about your symptoms. For each symptom, note:\n\n- When it started\n- How often it happens\n- What makes it better or worse\n- How severe it is (on a scale of 1-10)\n- Any other symptoms that happen at the same time"
          },
          {
            "title": "Prepare Your Questions",
            "content": "Write down your questions before your visit. Put the most important ones first. Good questions include:\n\n- What could be causing my symptoms?\n- What tests do I need?\n- What are my treatment options?\n- What should I do if I get worse?\n- When should I follow up with you?",
            "callouts": [
              {
                "type": "info",
                "content": "Bring a notepad and pen to write down what your doctor says."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "during-your-visit",
      "title": "During Your Doctor Visit",
      "description": "Learn how to communicate effectively with your doctor during your appointment.",
      "category": "Doctor Visits",
      "categoryId": "doctor-visits",
      "duration": "10 minutes",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "Be Honest and Complete",
            "content": "Tell your doctor everything about your health, even if it feels embarrassing. Your doctor needs the full picture to help you. Don't leave anything out, including:\n\n- All medications you take (including supplements)\n- Your lifestyle habits (smoking, alcohol, exercise)\n- Any changes in your health\n- Your concerns and fears"
          },
          {
            "title": "Ask for Clarification",
            "content": "If your doctor uses medical terms you don't understand, ask them to explain in plain language. You can say:\n\n- \"Can you explain that in simpler terms?\"\n- \"What does that word mean?\"\n- \"Can you write that down for me?\"\n- \"Can you give me an example?\""
          },
          {
            "title": "Take Notes",
            "content": "Write down important information during your visit, including:\n\n- Your diagnosis (what's wrong)\n- Your treatment plan\n- Medication instructions\n- When to follow up\n- Any warning signs to watch for",
            "callouts": [
              {
                "type": "success",
                "content": "It's okay to ask your doctor to slow down or repeat something you missed."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "after-your-visit",
      "title": "After Your Doctor Visit",
      "description": "Follow up on your care plan and keep track of your health.",
      "category": "Doctor Visits",
      "categoryId": "doctor-visits",
      "duration": "8 minutes",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "Review Your Instructions",
            "content": "As soon as you get home, review what your doctor told you. Make sure you understand:\n\n- What medicines to take and when\n- Any lifestyle changes you need to make\n- When to schedule follow-up appointments\n- What to do if your symptoms get worse"
          },
          {
            "title": "Fill Your Prescriptions",
            "content": "If your doctor prescribed medication:\n\n- Go to your pharmacy right away\n- Show the pharmacist your insurance card\n- Ask the pharmacist any questions about your medicine\n- Read the label carefully before taking any medication"
          },
          {
            "title": "Track Your Progress",
            "content": "Keep a health journal to track:\n\n- Your symptoms and how they change\n- Side effects from medications\n- Questions that come up between visits\n- Any improvements or worsening of your condition",
            "callouts": [
              {
                "type": "info",
                "content": "Bring your health journal to your next appointment to help your doctor understand your progress."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "blood-basics",
      "title": "Blood Test Basics",
      "description": "Understand what blood tests measure and why they're important.",
      "category": "Lab Results",
      "categoryId": "lab-results",
      "duration": "15 minutes",
      "level": "intermediate",
      "content": {
        "sections": [
          {
            "title": "Why Blood Tests?",
            "content": "Blood tests help doctors understand what's happening inside your body. They can show:\n\n- How well your organs are working\n- If you have certain diseases or conditions\n- How well medications are working\n- If your immune system is fighting an infection"
          },
          {
            "title": "Common Blood Tests",
            "content": "Some of the most common blood tests include:\n\n- Complete Blood Count (CBC) - measures different parts of your blood\n- Basic Metabolic Panel - checks kidney function, electrolytes, and blood sugar\n- Lipid Panel - measures cholesterol and triglycerides\n- Glucose Test - checks blood sugar levels for diabetes\n- Thyroid Panel - checks how well your thyroid is working"
          },
          {
            "title": "Understanding Reference Ranges",
            "content": "Blood test results show your numbers compared to a \"reference range\" - the range that's considered normal for most people. Your result might be:\n\n- Within the normal range\n- Above the normal range (high)\n- Below the normal range (low)\n\nBeing slightly outside the range isn't always a problem. Your doctor will look at the whole picture.",
            "callouts": [
              {
                "type": "info",
                "content": "Reference ranges can vary by lab, age, and sex. Always ask your doctor to explain your results."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "common-tests",
      "title": "Understanding Common Lab Tests",
      "description": "Learn what specific lab tests measure and what abnormal results might mean.",
      "category": "Lab Results",
      "categoryId": "lab-results",
      "duration": "20 minutes",
      "level": "intermediate",
      "content": {
        "sections": [
          {
            "title": "Complete Blood Count (CBC)",
            "content": "A CBC measures several parts of your blood:\n\n- Red blood cells - carry oxygen throughout your body\n- White blood cells - fight infection\n- Platelets - help your blood clot\n- Hemoglobin - the protein that carries oxygen in red blood cells\n- Hematocrit - the percentage of blood that's red blood cells"
          },
          {
            "title": "Cholesterol Test",
            "content": "Cholesterol tests measure different types of fats in your blood:\n\n- Total cholesterol - all cholesterol in your blood\n- LDL (bad) cholesterol - can build up in arteries\n- HDL (good) cholesterol - helps remove LDL from arteries\n- Triglycerides - a type of fat that stores energy",
            "callouts": [
              {
                "type": "warning",
                "content": "High LDL and low HDL can increase your risk of heart disease."
              }
            ]
          },
          {
            "title": "Blood Sugar Tests",
            "content": "Blood sugar tests check for diabetes or prediabetes:\n\n- Fasting glucose - blood sugar after not eating\n- A1C - average blood sugar over the past 2-3 months\n- Glucose tolerance - how your body handles sugar after eating"
          }
        ]
      }
    },
    {
      "id": "when-to-worry",
      "title": "When to Worry About Lab Results",
      "description": "Learn which abnormal results need immediate attention and which can wait.",
      "category": "Lab Results",
      "categoryId": "lab-results",
      "duration": "10 minutes",
      "level": "intermediate",
      "content": {
        "sections": [
          {
            "title": "Results That Need Quick Action",
            "content": "Call your doctor right away if your results show:\n\n- Very low or very high blood sugar\n- Signs of infection (very high white blood cell count)\n- Kidney problems (very high creatinine)\n- Liver problems (very high liver enzymes)\n- Severe anemia (very low hemoglobin)",
            "callouts": [
              {
                "type": "warning",
                "content": "If you can't reach your doctor and feel very sick, go to urgent care or the emergency room."
              }
            ]
          },
          {
            "title": "Results to Monitor",
            "content": "Some abnormal results need attention but aren't emergencies:\n\n- Slightly high cholesterol\n- Mildly elevated blood sugar\n- Slightly low or high thyroid levels\n- Mild anemia\n\nYour doctor may want to retest in a few weeks or make lifestyle changes."
          },
          {
            "title": "Questions to Ask Your Doctor",
            "content": "When discussing abnormal results, ask:\n\n- How serious is this result?\n- What could be causing it?\n- Do I need more tests?\n- What treatment do I need?\n- How will we monitor this?\n- What changes should I make?"
          }
        ]
      }
    }
  ],
  "es": [
    {
      "id": "understanding-prescription-labels",
      "title": "Entender las etiquetas de receta",
      "description": "Aprende a leer y entender las etiquetas de tus medicinas para tomarlas de forma segura.",
      "category": "Seguridad con medicamentos",
      "categoryId": "medication-safety",
      "duration": "15 minutos",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "¿Qué es una etiqueta de receta?",
            "content": "La etiqueta de receta es la información adherida al frasco o empaque de tu medicina. Te indica cómo tomarla de manera segura e incluye datos importantes como la dosis, cuándo tomarla y cualquier instrucción especial."
          },
          {
            "title": "Partes clave de una etiqueta",
            "content": "Toda etiqueta de receta tiene varias partes importantes:\n\n1. Tu nombre: para confirmar que la medicina es para ti\n2. Nombre y concentración del medicamento: qué medicina es y qué tan fuerte es\n3. Dosis: cuánto debes tomar\n4. Frecuencia: cada cuánto debes tomarla\n5. Instrucciones especiales: advertencias o indicaciones especiales\n6. Fecha de vencimiento: cuándo deja de ser seguro usarla",
            "callouts": [
              {
                "type": "info",
                "content": "Siempre verifica que tu nombre esté en la etiqueta antes de tomar cualquier medicina."
              }
            ]
          },
          {
            "title": "Cómo entender la dosis",
            "content": "Las instrucciones de dosis te dicen exactamente cuánto medicamento tomar y cuándo hacerlo. Ejemplos comunes:\n\n- \"Toma una tableta al día\" significa una pastilla todos los días a la misma hora\n- \"Tómalo con comida\" significa comer algo antes de tomar la medicina\n- \"Tómalo con el estómago vacío\" significa esperar 2 horas después de comer o 1 hora antes de comer\n- \"Dos veces al día\" normalmente significa por la mañana y por la noche",
            "callouts": [
              {
                "type": "warning",
                "content": "Nunca tomes más de la cantidad indicada. Si olvidas una dosis, pregunta a tu farmacéutico qué debes hacer."
              }
            ]
          },
          {
            "title": "Advertencias especiales",
            "content": "Las etiquetas de receta pueden incluir advertencias especiales como:\n\n- \"Puede causar sueño\": la medicina podría darte somnolencia, así que no manejes\n- \"Evita el alcohol\": beber alcohol con esta medicina puede ser peligroso\n- \"Guardar en un lugar fresco y seco\": mantén la medicina lejos del calor y la humedad\n- \"Agitar bien antes de usar\": en medicinas líquidas, mézclala antes de servirla"
          },
          {
            "title": "Preguntas para tu farmacéutico",
            "content": "Si algo en la etiqueta no está claro, pregunta a tu farmacéutico:\n\n1. ¿Para qué sirve esta medicina?\n2. ¿Cómo y cuándo debo tomarla?\n3. ¿Qué hago si olvido una dosis?\n4. ¿Qué efectos secundarios debo conocer?\n5. ¿Puedo tomarla con mis otras medicinas?",
            "callouts": [
              {
                "type": "success",
                "content": "Tu farmacéutico está para ayudarte. Nunca dudes en hacer preguntas sobre tus medicamentos."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "asking-about-medications",
      "title": "Preguntar sobre tus medicamentos",
      "description": "Aprende qué preguntas hacer a tu médico o farmacéutico sobre una medicina nueva.",
      "category": "Seguridad con medicamentos",
      "categoryId": "medication-safety",
      "duration": "10 minutos",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "¿Por qué hacer preguntas?",
            "content": "Hacer preguntas sobre tus medicamentos te ayuda a entender qué estás tomando y por qué. Puede prevenir errores, efectos secundarios e interacciones peligrosas. Tienes derecho a saber lo necesario sobre tus medicinas."
          },
          {
            "title": "Preguntas esenciales",
            "content": "Cuando tu médico te receta una medicina nueva, pregunta:\n\n1. ¿Cómo se llama la medicina?\n2. ¿Para qué sirve?\n3. ¿Cómo y cuándo debo tomarla?\n4. ¿Por cuánto tiempo debo tomarla?\n5. ¿Qué efectos secundarios debo vigilar?\n6. ¿Hay alimentos o bebidas que debo evitar?\n7. ¿Qué debo hacer si olvido una dosis?"
          },
          {
            "title": "Sobre las interacciones",
            "content": "Las interacciones ocurren cuando dos o más medicinas reaccionan entre sí. Siempre informa a tu médico y farmacéutico sobre:\n\n- Todas tus medicinas con receta\n- Medicinas de venta libre\n- Vitaminas y suplementos\n- Remedios herbales\n- Cualquier alergia que tengas",
            "callouts": [
              {
                "type": "warning",
                "content": "Lleva una lista de todas tus medicinas y muéstrala en cada consulta médica."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "managing-side-effects",
      "title": "Manejar los efectos secundarios",
      "description": "Aprende qué efectos secundarios pueden ser normales y cuándo debes llamar a tu médico.",
      "category": "Seguridad con medicamentos",
      "categoryId": "medication-safety",
      "duration": "12 minutos",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "¿Qué son los efectos secundarios?",
            "content": "Los efectos secundarios son reacciones no deseadas a un medicamento. Pueden variar desde algo leve, como resequedad en la boca, hasta algo grave, como una reacción alérgica. No todas las personas los presentan y a veces desaparecen cuando el cuerpo se adapta."
          },
          {
            "title": "Efectos secundarios leves comunes",
            "content": "Estos efectos secundarios suelen no ser graves y pueden desaparecer solos:\n\n- Náusea o malestar estomacal\n- Sueño o mareo\n- Boca seca\n- Dolor de cabeza\n- Sarpullido leve o comezón\n\nSi te molestan, habla con tu médico o farmacéutico para recibir orientación."
          },
          {
            "title": "Cuándo llamar al médico",
            "content": "Llama a tu médico de inmediato si presentas:\n\n- Dificultad para respirar o tragar\n- Sarpullido severo o ronchas\n- Hinchazón en cara, labios o lengua\n- Mareo intenso o desmayo\n- Dolor de pecho o latidos rápidos\n- Dolor de estómago intenso o vómito\n- Color amarillo en piel u ojos\n- Sangrado o moretones inusuales",
            "callouts": [
              {
                "type": "warning",
                "content": "Si crees que tienes una reacción grave, llama al 911 o ve a la sala de emergencia."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "before-your-visit",
      "title": "Antes de tu consulta médica",
      "description": "Prepárate para aprovechar mejor el tiempo con tu médico.",
      "category": "Consultas médicas",
      "categoryId": "doctor-visits",
      "duration": "10 minutos",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "Reúne tu información",
            "content": "Antes de tu cita, reúne estos elementos importantes:\n\n- Tarjeta del seguro e identificación\n- Lista de todas tus medicinas actuales\n- Historial médico, si verás a un médico nuevo\n- Resultados previos o expedientes\n- Lista de síntomas y cuándo comenzaron\n- Preguntas que quieres hacer"
          },
          {
            "title": "Anota tus síntomas",
            "content": "Sé específico sobre tus síntomas. Para cada uno, anota:\n\n- Cuándo empezó\n- Con qué frecuencia ocurre\n- Qué lo mejora o empeora\n- Qué tan fuerte es, por ejemplo del 1 al 10\n- Qué otros síntomas pasan al mismo tiempo"
          },
          {
            "title": "Prepara tus preguntas",
            "content": "Escribe tus preguntas antes de la visita y coloca primero las más importantes. Algunas buenas preguntas son:\n\n- ¿Qué podría estar causando mis síntomas?\n- ¿Qué pruebas necesito?\n- ¿Cuáles son mis opciones de tratamiento?\n- ¿Qué debo hacer si empeoro?\n- ¿Cuándo debo volver a consulta?",
            "callouts": [
              {
                "type": "info",
                "content": "Lleva libreta y pluma para anotar lo que diga tu médico."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "during-your-visit",
      "title": "Durante tu consulta médica",
      "description": "Aprende a comunicarte con claridad y confianza durante tu cita.",
      "category": "Consultas médicas",
      "categoryId": "doctor-visits",
      "duration": "10 minutos",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "Sé honesto y completo",
            "content": "Cuéntale a tu médico todo sobre tu salud, incluso si algo te da pena. Necesita la historia completa para ayudarte. No omitas información, incluyendo:\n\n- Todas las medicinas que tomas\n- Hábitos de vida como fumar, alcohol o ejercicio\n- Cambios recientes en tu salud\n- Preocupaciones o miedos que tengas"
          },
          {
            "title": "Pide aclaraciones",
            "content": "Si tu médico usa términos que no entiendes, pídele que te los explique con lenguaje sencillo. Puedes decir:\n\n- \"¿Puede explicarlo con palabras más simples?\"\n- \"¿Qué significa esa palabra?\"\n- \"¿Puede escribirlo para mí?\"\n- \"¿Me puede dar un ejemplo?\""
          },
          {
            "title": "Toma notas",
            "content": "Anota información importante durante tu visita, como:\n\n- Tu diagnóstico\n- Tu plan de tratamiento\n- Instrucciones sobre medicamentos\n- Cuándo debes regresar\n- Señales de alerta que debes vigilar",
            "callouts": [
              {
                "type": "success",
                "content": "Está bien pedir a tu médico que hable más despacio o repita algo."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "after-your-visit",
      "title": "Después de tu consulta médica",
      "description": "Da seguimiento a tu plan de cuidado y mantén un registro de tu salud.",
      "category": "Consultas médicas",
      "categoryId": "doctor-visits",
      "duration": "8 minutos",
      "level": "beginner",
      "content": {
        "sections": [
          {
            "title": "Revisa tus instrucciones",
            "content": "Tan pronto llegues a casa, revisa lo que te explicó tu médico. Asegúrate de entender:\n\n- Qué medicinas tomar y cuándo\n- Qué cambios de hábitos necesitas hacer\n- Cuándo programar seguimiento\n- Qué hacer si tus síntomas empeoran"
          },
          {
            "title": "Surte tus recetas",
            "content": "Si tu médico te recetó medicina:\n\n- Ve a la farmacia lo antes posible\n- Lleva tu tarjeta de seguro\n- Haz preguntas al farmacéutico\n- Lee cuidadosamente la etiqueta antes de tomar la medicina"
          },
          {
            "title": "Da seguimiento a tu progreso",
            "content": "Lleva un registro de salud para seguir:\n\n- Tus síntomas y cómo cambian\n- Efectos secundarios de medicinas\n- Preguntas que surjan entre visitas\n- Mejorías o empeoramientos",
            "callouts": [
              {
                "type": "info",
                "content": "Lleva tu registro de salud a la próxima cita para ayudar a tu médico a entender tu progreso."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "blood-basics",
      "title": "Conceptos básicos de análisis de sangre",
      "description": "Entiende qué miden los análisis de sangre y por qué son importantes.",
      "category": "Resultados de laboratorio",
      "categoryId": "lab-results",
      "duration": "15 minutos",
      "level": "intermediate",
      "content": {
        "sections": [
          {
            "title": "¿Por qué se hacen análisis?",
            "content": "Los análisis de sangre ayudan a los médicos a entender qué pasa dentro de tu cuerpo. Pueden mostrar:\n\n- Qué tan bien funcionan tus órganos\n- Si tienes ciertas enfermedades o condiciones\n- Cómo están funcionando los medicamentos\n- Si tu sistema inmune está combatiendo una infección"
          },
          {
            "title": "Análisis de sangre comunes",
            "content": "Algunos análisis de sangre frecuentes incluyen:\n\n- Biometría hemática completa: mide distintas partes de tu sangre\n- Panel metabólico básico: revisa riñones, electrolitos y azúcar\n- Perfil de lípidos: mide colesterol y triglicéridos\n- Prueba de glucosa: revisa azúcar en sangre\n- Panel tiroideo: revisa el funcionamiento de la tiroides"
          },
          {
            "title": "Cómo entender los rangos de referencia",
            "content": "Los resultados comparan tus números con un \"rango de referencia\", que es el rango considerado normal para la mayoría de las personas. Tu resultado puede estar:\n\n- Dentro del rango normal\n- Arriba del rango normal\n- Debajo del rango normal\n\nEstar un poco fuera del rango no siempre significa un problema. Tu médico revisará el panorama completo.",
            "callouts": [
              {
                "type": "info",
                "content": "Los rangos pueden variar según el laboratorio, la edad y el sexo. Pide a tu médico que te explique tus resultados."
              }
            ]
          }
        ]
      }
    },
    {
      "id": "common-tests",
      "title": "Entender análisis de laboratorio comunes",
      "description": "Aprende qué miden pruebas específicas y qué pueden significar los resultados anormales.",
      "category": "Resultados de laboratorio",
      "categoryId": "lab-results",
      "duration": "20 minutos",
      "level": "intermediate",
      "content": {
        "sections": [
          {
            "title": "Biometría hemática completa (CBC)",
            "content": "Una biometría hemática completa mide varias partes de tu sangre:\n\n- Glóbulos rojos: llevan oxígeno por el cuerpo\n- Glóbulos blancos: combaten infecciones\n- Plaquetas: ayudan a coagular la sangre\n- Hemoglobina: proteína que transporta oxígeno\n- Hematocrito: porcentaje de sangre formado por glóbulos rojos"
          },
          {
            "title": "Prueba de colesterol",
            "content": "Las pruebas de colesterol miden distintos tipos de grasa en tu sangre:\n\n- Colesterol total\n- LDL o colesterol malo\n- HDL o colesterol bueno\n- Triglicéridos",
            "callouts": [
              {
                "type": "warning",
                "content": "Tener LDL alto y HDL bajo puede aumentar tu riesgo de enfermedad del corazón."
              }
            ]
          },
          {
            "title": "Pruebas de azúcar en sangre",
            "content": "Las pruebas de azúcar ayudan a detectar diabetes o prediabetes:\n\n- Glucosa en ayuno\n- A1C, que muestra el promedio de azúcar de los últimos 2 a 3 meses\n- Prueba de tolerancia a la glucosa, que evalúa cómo maneja tu cuerpo el azúcar"
          }
        ]
      }
    },
    {
      "id": "when-to-worry",
      "title": "Cuándo preocuparte por resultados de laboratorio",
      "description": "Aprende qué resultados requieren atención inmediata y cuáles pueden esperar.",
      "category": "Resultados de laboratorio",
      "categoryId": "lab-results",
      "duration": "10 minutos",
      "level": "intermediate",
      "content": {
        "sections": [
          {
            "title": "Resultados que necesitan atención rápida",
            "content": "Llama a tu médico de inmediato si tus resultados muestran:\n\n- Azúcar en sangre muy baja o muy alta\n- Señales de infección\n- Problemas renales\n- Problemas hepáticos\n- Anemia severa",
            "callouts": [
              {
                "type": "warning",
                "content": "Si no puedes localizar a tu médico y te sientes muy mal, ve a urgencias o a la sala de emergencia."
              }
            ]
          },
          {
            "title": "Resultados para vigilar",
            "content": "Algunos resultados anormales requieren atención pero no son emergencias:\n\n- Colesterol ligeramente alto\n- Azúcar un poco elevada\n- Niveles tiroideos un poco altos o bajos\n- Anemia leve\n\nTu médico puede repetir la prueba más adelante o recomendar cambios de hábitos."
          },
          {
            "title": "Preguntas para tu médico",
            "content": "Cuando hables de resultados anormales, pregunta:\n\n- ¿Qué tan serio es este resultado?\n- ¿Qué podría causarlo?\n- ¿Necesito más pruebas?\n- ¿Qué tratamiento necesito?\n- ¿Cómo vamos a vigilarlo?\n- ¿Qué cambios debo hacer?"
          }
        ]
      }
    }
  ]
} as const;
