// Auto-generated by scripts/bundle-lessons.ts — do not edit by hand.
// Edit content/lessons/{en,es}/*.mdx then run: npm run content:bundle-lessons
// Server/SSG only. Do not import this combined barrel from 'use client' modules.
// Client code must dynamic-import ./lessonBundles.en or ./lessonBundles.es.

import type { Lesson } from "@/types/lesson";

import { lessons as en } from "./lessonBundles.en";
import { lessons as es } from "./lessonBundles.es";

export const lessonBundles: Record<"en" | "es", Lesson[]> = { en, es } as const;
