// Auto-generated by scripts/bundle-paths.ts — do not edit by hand.
// Edit content/paths/{en,es}/*.mdx then run: npm run content:bundle-paths

import type { LearningPath } from "@/types/learningPath";

import { paths as en } from "./pathBundles.en";
import { paths as es } from "./pathBundles.es";

export const pathBundles: Record<"en" | "es", LearningPath[]> = { en, es } as const;
