// Auto-generated by scripts/bundle-paths.ts — do not edit by hand.
// Edit content/paths/{en,es}/*.mdx then run: npm run content:bundle-paths

import type { LearningPath } from "@/types/learningPath";

export const paths: LearningPath[] = [
  {
    id: "safer-medicine-use",
    title: "Safer Medicine Use",
    description:
      "Learn how to safely take and manage your medications, understand prescription labels, and avoid drug interactions.",
    lessons: [
      "understanding-prescription-labels",
      "asking-about-medications",
      "managing-side-effects",
      "generic-vs-brand-drugs",
      "pain-medications-safely",
      "otc-drug-interactions",
      "drug-food-interactions",
      "antibiotic-stewardship",
    ],
    duration: "50 minutes",
    level: "beginner",
    icon: "💊",
    content: {
      sections: [
        {
          title:
            "Medications can improve your health, but only if taken correctly. This path teaches you how to read prescription labels, what questions to ask your doctor or pharmacist, and how to recognize and manage side effects. Whether you take one medication or many, these skills help you stay safe.",
          content:
            ":::warning\r\nAlways talk to your doctor or pharmacist before changing how you take any medication.\r\n:::",
        },
      ],
    },
  },
  {
    id: "doctor-visit-prep",
    title: "Preparing for Doctor Visits",
    description:
      "Get ready for your appointments by knowing what to bring, what questions to ask, and how to follow up.",
    lessons: ["before-your-visit", "during-your-visit", "after-your-visit"],
    duration: "25 minutes",
    level: "beginner",
    icon: "🩺",
    content: {
      sections: [
        {
          title:
            "Doctor visits can feel rushed and overwhelming. This path helps you prepare so you get the most out of every appointment. Learn what to bring, how to describe your symptoms, what questions to ask, and how to follow up after your visit.",
          content:
            ":::info\r\nYou are the expert on your own body. A good doctor visit is a partnership — your doctor brings medical knowledge, and you bring knowledge about how you feel.\r\n:::",
        },
      ],
    },
  },
  {
    id: "understanding-labs",
    title: "Understanding Lab Results",
    description:
      "Learn what common blood tests measure, what reference ranges mean, and how to interpret your results.",
    lessons: [
      "blood-basics",
      "common-tests",
      "understanding-cbc",
      "understanding-a1c",
      "reading-lab-report",
      "when-to-worry",
    ],
    duration: "50 minutes",
    level: "intermediate",
    icon: "🔬",
    content: {
      sections: [
        {
          title:
            "Lab results are full of numbers and abbreviations that can be confusing. This path helps you understand common blood tests, what reference ranges mean, and when a result might be a cause for concern — or completely normal.",
          content:
            ":::info\r\nLab results are just one piece of the puzzle. Your doctor considers your symptoms, history, and overall health — not just numbers on a page.\r\n:::",
        },
      ],
    },
  },
  {
    id: "managing-new-diagnosis",
    title: "Managing a New Diagnosis",
    description:
      "Learn about common chronic conditions and how to understand and manage a new health diagnosis.",
    lessons: [
      "living-with-hypertension",
      "understanding-type2-diabetes",
      "type-1-vs-type-2-diabetes",
      "insulin-resistance-explained",
      "introduction-to-heart-disease",
      "understanding-lipids",
      "how-statins-work",
      "thyroid-disorders-basics",
      "asthma-basics",
      "copd-vs-asthma",
      "understanding-allergies",
      "sleep-apnea-basics",
      "understanding-oxygen-saturation",
    ],
    duration: "90 minutes",
    level: "intermediate",
    icon: "🏥",
    content: {
      sections: [
        {
          title:
            "Receiving a new diagnosis can feel overwhelming. This path helps you understand common chronic conditions — what they are, how they're managed, and how to work with your healthcare team. Each lesson builds understanding of a different condition, but you can take them in any order.",
          content:
            ":::info\r\nA new diagnosis is a starting point, not an ending one. Knowledge and consistent care help people with chronic conditions live full, active lives.\r\n:::",
        },
      ],
    },
  },
  {
    id: "staying-healthy-preventive",
    title: "Staying Healthy: Preventive Care",
    description:
      "Build healthy habits and stay up to date on vaccines and screenings to prevent illness before it starts.",
    lessons: [
      "why-preventive-care-matters",
      "common-adult-screenings",
      "understanding-vaccines",
      "cancer-screening-basics",
      "smoking-cessation-medicines",
      "hydration-and-health",
      "reading-nutrition-labels",
      "building-balanced-plate",
      "micronutrient-deficiencies",
      "glycemic-index-and-load",
    ],
    duration: "60 minutes",
    level: "beginner",
    icon: "🌿",
    content: {
      sections: [
        {
          title:
            "Preventive care is one of the most powerful tools for staying healthy. This path covers why prevention matters, which screenings you need at every age, how vaccines protect you, and how to build healthy eating habits. Perfect for anyone looking to take charge of their health.",
          content:
            ":::success\r\nSmall steps add up. Even one preventive action — a screening, a vaccine, a healthier meal — makes a difference.\r\n:::",
        },
      ],
    },
  },
  {
    id: "mental-wellness-basics",
    title: "Mental Wellness Basics",
    description:
      "Understand depression and anxiety, learn coping strategies, and discover how sleep impacts mental health.",
    lessons: [
      "understanding-depression",
      "anxiety-and-panic",
      "how-antidepressants-work",
      "managing-stress",
      "sleep-and-health",
    ],
    duration: "40 minutes",
    level: "beginner",
    icon: "🧠",
    content: {
      sections: [
        {
          title:
            "Mental health is just as important as physical health. This path covers the basics of depression, anxiety, and the critical role of sleep in mental wellness. Learn to recognize symptoms, when to seek help, and practical strategies for coping.",
          content:
            ":::warning\r\nIf you're in crisis, call or text **988** (US). Help is available 24/7.\r\n:::",
        },
      ],
    },
  },
  {
    id: "navigating-healthcare",
    title: "Navigating Healthcare",
    description:
      "Learn how health insurance works, how to read medical bills, when to seek emergency care, and how to prepare for doctor visits.",
    lessons: [
      "understanding-health-insurance",
      "reading-medical-bills",
      "when-to-call-911",
      "before-your-visit",
      "building-first-aid-kit",
      "understanding-copay-assistance",
      "when-to-use-urgent-care",
    ],
    duration: "40 minutes",
    level: "intermediate",
    icon: "📋",
    content: {
      sections: [
        {
          title:
            "The healthcare system can feel overwhelming. This path helps you navigate it with confidence — from understanding insurance and reading medical bills to knowing when to call 911 and how to get the most from your doctor visits.",
          content:
            ":::info\r\nKnowing how the system works saves money, reduces stress, and helps you get better care.\r\n:::",
        },
      ],
    },
  },
] as const;
