// Auto-generated by scripts/bundle-paths.ts — do not edit by hand.
// Edit content/paths/{en,es}/*.mdx then run: npm run content:bundle-paths

import type { LearningPath } from "@/types/learningPath";

export const paths: LearningPath[] = [
  {
    id: "safer-medicine-use",
    title: "Uso más seguro de medicamentos",
    description:
      "Aprende a tomar y manejar tus medicamentos con seguridad, entender etiquetas de receta y evitar interacciones.",
    lessons: [
      "understanding-prescription-labels",
      "asking-about-medications",
      "managing-side-effects",
      "generic-vs-brand-drugs",
      "pain-medications-safely",
      "otc-drug-interactions",
      "drug-food-interactions",
      "antibiotic-stewardship",
    ],
    duration: "50 minutes",
    level: "beginner",
    icon: "💊",
    content: {
      sections: [
        {
          title:
            "Usar medicamentos con seguridad reduce errores y efectos secundarios. Esta ruta cubre etiquetas de receta, preguntas para farmacéuticos y manejo de efectos adversos.",
          content: "",
          callouts: [
            {
              type: "warning",
              content:
                "Nunca comparta medicamentos recetados con otras personas, aunque los síntomas parezcan similares.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "doctor-visit-prep",
    title: "Preparación para visitas al médico",
    description: "Prepárate para tus citas sabiendo qué llevar, qué preguntar y cómo dar seguimiento.",
    lessons: ["before-your-visit", "during-your-visit", "after-your-visit"],
    duration: "25 minutes",
    level: "beginner",
    icon: "🩺",
    content: {
      sections: [
        {
          title:
            "Las visitas al médico pueden sentirse apresuradas y abrumadoras. Esta ruta le ayuda a prepararse para sacar el máximo provecho de cada cita. Aprenda qué llevar, cómo describir síntomas, qué preguntas hacer y cómo hacer seguimiento.",
          content: "",
          callouts: [
            {
              type: "info",
              content:
                "Usted es el experto en su propio cuerpo. Una buena visita es una colaboración — su médico aporta conocimiento médico y usted aporta cómo se siente.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "understanding-labs",
    title: "Entendiendo los resultados de laboratorio",
    description:
      "Aprende qué miden los análisis de sangre comunes, qué significan los rangos de referencia y cómo interpretar tus resultados.",
    lessons: [
      "blood-basics",
      "common-tests",
      "understanding-cbc",
      "understanding-a1c",
      "reading-lab-report",
      "when-to-worry",
    ],
    duration: "50 minutes",
    level: "intermediate",
    icon: "🔬",
    content: {
      sections: [
        {
          title:
            "Los resultados de laboratorio pueden ser difíciles de interpretar. Esta ruta explica pruebas comunes, qué significan las banderas H/L y qué preguntar a su médico.",
          content: "",
          callouts: [
            {
              type: "info",
              content:
                "Un resultado fuera de rango no siempre significa enfermedad — su médico interpreta números en contexto.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "managing-new-diagnosis",
    title: "Manejando un nuevo diagnóstico",
    description:
      "Aprende sobre condiciones crónicas comunes y cómo entender y manejar un nuevo diagnóstico de salud.",
    lessons: [
      "living-with-hypertension",
      "understanding-type2-diabetes",
      "type-1-vs-type-2-diabetes",
      "insulin-resistance-explained",
      "introduction-to-heart-disease",
      "understanding-lipids",
      "how-statins-work",
      "thyroid-disorders-basics",
      "asthma-basics",
      "copd-vs-asthma",
      "understanding-allergies",
      "sleep-apnea-basics",
      "understanding-oxygen-saturation",
    ],
    duration: "90 minutes",
    level: "intermediate",
    icon: "🏥",
    content: {
      sections: [
        {
          title:
            "Recibir un diagnóstico nuevo puede ser abrumador. Esta ruta le guía paso a paso para entender su condición, hacer preguntas útiles y construir un plan de cuidado que funcione para usted.",
          content: "",
          callouts: [
            {
              type: "info",
              content:
                "Un diagnóstico es un punto de partida, no un destino final. Muchas personas viven bien con condiciones crónicas siguiendo un plan personalizado.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "staying-healthy-preventive",
    title: "Mantenerse saludable: atención preventiva",
    description:
      "Crea hábitos saludables y mantente al día con vacunas y pruebas de detección para prevenir enfermedades.",
    lessons: [
      "why-preventive-care-matters",
      "common-adult-screenings",
      "understanding-vaccines",
      "cancer-screening-basics",
      "smoking-cessation-medicines",
      "hydration-and-health",
      "reading-nutrition-labels",
      "building-balanced-plate",
      "micronutrient-deficiencies",
      "glycemic-index-and-load",
    ],
    duration: "60 minutes",
    level: "beginner",
    icon: "🌿",
    content: {
      sections: [
        {
          title:
            "La atención preventiva detecta problemas temprano cuando el tratamiento suele ser más sencillo. Esta ruta cubre chequeos, vacunas y hábitos diarios que apoyan la salud a largo plazo.",
          content: "",
          callouts: [
            {
              type: "success",
              content: "Muchas pruebas preventivas están cubiertas sin copago cuando usa proveedores en red.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "mental-wellness-basics",
    title: "Conceptos básicos de bienestar mental",
    description:
      "Entiende la depresión y la ansiedad, aprende estrategias de afrontamiento y descubre cómo el sueño afecta la salud mental.",
    lessons: [
      "understanding-depression",
      "anxiety-and-panic",
      "how-antidepressants-work",
      "managing-stress",
      "sleep-and-health",
    ],
    duration: "40 minutes",
    level: "beginner",
    icon: "🧠",
    content: {
      sections: [
        {
          title:
            "La salud mental es tan importante como la física. Esta ruta cubre estrategias cotidianas, cuándo buscar ayuda profesional y cómo apoyar a quienes le importan.",
          content: "",
          callouts: [
            {
              type: "warning",
              content:
                "Si está en peligro inmediato o tiene pensamientos de hacerse daño, llame al 911 o a una línea de crisis.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "navigating-healthcare",
    title: "Navegando el sistema de salud",
    description:
      "Aprende cómo funciona el seguro de salud, cómo leer facturas médicas, cuándo buscar atención de emergencia y cómo prepararte para visitas.",
    lessons: [
      "understanding-health-insurance",
      "reading-medical-bills",
      "when-to-call-911",
      "before-your-visit",
      "building-first-aid-kit",
      "understanding-copay-assistance",
      "when-to-use-urgent-care",
    ],
    duration: "40 minutes",
    level: "intermediate",
    icon: "📋",
    content: {
      sections: [
        {
          title:
            "El sistema de salud puede ser confuso. Esta ruta explica seguros, facturas, cómo elegir proveedores y cómo abogar por usted mismo en citas y reclamos.",
          content: "",
          callouts: [
            {
              type: "info",
              content:
                "Lleve siempre su tarjeta de seguro, identificación y lista de medicamentos a cada visita.",
            },
          ],
        },
      ],
    },
  },
] as const;
