// Auto-generated by scripts/bundle-paths.ts — do not edit by hand.
// Edit content/paths/{en,es}/*.mdx then run: npm run content:bundle-paths

import type { LearningPath } from "@/types/learningPath";

export const paths: LearningPath[] = [
  {
    id: "safer-medicine-use",
    title: "Uso más seguro de medicamentos",
    description:
      "Aprende a tomar y manejar tus medicamentos con seguridad, entender etiquetas de receta y evitar interacciones.",
    lessons: [
      "understanding-prescription-labels",
      "asking-about-medications",
      "managing-side-effects",
      "generic-vs-brand-drugs",
      "pain-medications-safely",
    ],
    duration: "30 minutes",
    level: "beginner",
    icon: "💊",
  },
  {
    id: "doctor-visit-prep",
    title: "Preparación para visitas al médico",
    description: "Prepárate para tus citas sabiendo qué llevar, qué preguntar y cómo dar seguimiento.",
    lessons: ["before-your-visit", "during-your-visit", "after-your-visit"],
    duration: "25 minutes",
    level: "beginner",
    icon: "🩺",
  },
  {
    id: "understanding-labs",
    title: "Entendiendo los resultados de laboratorio",
    description:
      "Aprende qué miden los análisis de sangre comunes, qué significan los rangos de referencia y cómo interpretar tus resultados.",
    lessons: ["blood-basics", "common-tests", "reading-lab-report", "when-to-worry"],
    duration: "35 minutes",
    level: "intermediate",
    icon: "🔬",
  },
  {
    id: "managing-new-diagnosis",
    title: "Manejando un nuevo diagnóstico",
    description:
      "Aprende sobre condiciones crónicas comunes y cómo entender y manejar un nuevo diagnóstico de salud.",
    lessons: [
      "living-with-hypertension",
      "understanding-type2-diabetes",
      "introduction-to-heart-disease",
      "asthma-basics",
      "understanding-allergies",
      "sleep-apnea-basics",
    ],
    duration: "45 minutes",
    level: "intermediate",
    icon: "🏥",
  },
  {
    id: "staying-healthy-preventive",
    title: "Mantenerse saludable: atención preventiva",
    description:
      "Crea hábitos saludables y mantente al día con vacunas y pruebas de detección para prevenir enfermedades.",
    lessons: [
      "why-preventive-care-matters",
      "common-adult-screenings",
      "understanding-vaccines",
      "cancer-screening-basics",
      "hydration-and-health",
      "reading-nutrition-labels",
      "building-balanced-plate",
    ],
    duration: "45 minutes",
    level: "beginner",
    icon: "🌿",
  },
  {
    id: "mental-wellness-basics",
    title: "Conceptos básicos de bienestar mental",
    description:
      "Entiende la depresión y la ansiedad, aprende estrategias de afrontamiento y descubre cómo el sueño afecta la salud mental.",
    lessons: ["understanding-depression", "anxiety-and-panic", "managing-stress", "sleep-and-health"],
    duration: "30 minutes",
    level: "beginner",
    icon: "🧠",
  },
  {
    id: "navigating-healthcare",
    title: "Navegando el sistema de salud",
    description:
      "Aprende cómo funciona el seguro de salud, cómo leer facturas médicas, cuándo buscar atención de emergencia y cómo prepararte para visitas.",
    lessons: [
      "understanding-health-insurance",
      "reading-medical-bills",
      "when-to-call-911",
      "before-your-visit",
      "building-first-aid-kit",
      "understanding-copay-assistance",
      "when-to-use-urgent-care",
    ],
    duration: "40 minutes",
    level: "intermediate",
    icon: "📋",
  },
] as const;
