// Auto-generated by scripts/bundle-paths.ts — do not edit by hand.
// Edit content/paths/{en,es}/*.mdx then run: npm run content:bundle-paths

import type { LearningPath } from "@/types/learningPath";

export const paths: LearningPath[] = [
  {
    "id": "safer-medicine-use",
    "title": "Uso más seguro de medicamentos",
    "description": "Aprende a tomar y organizar tus medicinas de forma segura, entender las etiquetas y evitar interacciones.",
    "lessons": [
      "understanding-prescription-labels",
      "asking-about-medications",
      "managing-side-effects"
    ],
    "duration": "30 minutos",
    "level": "beginner",
    "icon": "💊"
  },
  {
    "id": "doctor-visit-prep",
    "title": "Prepararte para tus consultas médicas",
    "description": "Llega a tus citas con más confianza sabiendo qué llevar, qué preguntar y cómo dar seguimiento.",
    "lessons": [
      "before-your-visit",
      "during-your-visit",
      "after-your-visit"
    ],
    "duration": "25 minutos",
    "level": "beginner",
    "icon": "🩺"
  },
  {
    "id": "understanding-labs",
    "title": "Entender los resultados de laboratorio",
    "description": "Aprende a leer análisis de sangre comunes y a comprender qué significan los números para tu salud.",
    "lessons": [
      "blood-basics",
      "common-tests",
      "when-to-worry"
    ],
    "duration": "40 minutos",
    "level": "intermediate",
    "icon": "🔬"
  }
] as const;
