// Auto-generated by scripts/bundle-quizzes.ts — do not edit by hand.
// Edit content/quizzes/{en,es}/*.mdx then run: npm run content:bundle-quizzes

import type { Quiz } from "@/types/quiz";

export const quizzes: Quiz[] = [
  {
    id: "understanding-prescription-labels",
    title: "Understanding Prescription Labels Quiz",
    lessonId: "understanding-prescription-labels",
    passScore: 70,
    questions: [
      {
        question: 'What does "Rx" on a prescription label mean?',
        options: [
          "Remedy X-ray",
          "Prescription (from Latin _recipere_)",
          "Required eXtract",
          "Repeat dosage",
        ],
        correctAnswer: "B",
        explanation:
          '"Rx" comes from the Latin word _recipere_, meaning "to take." It is the standard abbreviation for a medical prescription.',
      },
      {
        question: "Which part of the prescription label tells you how often to take your medication?",
        options: ["Patient name", "Pharmacy name", "Dosage instructions", "Refill count"],
        correctAnswer: "C",
        explanation:
          "The dosage instructions (or sig) tell you how much to take, how often, and by which route. Patient and pharmacy details are identifiers, and refill count shows remaining authorizations.",
      },
      {
        question: 'What does "NDC" stand for on a prescription label?',
        options: [
          "National Drug Code",
          "New Dosage Calculation",
          "Named Drug Classification",
          "Non-Drowsy Compound",
        ],
        correctAnswer: "A",
        explanation:
          "The NDC is a unique identifier for the medication, including the manufacturer, product, and package size. It helps prevent dispensing errors.",
      },
      {
        question: 'If your label says "Take 1 tablet by mouth twice daily," when should you take it?',
        options: [
          "Every 2 hours",
          "Once in the morning and once at night",
          "Only when symptoms appear",
          "Every 12 hours exactly",
        ],
        correctAnswer: "B",
        explanation:
          '"Twice daily" usually means morning and evening, approximately 10-12 hours apart. Taking with meals can help you remember.',
      },
      {
        question:
          "What should you do if the medication name on the label does not match what your doctor said?",
        options: [
          "Take it anyway",
          "Call your pharmacist before taking it",
          "Look it up online",
          "Wait until your next appointment",
        ],
        correctAnswer: "B",
        explanation:
          "Always verify with your pharmacist if the medication name looks different from what you expected. The generic name may differ from the brand name, but it is safest to confirm.",
      },
      {
        question: "Why is the expiration date important on a prescription label?",
        options: [
          "It is optional",
          "The medication may be less effective or unsafe after this date",
          "It tells you when to refill",
          "It shows when the pharmacy opened the bottle",
        ],
        correctAnswer: "B",
        explanation:
          "Expired medications can lose potency or degrade into harmful compounds. Always check the expiration date and properly dispose of expired medicines.",
      },
      {
        question: "What do the warning labels on a prescription bottle indicate?",
        options: [
          "The cost of the medication",
          "Special precautions like drowsiness or avoiding alcohol",
          "The manufacturer's address",
          "How to refill",
        ],
        correctAnswer: "B",
        explanation:
          'Warning labels highlight specific safety precautions such as "may cause drowsiness," "avoid alcohol," or "take with food." Always read these before starting a new medication.',
      },
      {
        question: "What information is NOT typically found on a prescription label?",
        options: [
          "Prescribing doctor's name",
          "Pharmacy phone number",
          "Medication cost",
          "Refill information",
        ],
        correctAnswer: "C",
        explanation:
          "Prescription labels include the patient name, doctor name, pharmacy details, medication name, dosage, instructions, and refill info — but not the cost. The pharmacy can provide pricing separately.",
      },
      {
        question: 'If your label says "May cause drowsiness," what should you avoid?',
        options: [
          "Drinking water",
          "Driving or operating heavy machinery",
          "Eating food",
          "Taking other medications",
        ],
        correctAnswer: "B",
        explanation:
          "Drowsiness warnings mean the medication can impair your alertness. Avoid driving or operating heavy machinery until you know how the medicine affects you.",
      },
      {
        question: "What does the refill number on a label tell you?",
        options: [
          "How many times you can refill the prescription",
          "When the medication expires",
          "The pharmacy's refill policy",
          "The doctor's DEA number",
        ],
        correctAnswer: "A",
        explanation:
          'The refill count shows how many additional times you can get the same prescription refilled without seeing your doctor. "Refills: 0" means you need a new prescription.',
      },
    ],
  },
  {
    id: "asking-about-medications",
    title: "Asking About Medications Quiz",
    lessonId: "asking-about-medications",
    passScore: 70,
    questions: [
      {
        question:
          "Which of the following is the most important reason to tell your doctor about all medications you are taking?",
        options: [
          "So the doctor can prescribe more of the same medication",
          "To avoid dangerous drug interactions between medications",
          "To save money on your pharmacy bill",
          "So the doctor can contact your pharmacist",
        ],
        correctAnswer: "B",
        explanation:
          "Telling your doctor about every medication you take, including over-the-counter drugs and supplements, helps prevent harmful drug interactions. Some medications can cancel each other out or combine to cause serious side effects.",
      },
      {
        question: "What should you ask your doctor before starting a new medication?",
        options: [
          "What color the pill is",
          "Whether similar medications are cheaper in other countries",
          "What the medication is for, how to take it, and what side effects to expect",
          "How much weight you will lose from taking it",
        ],
        correctAnswer: "C",
        explanation:
          "Before starting any new medication, you should understand its purpose, the correct dosage and timing, potential side effects, and any food or activity restrictions. This helps you take the medication safely and effectively.",
      },
      {
        question: 'What does the term "generic" mean when referring to medication?',
        options: [
          "A medication that is less effective than the brand name",
          "A medication that does not require a prescription",
          "A copy of a brand-name drug that has the same active ingredients",
          "A medication that is only available in liquid form",
        ],
        correctAnswer: "C",
        explanation:
          "Generic medications contain the same active ingredients as brand-name drugs and must meet the same FDA standards for safety and effectiveness. They are usually much cheaper than brand-name versions.",
      },
      {
        question: "If you forget to take a dose of your medication, what is the safest approach?",
        options: [
          "Take a double dose at the next scheduled time",
          "Skip the missed dose and never take it again",
          "Check the medication label or ask your pharmacist what to do",
          "Crush the pill and mix it with food",
        ],
        correctAnswer: "C",
        explanation:
          "Instructions for missed doses vary by medication. Some should be taken as soon as you remember, while others should be skipped if close to the next dose. Always check the label or ask your pharmacist to be safe.",
      },
      {
        question: "Why is it important to keep an updated list of your medications with you at all times?",
        options: [
          "So you can show your insurance company",
          "Emergency responders need to know what medications you take",
          "To prove you are following your doctors orders",
          "So you can compare prices at different pharmacies",
        ],
        correctAnswer: "B",
        explanation:
          "In an emergency, paramedics and emergency room doctors need to know exactly what medications you are taking to make safe treatment decisions. An updated list can prevent dangerous errors.",
      },
    ],
  },
  {
    id: "managing-side-effects",
    title: "Managing Side Effects Quiz",
    lessonId: "managing-side-effects",
    passScore: 70,
    questions: [
      {
        question: "What should you do first if you experience a side effect from a medication?",
        options: [
          "Immediately stop taking the medication",
          "Contact your doctor or pharmacist to discuss the symptom",
          "Double your dose to make the side effect go away faster",
          "Wait one month to see if it gets worse",
        ],
        correctAnswer: "B",
        explanation:
          "Always contact your doctor or pharmacist when you notice a side effect. They can determine if it is normal, adjust your dose, or switch you to a different medication. Stopping medication suddenly can be dangerous.",
      },
      {
        question: "Which of the following is a common side effect of many medications?",
        options: ["Improved vision", "Increased height", "Nausea or upset stomach", "Enhanced memory"],
        correctAnswer: "C",
        explanation:
          "Nausea and digestive upset are among the most common side effects across many different medications. Taking medication with food or at a specific time of day can often help reduce these symptoms.",
      },
      {
        question: "What is the difference between a side effect and an allergic reaction?",
        options: [
          "There is no difference, they are the same thing",
          "A side effect is expected and often mild; an allergic reaction involves the immune system and can be serious",
          "An allergic reaction only happens with generic drugs",
          "Side effects only happen with liquid medications",
        ],
        correctAnswer: "B",
        explanation:
          "Side effects are known possible reactions that are usually mild and may go away as your body adjusts. Allergic reactions involve the immune system and can cause hives, swelling, or trouble breathing, which requires immediate medical attention.",
      },
      {
        question: "What can help reduce medication side effects like dizziness or drowsiness?",
        options: [
          "Taking the medication with grapefruit juice",
          "Taking the medication at bedtime if your doctor approves",
          "Chewing the medication instead of swallowing it",
          "Drinking alcohol to counteract the dizziness",
        ],
        correctAnswer: "B",
        explanation:
          "Taking certain medications at bedtime can help manage side effects like dizziness or drowsiness. Always ask your doctor or pharmacist about the best time to take your medication and whether food or specific timing can help.",
      },
      {
        question: "If you are taking multiple medications and notice new symptoms, what could be happening?",
        options: [
          "The symptoms are definitely unrelated to your medications",
          "You may be experiencing a drug interaction between medications",
          "You should take extra vitamins to fix the symptoms",
          "Your body is building immunity to the medications",
        ],
        correctAnswer: "B",
        explanation:
          "New symptoms when taking multiple medications could signal a drug interaction. Certain combinations can change how medications work in your body. Always report new symptoms to your doctor, especially when starting a new medication.",
      },
    ],
  },
  {
    id: "before-your-visit",
    title: "Before Your Visit Quiz",
    lessonId: "before-your-visit",
    passScore: 70,
    questions: [
      {
        question: "What is the most important thing to bring to your doctors appointment?",
        options: [
          "A snack and a bottle of water",
          "Your ID, insurance card, and a list of your current medications",
          "A friend who can drive you home",
          "Your favorite book to read in the waiting room",
        ],
        correctAnswer: "B",
        explanation:
          "Bringing your ID and insurance card is essential for check-in. A current medication list including doses and frequencies helps your doctor make safe and informed decisions about your care.",
      },
      {
        question: "Why should you write down your questions before a doctors visit?",
        options: [
          "So you can impress your doctor with how prepared you are",
          "To avoid forgetting important concerns during the appointment",
          "Because the receptionist collects your questions at check-in",
          "So the doctor does not have to talk to you",
        ],
        correctAnswer: "B",
        explanation:
          "Doctor visits are often short and can feel overwhelming. Writing down your questions beforehand ensures you cover everything that matters to you, even if you feel nervous or rushed during the appointment.",
      },
      {
        question: "What should you do if you have new symptoms but your appointment is weeks away?",
        options: [
          "Wait until the appointment and then mention them",
          "Call your doctors office to ask if you should come in sooner",
          "Go to the emergency room for any new symptom",
          "Try to treat the symptoms yourself without medical advice",
        ],
        correctAnswer: "B",
        explanation:
          "If new symptoms develop before your scheduled appointment, call your doctors office. They can advise whether you need to be seen sooner, speak with a nurse, or if it is safe to wait. Some symptoms need prompt attention.",
      },
      {
        question: "How far in advance should you arrive for a typical doctors appointment?",
        options: [
          "2 to 3 hours early",
          "Exactly at the appointment time, not earlier",
          "10 to 15 minutes early to complete paperwork",
          "Whenever you want, as long as you arrive before the office closes",
        ],
        correctAnswer: "C",
        explanation:
          "Arriving 10 to 15 minutes early gives you time to check in, update your insurance information, and complete any necessary forms. This helps the appointment start on time and reduces stress.",
      },
      {
        question: 'What is a "visit summary" and why is it important?',
        options: [
          "A summary of what you watched on TV in the waiting room",
          "A document your doctor gives you that explains the visit, any new medications, and follow-up steps",
          "A bill for the appointment",
          "A summary your friend writes about your symptoms",
        ],
        correctAnswer: "B",
        explanation:
          "A visit summary is a document that outlines what was discussed during your appointment, including diagnoses, medication changes, and follow-up instructions. Reviewing it helps ensure you understand and remember your care plan.",
      },
    ],
  },
  {
    id: "during-your-visit",
    title: "During Your Visit Quiz",
    lessonId: "during-your-visit",
    passScore: 70,
    questions: [
      {
        question:
          "What should you do if you do not understand something your doctor says during the appointment?",
        options: [
          "Nod and agree so you do not seem difficult",
          "Ask the doctor to explain it in simpler terms",
          "Look it up on your phone after the appointment",
          "Assume it is not important",
        ],
        correctAnswer: "B",
        explanation:
          "It is your right to understand your health. Doctors use medical terms that can be confusing. Asking for clarification helps you make informed decisions about your care. A good doctor will be happy to explain.",
      },
      {
        question:
          "Why is it important to be honest with your doctor about your habits like smoking, drinking, or diet?",
        options: [
          "So the doctor can judge your lifestyle choices",
          "Because these habits affect your health and treatment options",
          "So the information can be shared with your employer",
          "It is not important; you can keep these private",
        ],
        correctAnswer: "B",
        explanation:
          "Your lifestyle directly affects your health risks and how well treatments will work. Doctors need accurate information to provide the best care. They are bound by privacy laws and are there to help, not judge.",
      },
      {
        question: 'What is a "telehealth" visit?',
        options: [
          "A visit where you talk to your doctor through a phone call or video call",
          "A visit where a robot examines you",
          "A visit where you send emails to your doctor",
          "A visit that happens over the telephone only for emergencies",
        ],
        correctAnswer: "A",
        explanation:
          "Telehealth uses technology to connect you with your doctor remotely through phone or video. It is convenient for follow-ups, discussing test results, and managing ongoing conditions when an in-person exam is not needed.",
      },
      {
        question:
          "If you see a medical student or a nurse practitioner during your visit, what should you do?",
        options: [
          "Refuse to speak with anyone except the main doctor",
          "Ask for a discount because you are seeing a trainee",
          "Treat them with respect and answer their questions honestly",
          "Leave the appointment immediately",
        ],
        correctAnswer: "C",
        explanation:
          "Medical students and nurse practitioners are trained professionals working as part of your care team. They often spend more time with patients and communicate well. You can always ask for the attending doctor if you prefer.",
      },
      {
        question: "What should you do before leaving your doctors appointment?",
        options: [
          "Ask for a copy of your medical records to take home",
          "Make sure you understand the next steps: medications, follow-up visits, and any tests needed",
          "Request a second opinion from every doctor in the office",
          "Ask the receptionist to call you a taxi",
        ],
        correctAnswer: "B",
        explanation:
          "Before leaving, confirm your understanding of the treatment plan, including any new prescriptions, recommended tests, and when to schedule a follow-up. This prevents confusion and helps you follow through with your care.",
      },
    ],
  },
  {
    id: "after-your-visit",
    title: "After Your Visit Quiz",
    lessonId: "after-your-visit",
    passScore: 70,
    questions: [
      {
        question: "After a doctors visit, when should you fill a new prescription?",
        options: [
          "Only when you run out of your current medications",
          "As soon as possible, ideally the same day",
          "Whenever you remember, even if it is months later",
          "Only if the pharmacy offers a discount",
        ],
        correctAnswer: "B",
        explanation:
          "Filling your prescription right away ensures you do not forget and start your treatment on schedule. It also lets the pharmacist check for drug interactions and answer any questions you may have.",
      },
      {
        question:
          "What should you do if you have questions about your visit summary or discharge instructions?",
        options: [
          "Ignore them and hope for the best",
          "Call your doctors office to clarify before the next appointment",
          "Wait until your next visit and ask then",
          "Ask a friend to interpret the medical terms",
        ],
        correctAnswer: "B",
        explanation:
          "If anything in your visit summary is unclear, call your doctors office soon after the visit. Getting clarification quickly helps you follow your care plan correctly and avoid mistakes with medications or follow-up steps.",
      },
      {
        question: "Why is it important to schedule your next follow-up visit before leaving the office?",
        options: [
          "It saves you a phone call later and ensures you get an appointment at a good time",
          "The office charges less if you schedule ahead of time",
          "It is not important; you can call whenever you want",
          "The doctor will only see you if you schedule before leaving",
        ],
        correctAnswer: "A",
        explanation:
          "Scheduling your follow-up before leaving guarantees you a convenient appointment time and reduces the chance you will forget to book one later. Keeping follow-up appointments is key to managing your health.",
      },
      {
        question:
          "What should you do with medical documents like lab orders or referral forms after your visit?",
        options: [
          "Throw them away since everything is electronic now",
          "Keep them in a folder or file where you can find them easily",
          "Mail them back to your doctors office",
          "Post them on the refrigerator as a reminder",
        ],
        correctAnswer: "B",
        explanation:
          "Keep important medical documents, lab orders, and referral forms in a designated folder or file. Having them organized and accessible ensures you can follow through with tests and specialist appointments without delay.",
      },
      {
        question: "If your doctor ordered lab work, when should you expect to hear about the results?",
        options: [
          "The lab calls you the same day",
          "Doctors usually contact patients within a few days to a week with results",
          "You never hear back unless something is wrong",
          "Results are mailed to your home address in one month",
        ],
        correctAnswer: "B",
        explanation:
          "Most doctors offices contact patients with lab results within a few days to a week. If you have not heard back after a week, call the office. No news is not always good news, so it is best to follow up.",
      },
    ],
  },
  {
    id: "blood-basics",
    title: "Blood Basics Quiz",
    lessonId: "blood-basics",
    passScore: 70,
    questions: [
      {
        question: "What are the main components of blood?",
        options: [
          "Water, salt, and sugar",
          "Red blood cells, white blood cells, platelets, and plasma",
          "Oxygen, carbon dioxide, and nitrogen",
          "Vitamins, minerals, and protein",
        ],
        correctAnswer: "B",
        explanation:
          "Blood is made of four main components. Red blood cells carry oxygen, white blood cells fight infection, platelets help with clotting, and plasma is the liquid that carries them all. Each plays a vital role in keeping you healthy.",
      },
      {
        question: "What is the main function of red blood cells?",
        options: [
          "Fighting infections",
          "Carrying oxygen from the lungs to the rest of the body",
          "Helping blood clot after an injury",
          "Digesting food in the stomach",
        ],
        correctAnswer: "B",
        explanation:
          "Red blood cells contain hemoglobin, a protein that picks up oxygen in your lungs and delivers it to tissues throughout your body. Low red blood cell counts can cause fatigue and weakness, a condition called anemia.",
      },
      {
        question: "What do white blood cells do?",
        options: [
          "Help you breathe",
          "Carry nutrients to your organs",
          "Fight infections and protect against illness",
          "Control your body temperature",
        ],
        correctAnswer: "C",
        explanation:
          "White blood cells are part of your immune system. They identify and attack germs like bacteria and viruses. A high white blood cell count can indicate your body is fighting an infection.",
      },
      {
        question: "What is the role of platelets in the blood?",
        options: [
          "Carrying oxygen to the brain",
          "Fighting viruses",
          "Helping blood clot to stop bleeding",
          "Transporting hormones",
        ],
        correctAnswer: "C",
        explanation:
          "Platelets are tiny cell fragments that clump together at the site of an injury to form a plug and stop bleeding. Without enough platelets, even small cuts can bleed excessively.",
      },
      {
        question: "What is plasma?",
        options: [
          "The solid part of blood",
          "The liquid part of blood that carries cells, nutrients, and waste",
          "A type of white blood cell",
          "A protein that helps with digestion",
        ],
        correctAnswer: "B",
        explanation:
          "Plasma is the liquid portion of blood, making up about 55 percent of total blood volume. It carries blood cells, nutrients, hormones, and waste products throughout the body. Plasma is mostly water but contains important proteins and electrolytes.",
      },
    ],
  },
  {
    id: "common-tests",
    title: "Common Tests Quiz",
    lessonId: "common-tests",
    passScore: 70,
    questions: [
      {
        question: "What is a complete blood count or CBC test used for?",
        options: [
          "To measure how fast you can run",
          "To check your overall health and detect disorders like anemia or infection",
          "To see if your bones are broken",
          "To test your eyesight",
        ],
        correctAnswer: "B",
        explanation:
          "A CBC measures red blood cells, white blood cells, hemoglobin, and platelets. It is a common screening test that can help detect anemia, infection, inflammation, and other blood disorders.",
      },
      {
        question: "What does a blood pressure reading measure?",
        options: [
          "The speed of blood flow through your veins",
          "The force of blood against the walls of your arteries when your heart beats and rests",
          "The amount of sugar in your blood",
          "How much oxygen is in your lungs",
        ],
        correctAnswer: "B",
        explanation:
          "Blood pressure has two numbers: systolic (pressure when the heart beats) and diastolic (pressure when the heart rests between beats). High blood pressure over time can damage your heart and arteries.",
      },
      {
        question: "What is a cholesterol test also known as?",
        options: [
          "A stress test",
          "A lipid panel or lipid profile",
          "A glucose tolerance test",
          "A thyroid panel",
        ],
        correctAnswer: "B",
        explanation:
          "A lipid panel measures total cholesterol, LDL (bad cholesterol), HDL (good cholesterol), and triglycerides. It helps assess your risk for heart disease and stroke.",
      },
      {
        question: "What is the purpose of a urinalysis?",
        options: [
          "To test how much water you drink",
          "To detect kidney problems, urinary tract infections, and other health conditions",
          "To measure your lung capacity",
          "To check your reflexes",
        ],
        correctAnswer: "B",
        explanation:
          "A urinalysis examines the color, concentration, and content of your urine. It can detect kidney disease, urinary tract infections, diabetes, and other conditions. It is a simple, non-invasive test.",
      },
      {
        question: "What is a fasting blood glucose test used for?",
        options: [
          "To measure your blood sugar after eating a large meal",
          "To screen for diabetes and prediabetes after not eating for at least 8 hours",
          "To test your iron levels",
          "To check your kidney function",
        ],
        correctAnswer: "B",
        explanation:
          "A fasting blood glucose test measures your blood sugar after an overnight fast. Normal levels are typically below 100 mg/dL. Higher levels may indicate prediabetes or diabetes and require follow-up testing.",
      },
    ],
  },
  {
    id: "when-to-worry",
    title: "When to Worry Quiz",
    lessonId: "when-to-worry",
    passScore: 70,
    questions: [
      {
        question: "Which of the following symptoms requires immediate emergency care?",
        options: [
          "A mild headache after a long day",
          "Trouble breathing or shortness of breath that does not go away",
          "A small paper cut on your finger",
          "A stuffy nose from seasonal allergies",
        ],
        correctAnswer: "B",
        explanation:
          "Trouble breathing is a medical emergency that requires immediate attention. Call 911 or go to the emergency room if you have difficulty breathing, chest pain, or sudden confusion. Do not wait to see if it gets better on its own.",
      },
      {
        question: "What should you do if you have a fever of 103 degrees Fahrenheit or higher?",
        options: [
          "Take a cold shower immediately",
          "Wait one week to see if it goes down",
          "Call your doctor or seek medical attention",
          "Cover yourself with heavy blankets",
        ],
        correctAnswer: "C",
        explanation:
          "A fever of 103 degrees Fahrenheit or higher in adults requires medical attention. High fevers can indicate serious infections. Contact your doctor or seek medical care, especially if the fever is accompanied by other symptoms like stiff neck or confusion.",
      },
      {
        question: "What is a sign that chest pain might be serious and require emergency care?",
        options: [
          "The pain goes away when you change position",
          "The pain is sharp and lasts only a second",
          "The pain is accompanied by shortness of breath, nausea, or pain spreading to the arm or jaw",
          "The pain happens only when you take a deep breath",
        ],
        correctAnswer: "C",
        explanation:
          "Chest pain accompanied by shortness of breath, nausea, lightheadedness, or pain spreading to the arm, back, or jaw could be a heart attack. Call 911 immediately. Do not drive yourself to the hospital.",
      },
      {
        question: "Which of the following sudden symptoms could indicate a stroke?",
        options: [
          "A mild muscle cramp in your leg",
          "Numbness or weakness on one side of the face or body, confusion, or trouble speaking",
          "A headache that goes away after drinking water",
          "Blurred vision that clears up after blinking",
        ],
        correctAnswer: "B",
        explanation:
          "Use the FAST acronym to recognize stroke: Face drooping, Arm weakness, Speech difficulty, Time to call 911. Sudden numbness, confusion, trouble speaking, or vision changes require immediate emergency care.",
      },
      {
        question:
          "If you cut yourself and the bleeding does not stop after 10 minutes of direct pressure, what should you do?",
        options: [
          "Keep applying pressure and seek medical help",
          "Pour rubbing alcohol on the wound",
          "Wait another hour to see if it stops",
          "Remove the bandage and let the wound air dry",
        ],
        correctAnswer: "A",
        explanation:
          "If bleeding does not stop after 10 to 15 minutes of steady direct pressure, seek medical attention. You may need stitches or other treatment to close the wound and prevent excessive blood loss.",
      },
    ],
  },
  {
    id: "why-preventive-care-matters",
    title: "Why Preventive Care Matters Quiz",
    lessonId: "why-preventive-care-matters",
    passScore: 70,
    questions: [
      {
        question: "What is preventive care?",
        options: [
          "Treatment you receive after getting sick",
          "Medical care focused on preventing illness or detecting it early before it becomes serious",
          "Emergency care for life-threatening conditions",
          "Alternative medicine that replaces regular doctor visits",
        ],
        correctAnswer: "B",
        explanation:
          "Preventive care includes check-ups, vaccinations, and screenings that help prevent disease or catch it early when it is easiest to treat. Regular preventive care can help you live a longer, healthier life.",
      },
      {
        question: "Why are regular check-ups important even if you feel healthy?",
        options: [
          "They are not important if you feel fine",
          "Some health problems have no symptoms in early stages and can only be detected through screenings",
          "They are only required for people over age 65",
          "They are mainly for getting free samples from the doctor",
        ],
        correctAnswer: "B",
        explanation:
          "Many serious conditions like high blood pressure, high cholesterol, and some cancers have no early symptoms. Regular check-ups and screenings can detect these problems early when treatment is most effective.",
      },
      {
        question:
          "Under the Affordable Care Act, which preventive services are typically covered at no cost?",
        options: [
          "Only emergency room visits",
          "Many preventive services like vaccines and cancer screenings are covered without a copay",
          "No services are covered without cost",
          "Only prescription medications",
        ],
        correctAnswer: "B",
        explanation:
          "The Affordable Care Act requires most insurance plans to cover recommended preventive services like annual check-ups, vaccines, and cancer screenings without charging a copay or deductible. This makes it easier for people to get preventive care.",
      },
      {
        question: "How often should most adults have a routine physical exam?",
        options: [
          "Every 10 years",
          "Only when they are sick",
          "Once a year or as recommended by their doctor",
          "Never, if they feel healthy",
        ],
        correctAnswer: "C",
        explanation:
          "Most adults should have an annual physical exam. Your doctor may recommend a different schedule based on your age, health conditions, and risk factors. Regular visits help track changes in your health over time.",
      },
      {
        question: "What is a screening test?",
        options: [
          "A test that diagnoses a disease you already have symptoms for",
          "A test that looks for disease in people who do not have symptoms yet",
          "A test that determines your blood type",
          "A test that measures your fitness level",
        ],
        correctAnswer: "B",
        explanation:
          "Screening tests are given to people without symptoms to detect potential health problems early. Examples include mammograms for breast cancer, colonoscopies for colon cancer, and blood pressure checks for hypertension.",
      },
    ],
  },
  {
    id: "common-adult-screenings",
    title: "Common Adult Screenings Quiz",
    lessonId: "common-adult-screenings",
    passScore: 70,
    questions: [
      {
        question: "At what age should most women begin getting mammograms to screen for breast cancer?",
        options: [
          "Age 30",
          "Age 40 or as recommended by their doctor based on risk factors",
          "Age 60",
          "Age 21",
        ],
        correctAnswer: "B",
        explanation:
          "Most guidelines recommend women start regular mammograms at age 40. Women with a family history of breast cancer may need to start earlier. Mammograms can detect breast cancer years before a lump can be felt.",
      },
      {
        question: "What is a colonoscopy used to screen for?",
        options: [
          "Stomach ulcers",
          "Colon cancer and precancerous polyps",
          "Kidney stones",
          "Food allergies",
        ],
        correctAnswer: "B",
        explanation:
          "A colonoscopy allows doctors to examine the entire colon for abnormal growths called polyps. Removing these polyps can prevent colon cancer from developing. Screening usually begins at age 45 for average-risk adults.",
      },
      {
        question: "What does a Pap smear screen for?",
        options: [
          "Ovarian cancer",
          "Cervical cancer and precancerous changes in the cervix",
          "Urinary tract infections",
          "Thyroid problems",
        ],
        correctAnswer: "B",
        explanation:
          "A Pap smear collects cells from the cervix to look for abnormal changes that could lead to cervical cancer. Regular screening has dramatically reduced cervical cancer rates. Women typically start screening at age 21.",
      },
      {
        question: "What is the PSA test used for?",
        options: [
          "Screening for prostate cancer in men",
          "Testing for lung function",
          "Diagnosing diabetes",
          "Checking liver health",
        ],
        correctAnswer: "A",
        explanation:
          "The PSA blood test measures prostate-specific antigen, a protein produced by the prostate gland. High levels may indicate prostate cancer, though other conditions can also raise PSA. Men should discuss screening with their doctor starting around age 50.",
      },
      {
        question: "Why are regular blood pressure screenings important as you age?",
        options: [
          "Blood pressure only matters if you have symptoms",
          "High blood pressure often has no symptoms but can cause serious damage to your heart and arteries",
          "Blood pressure screenings are only needed for athletes",
          "Your blood pressure stays the same throughout your life",
        ],
        correctAnswer: "B",
        explanation:
          "High blood pressure is called the silent killer because it usually has no symptoms. Over time, it damages blood vessels and increases the risk of heart attack, stroke, and kidney disease. Regular screening is the only way to know your levels.",
      },
    ],
  },
  {
    id: "understanding-vaccines",
    title: "Understanding Vaccines Quiz",
    lessonId: "understanding-vaccines",
    passScore: 70,
    questions: [
      {
        question: "How do vaccines work to protect you from disease?",
        options: [
          "They cure diseases after you get sick",
          "They train your immune system to recognize and fight specific germs",
          "They create a barrier on your skin that blocks germs",
          "They replace your bodys natural immune system",
        ],
        correctAnswer: "B",
        explanation:
          "Vaccines contain weakened or inactivated parts of a germ. Your immune system learns to recognize the germ and builds antibodies against it. If you are later exposed to the real germ, your body can fight it off quickly.",
      },
      {
        question: "What is herd immunity?",
        options: [
          "A type of vaccine given to farm animals",
          "When most of a population is vaccinated, making it harder for disease to spread",
          "Immunity that is passed down from parents to children",
          "Natural immunity from getting sick",
        ],
        correctAnswer: "B",
        explanation:
          "Herd immunity occurs when a high percentage of a community is vaccinated, creating a barrier that slows or stops disease spread. This protects people who cannot get vaccinated, such as those with weakened immune systems or allergies.",
      },
      {
        question: "Why are booster shots sometimes needed?",
        options: [
          "Vaccines expire like food does",
          "Immunity from some vaccines can fade over time, and boosters strengthen the protection",
          "Boosters are optional and do not provide additional protection",
          "Boosters are only for children, never for adults",
        ],
        correctAnswer: "B",
        explanation:
          "For some vaccines, immunity decreases over time. A booster shot reminds your immune system to produce more antibodies, keeping you protected. Examples include tetanus boosters every 10 years and COVID-19 boosters.",
      },
      {
        question: "Which of the following is true about vaccine side effects?",
        options: [
          "Vaccines cause the disease they are meant to prevent in most people",
          "Most side effects are mild and short-lived, like soreness at the injection site or low fever",
          "Vaccines have no side effects at all",
          "Side effects are always severe and dangerous",
        ],
        correctAnswer: "B",
        explanation:
          "Common vaccine side effects include soreness, redness at the injection site, and mild fever. These are normal signs that your immune system is responding. Serious side effects are extremely rare compared to the risks of the diseases vaccines prevent.",
      },
      {
        question: "Which vaccine is recommended annually for most people?",
        options: [
          "The tetanus vaccine",
          "The flu (influenza) vaccine",
          "The hepatitis B vaccine",
          "The polio vaccine",
        ],
        correctAnswer: "B",
        explanation:
          "The flu vaccine is recommended every year because flu viruses change over time. Each years vaccine is updated to match the strains expected to be most common. Annual vaccination gives you the best protection against the current flu season.",
      },
    ],
  },
  {
    id: "living-with-hypertension",
    title: "Living with Hypertension Quiz",
    lessonId: "living-with-hypertension",
    passScore: 70,
    questions: [
      {
        question: "What is hypertension?",
        options: [
          "Low blood pressure that causes dizziness",
          "Chronically high blood pressure that puts strain on the heart and blood vessels",
          "A condition where blood pressure goes up and down rapidly",
          "A temporary increase in blood pressure during exercise",
        ],
        correctAnswer: "B",
        explanation:
          "Hypertension means your blood pressure stays higher than normal over time. This constant strain damages arteries and increases the risk of heart attack, stroke, and kidney disease. It is often called the silent killer because it has no symptoms.",
      },
      {
        question: "Which lifestyle change can help lower blood pressure?",
        options: [
          "Eating more salty foods",
          "Reducing sodium intake, eating a balanced diet, and getting regular exercise",
          "Drinking more caffeine",
          "Sleeping fewer than 5 hours per night",
        ],
        correctAnswer: "B",
        explanation:
          "Reducing salt, eating more fruits and vegetables, maintaining a healthy weight, regular physical activity, limiting alcohol, and managing stress can all help lower blood pressure. Even small changes can make a meaningful difference.",
      },
      {
        question: "What is a normal blood pressure reading?",
        options: ["140 over 90 or higher", "130 over 80 or higher", "Below 120 over 80", "150 over 100"],
        correctAnswer: "C",
        explanation:
          "A normal blood pressure reading is below 120 systolic and below 80 diastolic. Readings of 130 over 80 or higher are considered elevated or stage 1 hypertension and should be discussed with your doctor.",
      },
      {
        question: "Why is medication often needed to manage hypertension?",
        options: [
          "Lifestyle changes never work for lowering blood pressure",
          "Some people need medication because lifestyle changes alone are not enough to control their blood pressure",
          "Medication cures hypertension permanently",
          "Medication is only needed for people over 80",
        ],
        correctAnswer: "B",
        explanation:
          "While lifestyle changes are important, many people with hypertension also need medication to reach a safe blood pressure level. Medications work in different ways to relax blood vessels or reduce fluid volume. Never stop blood pressure medication without talking to your doctor.",
      },
      {
        question: "What should you do if you miss a dose of your blood pressure medication?",
        options: [
          "Take two doses together when you remember",
          "Skip the dose and do not worry about it",
          "Follow the instructions on your prescription label or ask your pharmacist",
          "Stop taking all medications until you see your doctor",
        ],
        correctAnswer: "C",
        explanation:
          "If you miss a dose, check your prescription label or call your pharmacist. Some medications should be taken as soon as you remember, while others should be skipped if it is close to the next dose. Never double up unless instructed.",
      },
    ],
  },
  {
    id: "understanding-type2-diabetes",
    title: "Understanding Type 2 Diabetes Quiz",
    lessonId: "understanding-type2-diabetes",
    passScore: 70,
    questions: [
      {
        question: "What happens in the body of someone with type 2 diabetes?",
        options: [
          "The body produces too much insulin",
          "The body becomes resistant to insulin or does not produce enough insulin to control blood sugar",
          "The body cannot digest carbohydrates at all",
          "The body stops producing red blood cells",
        ],
        correctAnswer: "B",
        explanation:
          "In type 2 diabetes, your cells become resistant to insulin, a hormone that helps sugar enter your cells for energy. Over time, the pancreas cannot produce enough insulin to keep blood sugar levels normal. This leads to high blood sugar.",
      },
      {
        question: "What is a common symptom of uncontrolled high blood sugar?",
        options: [
          "Weight gain and slow heart rate",
          "Frequent urination, excessive thirst, and unexplained weight loss",
          "Improved vision and hearing",
          "Decreased appetite and difficulty sleeping",
        ],
        correctAnswer: "B",
        explanation:
          "When blood sugar is high, your kidneys work overtime to remove excess sugar through urine. This causes frequent urination and thirst. Other symptoms include fatigue, blurry vision, and slow-healing cuts. These symptoms develop gradually in type 2 diabetes.",
      },
      {
        question: "How can diet help manage type 2 diabetes?",
        options: [
          "Eating only one meal per day",
          "Avoiding all carbohydrates completely",
          "Eating balanced meals with controlled portions, limiting sugar and refined carbs",
          "Drinking only fruit juice",
        ],
        correctAnswer: "C",
        explanation:
          "A diabetes-friendly diet focuses on portion control, fiber-rich foods, lean protein, and healthy fats. Monitoring carbohydrate intake helps keep blood sugar stable. A registered dietitian can help create a personalized meal plan.",
      },
      {
        question: "What is the A1C test?",
        options: [
          "A daily blood sugar test done with a finger stick",
          "A blood test that measures average blood sugar levels over the past 2 to 3 months",
          "A test for kidney function",
          "A urine test for ketones",
        ],
        correctAnswer: "B",
        explanation:
          "The A1C test provides an average of your blood sugar levels over the past 2 to 3 months. It shows how well your diabetes is being managed. Most people with diabetes should have an A1C test at least twice a year.",
      },
      {
        question: "What foot care practice is important for people with diabetes?",
        options: [
          "Walking barefoot to strengthen the feet",
          "Checking feet daily for cuts, blisters, or sores",
          "Soaking feet in hot water every night",
          "Applying ice to the feet before bed",
        ],
        correctAnswer: "B",
        explanation:
          "Diabetes can reduce blood flow and sensation in the feet, making it hard to feel injuries. Small cuts can become infected and lead to serious complications. Daily foot checks help catch problems early before they become severe.",
      },
    ],
  },
  {
    id: "asthma-basics",
    title: "Asthma Basics Quiz",
    lessonId: "asthma-basics",
    passScore: 70,
    questions: [
      {
        question: "What is asthma?",
        options: [
          "A condition where the lungs fill with fluid",
          "A chronic condition where airways become inflamed and narrow, making it hard to breathe",
          "A temporary infection of the throat",
          "A type of allergic reaction to food",
        ],
        correctAnswer: "B",
        explanation:
          "Asthma is a chronic lung condition. The airways become swollen, produce extra mucus, and the muscles around them tighten. This narrows the airways and causes wheezing, coughing, chest tightness, and shortness of breath.",
      },
      {
        question: "What is a common trigger for asthma symptoms?",
        options: [
          "Drinking cold water",
          "Exercise, allergies, cold air, or respiratory infections",
          "Eating too much protein",
          "Exposure to sunlight",
        ],
        correctAnswer: "B",
        explanation:
          "Asthma triggers vary by person but commonly include pollen, dust mites, pet dander, mold, cold air, exercise, smoke, and colds or flu. Identifying and avoiding your personal triggers is a key part of asthma management.",
      },
      {
        question: "What is the difference between a rescue inhaler and a controller inhaler?",
        options: [
          "There is no difference",
          "Rescue inhalers are used daily; controller inhalers are used only in emergencies",
          "Rescue inhalers provide quick relief during an asthma attack; controller inhalers reduce airway inflammation over time",
          "Controller inhalers are only for children",
        ],
        correctAnswer: "C",
        explanation:
          "Rescue inhalers contain quick-acting medication that relaxes airway muscles during an attack, providing fast relief. Controller inhalers contain anti-inflammatory medication taken daily to prevent symptoms. Both play important roles in asthma management.",
      },
      {
        question: "What should you do if your rescue inhaler does not relieve asthma symptoms?",
        options: [
          "Wait another hour and try again",
          "Take a hot shower to open your airways",
          "Seek emergency medical help immediately",
          "Drink a large amount of water",
        ],
        correctAnswer: "C",
        explanation:
          "If your rescue inhaler does not work or symptoms get worse, seek emergency care right away. Severe asthma attacks can be life-threatening. Signs of a severe attack include gasping for air, inability to speak full sentences, and blue lips or fingernails.",
      },
      {
        question: "Can asthma be cured?",
        options: [
          "Yes, with the right medication",
          "No, asthma is a chronic condition that can be managed but not cured",
          "Yes, but only with surgery",
          "Yes, it goes away on its own after childhood",
        ],
        correctAnswer: "B",
        explanation:
          "Asthma is a chronic condition with no cure, but it can be effectively managed. With proper treatment, an asthma action plan, and avoiding triggers, most people with asthma can live active, full lives without frequent symptoms.",
      },
    ],
  },
  {
    id: "introduction-to-heart-disease",
    title: "Introduction to Heart Disease Quiz",
    lessonId: "introduction-to-heart-disease",
    passScore: 70,
    questions: [
      {
        question: "What is heart disease?",
        options: [
          "Any condition that affects the brain",
          "A group of conditions that affect the heart and blood vessels, including coronary artery disease",
          "An infection of the heart muscle",
          "A temporary condition that only affects older adults",
        ],
        correctAnswer: "B",
        explanation:
          "Heart disease is an umbrella term for conditions affecting the heart and blood vessels. The most common type is coronary artery disease, where plaque builds up in the arteries supplying blood to the heart. Heart disease is the leading cause of death in the United States.",
      },
      {
        question: "What is a heart attack?",
        options: [
          "When the heart stops beating completely",
          "When blood flow to a part of the heart muscle is blocked, usually by a blood clot",
          "When the heart beats too fast temporarily",
          "When the lungs stop working",
        ],
        correctAnswer: "B",
        explanation:
          "A heart attack occurs when blood flow to the heart is severely reduced or blocked, usually by a clot in a narrowed artery. Without oxygen, heart muscle begins to die. Quick treatment is critical to minimize damage.",
      },
      {
        question: "Which of the following is a major risk factor for heart disease?",
        options: [
          "Getting enough sleep",
          "High blood pressure, high cholesterol, and smoking",
          "Eating a balanced diet",
          "Regular physical activity",
        ],
        correctAnswer: "B",
        explanation:
          "Major risk factors for heart disease include high blood pressure, high cholesterol, smoking, diabetes, obesity, and a family history of heart disease. Many of these can be managed through lifestyle changes and medication.",
      },
      {
        question: "What lifestyle habit can reduce your risk of heart disease?",
        options: [
          "Smoking cigarettes in moderation",
          "Eating a diet rich in fruits, vegetables, whole grains, and lean proteins",
          "Drinking large amounts of alcohol every day",
          "Sitting for most of the day without physical activity",
        ],
        correctAnswer: "B",
        explanation:
          "A heart-healthy diet includes plenty of fruits, vegetables, whole grains, lean proteins, and healthy fats while limiting saturated fats, trans fats, sodium, and added sugars. Combined with regular exercise and not smoking, this can significantly reduce heart disease risk.",
      },
      {
        question: "What does CPR stand for and what is its purpose?",
        options: [
          "Cardiac Pulse Regulation; it regulates the heart rhythm",
          "Cardiopulmonary Resuscitation; it keeps blood and oxygen flowing during cardiac arrest",
          "Cardio-Pulmonary Recovery; it helps after a heart attack",
          "Cardiac Prevention Routine; it prevents heart disease",
        ],
        correctAnswer: "B",
        explanation:
          "CPR combines chest compressions and rescue breaths to keep blood and oxygen flowing to the brain and organs when a persons heart has stopped. Bystander CPR can double or triple a cardiac arrest victims chance of survival.",
      },
    ],
  },
  {
    id: "understanding-depression",
    title: "Understanding Depression Quiz",
    lessonId: "understanding-depression",
    passScore: 70,
    questions: [
      {
        question: "What is depression?",
        options: [
          "The same as feeling sad for a few hours after a bad day",
          "A common but serious mood disorder that affects how you feel, think, and handle daily activities",
          "A sign of personal weakness",
          "An illness that only affects older adults",
        ],
        correctAnswer: "B",
        explanation:
          "Depression is a medical condition, not a character flaw or temporary sadness. It involves persistent feelings of sadness, loss of interest in activities, and changes in sleep, appetite, and energy. It affects people of all ages and backgrounds.",
      },
      {
        question: "Which of the following is a common symptom of depression?",
        options: [
          "Feeling unusually happy and energetic for weeks",
          "Persistent sadness, loss of interest in hobbies, and changes in sleep or appetite",
          "Sudden improvement in memory and concentration",
          "Increased desire to socialize with others",
        ],
        correctAnswer: "B",
        explanation:
          "Common depression symptoms include persistent sadness or emptiness, loss of interest in activities once enjoyed, significant changes in weight or appetite, trouble sleeping or sleeping too much, low energy, difficulty concentrating, and thoughts of death or suicide.",
      },
      {
        question: "How is depression typically treated?",
        options: [
          "Depression does not need treatment; it goes away on its own",
          "Through therapy, medication, or a combination of both",
          "Only by taking herbal supplements",
          "By exercising for 12 hours a day",
        ],
        correctAnswer: "B",
        explanation:
          "Depression is highly treatable. The most effective approaches include psychotherapy or talk therapy, antidepressant medication, or both. Lifestyle changes like regular exercise and social support also help. What works best varies from person to person.",
      },
      {
        question: "If someone says they are thinking about suicide, what should you do?",
        options: [
          "Ignore it because people who talk about suicide rarely mean it",
          "Take it seriously, stay with them, and help them contact a crisis helpline or emergency services",
          "Tell them to think about something else",
          "Wait to see if they mention it again",
        ],
        correctAnswer: "B",
        explanation:
          "Any mention of suicide should be taken seriously. Stay with the person and call or text 988 (the Suicide and Crisis Lifeline) or 911. Do not leave them alone. Talking about suicide does not increase the risk; it provides an opportunity to help.",
      },
      {
        question: "Can depression affect physical health?",
        options: [
          "No, depression is only in your mind",
          "Yes, depression can cause physical symptoms like headaches, digestive problems, and chronic pain",
          "No, mental health and physical health are completely separate",
          "Yes, but only in people over 60",
        ],
        correctAnswer: "B",
        explanation:
          "Depression affects both mind and body. It can cause fatigue, headaches, back pain, digestive issues, and worsen chronic conditions like heart disease or diabetes. Treating depression often improves both mental and physical health.",
      },
    ],
  },
  {
    id: "anxiety-and-panic",
    title: "Anxiety and Panic Quiz",
    lessonId: "anxiety-and-panic",
    passScore: 70,
    questions: [
      {
        question: "What is the difference between normal anxiety and an anxiety disorder?",
        options: [
          "There is no difference",
          "Normal anxiety is temporary and proportional to a situation; an anxiety disorder involves excessive, persistent worry that interferes with daily life",
          "Anxiety disorders are caused by bad parenting",
          "Normal anxiety only happens at night",
        ],
        correctAnswer: "B",
        explanation:
          "Everyone feels anxious sometimes. Normal anxiety is a natural response to stress and goes away when the situation passes. An anxiety disorder involves intense, excessive worry that lasts for months and makes it hard to work, sleep, or socialize.",
      },
      {
        question: "What is a panic attack?",
        options: [
          "A sudden, intense wave of fear that triggers severe physical reactions even when there is no real danger",
          "A mild feeling of nervousness before a test",
          "A chronic state of worry that lasts all day",
          "A type of allergic reaction",
        ],
        correctAnswer: "A",
        explanation:
          "Panic attacks come on suddenly and can include racing heart, chest pain, sweating, shaking, shortness of breath, and a feeling of losing control. Many people mistake panic attacks for heart attacks. They usually peak within 10 minutes.",
      },
      {
        question: "Which of the following is a common symptom of generalized anxiety disorder?",
        options: [
          "Feeling perfectly calm in all situations",
          "Excessive worry about everyday things like work, health, or family that is hard to control",
          "Complete inability to feel fear",
          "Sudden bursts of uncontrollable laughter",
        ],
        correctAnswer: "B",
        explanation:
          "People with generalized anxiety disorder worry excessively about a variety of everyday concerns. The worry is out of proportion to the situation, difficult to control, and often accompanied by restlessness, fatigue, muscle tension, and trouble sleeping.",
      },
      {
        question: "What breathing technique can help during a moment of acute anxiety?",
        options: [
          "Holding your breath for as long as possible",
          "Taking fast, shallow breaths",
          "Slow, deep breathing where you breathe in for 4 counts, hold for 4, and breathe out for 4",
          "Breathing only through your mouth rapidly",
        ],
        correctAnswer: "C",
        explanation:
          "Slow, deep breathing activates the parasympathetic nervous system, which helps calm the bodys stress response. Box breathing in for 4, hold for 4, out for 4 is a simple technique that can reduce anxiety symptoms in the moment.",
      },
      {
        question: "Is anxiety treatable?",
        options: [
          "No, anxiety is a lifelong sentence",
          "Yes, anxiety disorders are highly treatable with therapy, medication, or both",
          "Yes, but only with medication that has severe side effects",
          "No, anxiety can only be managed with alcohol",
        ],
        correctAnswer: "B",
        explanation:
          "Anxiety disorders are very treatable. Cognitive behavioral therapy is particularly effective. Many people also benefit from medication. With proper treatment, most people with anxiety disorders can manage their symptoms and live full, productive lives.",
      },
    ],
  },
  {
    id: "sleep-and-health",
    title: "Sleep and Health Quiz",
    lessonId: "sleep-and-health",
    passScore: 70,
    questions: [
      {
        question: "How many hours of sleep do most adults need per night?",
        options: ["4 to 5 hours", "7 to 9 hours", "10 to 12 hours", "5 to 6 hours"],
        correctAnswer: "B",
        explanation:
          "Most adults need 7 to 9 hours of quality sleep per night for optimal health. Consistent sleep helps your body repair, supports brain function, and strengthens your immune system. Sleeping too little over time increases health risks.",
      },
      {
        question: "What is sleep hygiene?",
        options: [
          "Washing your bedsheets every night",
          "Habits and practices that promote good, consistent sleep",
          "A special diet for people who cannot sleep",
          "Using medication to fall asleep faster",
        ],
        correctAnswer: "B",
        explanation:
          "Sleep hygiene refers to healthy sleep habits like keeping a consistent bedtime, avoiding screens before bed, limiting caffeine in the evening, and creating a cool, dark, quiet sleep environment. Good sleep hygiene helps you fall asleep and stay asleep.",
      },
      {
        question: "How does chronic lack of sleep affect your health?",
        options: [
          "It has no effect on health",
          "It increases the risk of obesity, heart disease, diabetes, and weakened immune function",
          "It only affects your mood, not your physical health",
          "It improves memory and concentration",
        ],
        correctAnswer: "B",
        explanation:
          "Chronic sleep deprivation is linked to serious health problems including obesity, heart disease, high blood pressure, diabetes, and depression. It also weakens the immune system, making you more likely to get sick.",
      },
      {
        question: "What is sleep apnea?",
        options: [
          "A condition where you cannot fall asleep at night",
          "A disorder where breathing repeatedly stops and starts during sleep",
          "A condition where you sleep too much",
          "A temporary phase of insomnia",
        ],
        correctAnswer: "B",
        explanation:
          "Sleep apnea causes repeated pauses in breathing during sleep, which reduces oxygen levels and disrupts sleep quality. Common signs include loud snoring, gasping for air during sleep, and daytime fatigue. It can increase the risk of heart problems if untreated.",
      },
      {
        question: "What should you avoid before bedtime to improve sleep?",
        options: [
          "Reading a book",
          "Using phones, tablets, or computers because blue light can interfere with your body's sleep signals",
          "Drinking herbal tea",
          "Taking a warm bath",
        ],
        correctAnswer: "B",
        explanation:
          "Blue light from screens suppresses melatonin, the hormone that signals your body to sleep. Avoiding screens for at least 30 to 60 minutes before bed, along with limiting caffeine and heavy meals, helps you fall asleep more easily.",
      },
    ],
  },
  {
    id: "understanding-health-insurance",
    title: "Understanding Health Insurance Quiz",
    lessonId: "understanding-health-insurance",
    passScore: 70,
    questions: [
      {
        question: "What is a health insurance premium?",
        options: [
          "The amount you pay when you visit the doctor",
          "The monthly payment you make to keep your insurance active",
          "The discount you get for using in-network providers",
          "The total amount your employer pays for your healthcare",
        ],
        correctAnswer: "B",
        explanation:
          "A premium is the amount you pay each month to have health insurance coverage. You pay this whether or not you use medical services. Premiums vary based on the plan type, coverage level, and your age or location.",
      },
      {
        question: "What is a deductible in health insurance?",
        options: [
          "The amount you pay each time you fill a prescription",
          "The amount you must pay out of pocket before your insurance starts covering services",
          "The monthly payment to keep your insurance",
          "The maximum amount your insurance will pay in a year",
        ],
        correctAnswer: "B",
        explanation:
          "A deductible is the amount you pay for covered healthcare services before your insurance plan starts to pay. For example, if your deductible is 1,000 dollars, you pay the first 1,000 dollars of covered services yourself. Some preventive services are covered before you meet the deductible.",
      },
      {
        question: 'What does "in-network" mean?',
        options: [
          "Doctors and hospitals that have a contract with your insurance plan to provide care at lower rates",
          "Any doctor or hospital you choose to visit",
          "A special network of doctors who only treat emergencies",
          "Online doctors who you can only see through a computer",
        ],
        correctAnswer: "A",
        explanation:
          "In-network providers have agreed to accept your insurance plans negotiated rates. Using in-network providers usually costs you much less than going out-of-network. Always check if your doctor is in-network before scheduling to avoid surprise bills.",
      },
      {
        question: "What is a copay?",
        options: [
          "A fixed amount you pay for a specific service, like 20 dollars for a doctors visit",
          "The total cost of your medical treatment",
          "A discount you receive for paying your premium early",
          "The amount your insurance pays to the hospital",
        ],
        correctAnswer: "A",
        explanation:
          "A copay is a fixed dollar amount you pay at the time of service, such as 20 dollars for a primary care visit or 10 dollars for a prescription. Copays are separate from deductibles and usually do not count toward the deductible.",
      },
      {
        question: "What is an out-of-pocket maximum?",
        options: [
          "The amount you can save by using insurance",
          "The most you will have to pay for covered services in a plan year",
          "The amount you owe if you cancel your insurance",
          "The maximum amount your insurance pays for a single procedure",
        ],
        correctAnswer: "B",
        explanation:
          "The out-of-pocket maximum is the most you will pay for covered healthcare services in a year. Once you reach this limit, your insurance pays 100 percent of covered services for the rest of the plan year. This protects you from catastrophic medical costs.",
      },
    ],
  },
  {
    id: "reading-medical-bills",
    title: "Reading Medical Bills Quiz",
    lessonId: "reading-medical-bills",
    passScore: 70,
    questions: [
      {
        question: "What should you check first when you receive a medical bill?",
        options: [
          "Whether the bill is printed on official letterhead",
          "Whether your personal information, the dates of service, and the services listed are correct",
          "Whether the bill has a watermark",
          "Whether the envelope is sealed properly",
        ],
        correctAnswer: "B",
        explanation:
          "Always verify your name, the dates you received care, and the procedures listed. Mistakes in billing are common. An incorrect date, wrong procedure code, or mixed-up patient information can lead to being charged for services you did not receive.",
      },
      {
        question: "What is an Explanation of Benefits or EOB?",
        options: [
          "A bill that shows how much you owe",
          "A summary from your insurance company showing what services were billed, what was covered, and what you may owe",
          "A letter explaining why your insurance was denied",
          "A form you fill out to apply for insurance",
        ],
        correctAnswer: "B",
        explanation:
          "An EOB is not a bill. It is a statement from your insurance explaining how a claim was processed. It shows the amount billed, the insurance discount, what the insurance paid, and your remaining responsibility. Compare it with the providers bill to check for errors.",
      },
      {
        question: 'What does a "CPT code" on a medical bill represent?',
        options: [
          "The patients condition or diagnosis",
          "A standard code that describes the medical procedure or service that was provided",
          "The doctors license number",
          "The hospitals room number",
        ],
        correctAnswer: "B",
        explanation:
          "CPT codes are standardized numbers assigned to every medical procedure and service, like a 99213 for an office visit. These codes determine how much you are charged and whether your insurance will cover the service. Errors in coding can lead to incorrect charges.",
      },
      {
        question: "If you cannot afford to pay a medical bill, what should you do?",
        options: [
          "Ignore it and hope it goes away",
          "Contact the billing office to ask about payment plans or financial assistance",
          "Pay only half and assume that is enough",
          "Dispute the entire bill without any reason",
        ],
        correctAnswer: "B",
        explanation:
          "Most hospitals and medical providers offer payment plans or charity care programs for patients who cannot pay their full bill. Contact the billing office and ask about options. Ignoring the bill can lead to collection actions and damage to your credit.",
      },
      {
        question: "What is a common reason medical bills contain errors?",
        options: [
          "Hospitals intentionally overcharge all patients",
          "Billing is complex and errors like duplicate charges, wrong codes, or incorrect insurance information are common",
          "Doctors do not know how much services cost",
          "Insurance companies refuse to share information",
        ],
        correctAnswer: "B",
        explanation:
          "Medical billing is complicated and error-prone. Common mistakes include duplicate charges for the same service, upcoding (billing for a more expensive service than was provided), and incorrect insurance information. Reviewing bills carefully can save you money.",
      },
    ],
  },
  {
    id: "when-to-call-911",
    title: "When to Call 911 Quiz",
    lessonId: "when-to-call-911",
    passScore: 70,
    questions: [
      {
        question: "Which of the following is a reason to call 911?",
        options: [
          "You have a mild cold and want to see a doctor",
          "Someone is unconscious, not breathing, or having chest pain",
          "You need a ride to the pharmacy",
          "Your internet service is not working",
        ],
        correctAnswer: "B",
        explanation:
          "Call 911 for any life-threatening emergency: difficulty breathing, chest pain, signs of stroke, severe bleeding, choking, unconsciousness, or someone who stops breathing. When in doubt, call. Dispatchers can guide you on what to do while help arrives.",
      },
      {
        question: "What should you do first when calling 911?",
        options: [
          "Hang up and call your doctor instead",
          "Stay as calm as possible and clearly tell the dispatcher your location and what is happening",
          "Start performing first aid before calling",
          "Look up the nearest hospital address",
        ],
        correctAnswer: "B",
        explanation:
          "Stay calm and give the dispatcher your exact location and a clear description of the emergency. Answer their questions. They are trained to help you and will give instructions. Do not hang up until the dispatcher tells you to.",
      },
      {
        question: "If someone is choking but is coughing forcefully, what should you do?",
        options: [
          "Perform the Heimlich maneuver immediately",
          "Encourage them to keep coughing and stay with them",
          "Call 911 right away",
          "D） Give them water to drink",
        ],
        correctAnswer: "B",
        explanation:
          "If a choking person is coughing forcefully, their airway is partially blocked and they may be able to clear it on their own. Stay with them and encourage them to keep coughing. Only perform abdominal thrusts if they cannot cough, speak, or breathe.",
      },
      {
        question: "When should you NOT call 911?",
        options: [
          "When someone is having a severe allergic reaction",
          "When you have a minor cut that you can treat with a bandage at home",
          "When you witness a car accident with injuries",
          "When someone is having a stroke",
        ],
        correctAnswer: "B",
        explanation:
          "911 is for emergencies that threaten life, limb, or property. Minor injuries that can be treated at home, routine medical questions, or non-urgent transportation needs should be handled through your primary care doctor or urgent care.",
      },
      {
        question: "What information should you have ready when calling 911?",
        options: [
          "The patients favorite color",
          "Your exact location, what happened, how many people are hurt, and the patients condition",
          "The patients social security number",
          "The patients blood type",
        ],
        correctAnswer: "B",
        explanation:
          "The dispatcher needs to know where to send help, what kind of emergency it is, and how many people are involved. Knowing the patients condition (conscious, breathing, bleeding) helps dispatchers send the right resources and give you instructions.",
      },
    ],
  },
  {
    id: "building-first-aid-kit",
    title: "Building a First Aid Kit Quiz",
    lessonId: "building-first-aid-kit",
    passScore: 70,
    questions: [
      {
        question: "Which of the following is an essential item for a basic first aid kit?",
        options: ["A sewing kit", "Adhesive bandages in assorted sizes", "A bottle of soda", "A magazine"],
        correctAnswer: "B",
        explanation:
          "Adhesive bandages are one of the most basic and essential first aid items. A well-stocked kit should include various sizes for cuts, scrapes, and blisters. They protect wounds from dirt and bacteria while they heal.",
      },
      {
        question: "What is the purpose of including antiseptic wipes in a first aid kit?",
        options: [
          "To clean your hands before eating",
          "To clean the skin around a wound to prevent infection",
          "To wipe up spilled liquids",
          "To remove makeup",
        ],
        correctAnswer: "B",
        explanation:
          "Antiseptic wipes kill germs on the skin around a wound, reducing the risk of infection. Clean the wound gently before applying a bandage. Do not use alcohol directly inside deep wounds, as it can damage tissue.",
      },
      {
        question: "Why should you include a CPR face mask or shield in your first aid kit?",
        options: [
          "To protect yourself from the sun",
          "To safely perform rescue breaths without direct mouth-to-mouth contact",
          "To cover your face during cold weather",
          "To filter dust from the air",
        ],
        correctAnswer: "B",
        explanation:
          "A CPR face mask or shield creates a barrier when giving rescue breaths, reducing the risk of disease transmission. It is a small, inexpensive item that makes bystanders more willing to perform CPR in an emergency.",
      },
      {
        question: "How often should you check and restock your first aid kit?",
        options: [
          "Once every 10 years",
          "Every few months to replace expired items and restock used supplies",
          "Never, once it is stocked it lasts forever",
          "Only after using it for a major emergency",
        ],
        correctAnswer: "B",
        explanation:
          "Check your first aid kit every few months. Replace expired medications, restock used bandages and wipes, and make sure the flashlight batteries work. A kit that is out of date or missing supplies is not helpful in an emergency.",
      },
      {
        question: "Where is the best place to store a first aid kit in your home?",
        options: [
          "In a locked safe that only adults can open",
          "In an easily accessible location that everyone in the household knows about",
          "In the garage behind boxes",
          "In a high cabinet that requires a step stool to reach",
        ],
        correctAnswer: "B",
        explanation:
          "Your first aid kit should be easy to reach in an emergency. Place it in a central, accessible location and make sure all household members know where it is. Avoid locking it, as seconds matter during an injury.",
      },
    ],
  },
  {
    id: "reading-nutrition-labels",
    title: "Reading Nutrition Labels Quiz",
    lessonId: "reading-nutrition-labels",
    passScore: 70,
    questions: [
      {
        question: "What is the first thing you should look at on a nutrition facts label?",
        options: [
          "The brand name",
          "The serving size and the number of servings per container",
          "The expiration date",
          "The ingredient list in small font",
        ],
        correctAnswer: "B",
        explanation:
          "Serving size is the foundation of the nutrition label. All the information on the label is based on one serving. If you eat two servings, you need to double all the numbers. Many packages that look like single servings actually contain multiple servings.",
      },
      {
        question: 'What does the "% Daily Value" tell you on a nutrition label?',
        options: [
          "The exact number of calories you should eat each day",
          "How much a nutrient in one serving contributes to a daily diet based on a 2,000-calorie diet",
          "The percentage of the food that is fat",
          "The amount of sugar you should eat per day",
        ],
        correctAnswer: "B",
        explanation:
          "Percent Daily Value shows how much a nutrient in one serving contributes to a total daily diet. A DV of 5 percent or less is low, and 20 percent or more is high. Use this to quickly compare foods and see if they are high or low in specific nutrients.",
      },
      {
        question:
          "Which of the following nutrients should you try to limit according to the nutrition label?",
        options: ["Dietary fiber", "Vitamin D", "Saturated fat, sodium, and added sugars", "Potassium"],
        correctAnswer: "C",
        explanation:
          "Health experts recommend limiting saturated fat, sodium, and added sugars because they are linked to heart disease, high blood pressure, and other health problems. Look for low DV percentages for these nutrients. Fiber, vitamins, and minerals are beneficial.",
      },
      {
        question: 'What is the difference between "total sugars" and "added sugars" on a label?',
        options: [
          "They are the same thing",
          "Total sugars includes natural and added sugars; added sugars shows how much sugar was added during processing",
          "Added sugars only includes artificial sweeteners",
          "Total sugars does not include sugar from fruit",
        ],
        correctAnswer: "B",
        explanation:
          "Total sugars includes both naturally occurring sugars found in foods like fruit and dairy plus any sugars added during processing. Added sugars specifically shows how much sugar was added. The American Heart Association recommends limiting added sugars.",
      },
      {
        question: "Why is the ingredient list important on a food package?",
        options: [
          "It shows the brand name",
          "Ingredients are listed in descending order by weight, so the first ingredients make up the most of the food",
          "It tells you when the food was manufactured",
          "It lists the price per ingredient",
        ],
        correctAnswer: "B",
        explanation:
          "Ingredients are listed from the most to the least by weight. If sugar or a type of oil is listed first, the product is mostly made of that ingredient. This helps you identify hidden sources of sugar, unhealthy fats, and artificial additives.",
      },
    ],
  },
  {
    id: "building-balanced-plate",
    title: "Building a Balanced Plate Quiz",
    lessonId: "building-balanced-plate",
    passScore: 70,
    questions: [
      {
        question:
          "According to the MyPlate model, what portions of your plate should be filled with fruits and vegetables?",
        options: [
          "One quarter",
          "About half of the plate",
          "The entire plate",
          "A small corner of the plate",
        ],
        correctAnswer: "B",
        explanation:
          "The MyPlate model recommends filling half your plate with fruits and vegetables. These foods are rich in vitamins, minerals, and fiber while being low in calories. Eating a variety of colorful produce ensures you get a range of nutrients.",
      },
      {
        question: "What type of grains should make up at least half of the grains you eat?",
        options: [
          "Refined white grains like white bread and white rice",
          "Whole grains like whole wheat, brown rice, oats, and quinoa",
          "Enriched grains only",
          "Grain-based desserts like cookies and cake",
        ],
        correctAnswer: "B",
        explanation:
          "Whole grains contain the entire grain kernel, providing more fiber, protein, vitamins, and minerals than refined grains. Fiber helps with digestion, keeps you full longer, and can lower cholesterol and blood sugar levels.",
      },
      {
        question: "What is a healthy source of protein to include on your plate?",
        options: [
          "Fried chicken and bacon",
          "Lean meat, poultry, fish, beans, eggs, nuts, and tofu",
          "Processed lunch meats",
          "Foods fried in oil",
        ],
        correctAnswer: "B",
        explanation:
          "Healthy protein sources include lean meats, fish, poultry, eggs, beans, lentils, tofu, nuts, and seeds. These provide essential amino acids without excess saturated fat. Aim for a variety of protein sources throughout the week.",
      },
      {
        question: "What type of fat is considered heart-healthy?",
        options: [
          "Saturated fats found in butter and red meat",
          "Trans fats found in many processed snacks",
          "Unsaturated fats found in olive oil, avocados, nuts, and fish",
          "All fats are equally healthy",
        ],
        correctAnswer: "C",
        explanation:
          "Unsaturated fats, including monounsaturated and polyunsaturated fats, can help improve cholesterol levels and reduce heart disease risk. Sources include olive oil, avocados, nuts, seeds, and fatty fish like salmon. Limit saturated and avoid trans fats.",
      },
      {
        question: "What should you drink with a balanced meal for the healthiest choice?",
        options: [
          "Sugary soda or sweetened tea",
          "Water or unsweetened beverages",
          "Energy drinks",
          "Fruit punch with added sugar",
        ],
        correctAnswer: "B",
        explanation:
          "Water is the healthiest choice to accompany any meal. It hydrates without adding calories or sugar. Sugary drinks are a major source of added sugar and empty calories. Unsweetened tea or milk are also good options.",
      },
    ],
  },
] as const;
