// Auto-generated by scripts/bundle-quizzes.ts — do not edit by hand.
// Edit content/quizzes/{en,es}/*.mdx then run: npm run content:bundle-quizzes

import type { Quiz } from "@/types/quiz";

import { quizzes as en } from "./quizBundles.en";
import { quizzes as es } from "./quizBundles.es";

export const quizBundles: Record<"en" | "es", Quiz[]> = { en, es } as const;
